using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.SmartWorkflow;

namespace InovaGed.Infrastructure.SmartWorkflow;

public sealed class SmartWorkflowService(IDbConnectionFactory db) : ISmartWorkflowTaskService, ISmartWorkflowNumberGenerator
{
 public async Task<string> NextAsync(Guid tenantId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var n=await c.ExecuteScalarAsync<long>(new CommandDefinition("select count(*)+1 from ged.smart_workflow_task where tenant_id=@tenantId",new{tenantId},cancellationToken:ct));return $"WF-{DateTime.UtcNow:yyyyMMdd}-{n:000000}";}
 public async Task<Guid> CreateAsync(SmartWorkflowTaskCreateCommand x,CancellationToken ct){await using var c=await db.OpenAsync(ct);var existing=await c.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from ged.smart_workflow_task where tenant_id=@TenantId and source_type=@SourceType and source_id is not distinct from @SourceId and task_type=@TaskType and status in ('OPEN','IN_PROGRESS','WAITING') and reg_status='A' limit 1",x,cancellationToken:ct));if(existing.HasValue)return existing.Value;var number=await NextAsync(x.TenantId,ct);var id=Guid.NewGuid();var hours=x.Priority switch{SmartWorkflowPriority.Critical=>4,SmartWorkflowPriority.High=>8,SmartWorkflowPriority.Low=>120,_=>48};await c.ExecuteAsync(new CommandDefinition("""
insert into ged.smart_workflow_task(id,tenant_id,task_number,source_type,source_id,related_document_id,related_box_id,related_incident_id,related_suggestion_id,task_type,title,description,recommended_action,priority,due_at,opened_by) values(@id,@TenantId,@number,@SourceType,@SourceId,@RelatedDocumentId,@RelatedBoxId,@RelatedIncidentId,@RelatedSuggestionId,@TaskType,@Title,@Description,@RecommendedAction,@Priority,now()+(@hours||' hours')::interval,@OpenedBy);
insert into ged.smart_workflow_event(tenant_id,task_id,event_type,event_message,performed_by) values(@TenantId,@id,'SMART_WORKFLOW_TASK_CREATED','Tarefa criada para revisão humana.',@OpenedBy)
""",new{id,number,hours,x.TenantId,x.SourceType,x.SourceId,x.RelatedDocumentId,x.RelatedBoxId,x.RelatedIncidentId,x.RelatedSuggestionId,x.TaskType,x.Title,x.Description,x.RecommendedAction,x.Priority,x.OpenedBy},cancellationToken:ct));return id;}
 public async Task<SmartWorkflowDashboard> GetDashboardAsync(Guid tenantId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var r=await c.QuerySingleAsync<DashboardRow>(new CommandDefinition("""select count(*) filter(where status in ('OPEN','IN_PROGRESS','WAITING')) OpenTasks,count(*) filter(where status in ('OPEN','IN_PROGRESS','WAITING') and due_at<now()) OverdueTasks,count(*) filter(where status in ('OPEN','IN_PROGRESS','WAITING') and priority='CRITICAL') CriticalTasks,count(*) filter(where status='IN_PROGRESS') InProgressTasks,count(*) filter(where status='COMPLETED' and completed_at>=current_date) CompletedToday,count(*) filter(where task_type='CLASSIFICATION_SUGGESTION_REVIEW' and status in ('OPEN','IN_PROGRESS','WAITING')) ClassificationPending,count(*) filter(where task_type='RETENTION_SUGGESTION_REVIEW' and status in ('OPEN','IN_PROGRESS','WAITING')) RetentionPending,count(*) filter(where task_type='ASSISTANT_ACTION_REVIEW' and status in ('OPEN','IN_PROGRESS','WAITING')) AssistantPending from ged.smart_workflow_task where tenant_id=@tenantId and reg_status='A'""",new{tenantId},cancellationToken:ct));return new(r.OpenTasks,r.OverdueTasks,r.CriticalTasks,r.InProgressTasks,r.CompletedToday,r.ClassificationPending,r.RetentionPending,r.AssistantPending);}
 public async Task<IReadOnlyList<SmartWorkflowTaskItem>> ListAsync(SmartWorkflowTaskFilter f,CancellationToken ct){await using var c=await db.OpenAsync(ct);var rows=await c.QueryAsync<TaskRow>(new CommandDefinition("""select id Id,task_number TaskNumber,source_type SourceType,task_type TaskType,title Title,priority Priority,status Status,assigned_to_name AssignedToName,due_at DueAt,opened_at OpenedAt from ged.smart_workflow_task where tenant_id=@TenantId and reg_status='A' and (@Status is null or status=@Status) and (@Priority is null or priority=@Priority) and (@TaskType is null or task_type=@TaskType) and (@SourceType is null or source_type=@SourceType) and (@DocumentId is null or related_document_id=@DocumentId) and (not @OverdueOnly or due_at<now()) order by case priority when 'CRITICAL' then 1 when 'HIGH' then 2 when 'MEDIUM' then 3 else 4 end,due_at""",f,cancellationToken:ct));return rows.Select(Map).ToArray();}
 public async Task<SmartWorkflowTaskDetails?> GetAsync(Guid tenantId,Guid taskId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var r=await c.QuerySingleOrDefaultAsync<DetailRow>(new CommandDefinition("select *,task_number TaskNumber,source_type SourceType,source_id SourceId,task_type TaskType,assigned_to_name AssignedToName,due_at DueAt,opened_at OpenedAt,related_document_id RelatedDocumentId,related_box_id RelatedBoxId,related_incident_id RelatedIncidentId,related_suggestion_id RelatedSuggestionId,recommended_action RecommendedAction,completion_notes CompletionNotes from ged.smart_workflow_task where tenant_id=@tenantId and id=@taskId and reg_status='A'",new{tenantId,taskId},cancellationToken:ct));if(r is null)return null;var ev=await c.QueryAsync<EventRow>(new CommandDefinition("select event_type EventType,event_message Message,performed_by_name PerformedByName,occurred_at OccurredAt from ged.smart_workflow_event where tenant_id=@tenantId and task_id=@taskId and reg_status='A' order by occurred_at desc",new{tenantId,taskId},cancellationToken:ct));return new(Map(r),r.SourceId,r.RelatedDocumentId,r.RelatedBoxId,r.RelatedIncidentId,r.RelatedSuggestionId,r.Description,r.RecommendedAction,r.CompletionNotes,ev.Select(e=>new SmartWorkflowEventItem(e.EventType,e.Message,e.PerformedByName,e.OccurredAt)).ToArray());}
 public Task AssignAsync(Guid t,Guid id,Guid assigned,Guid by,CancellationToken ct)=>Transition(t,id,by,"SMART_WORKFLOW_TASK_ASSIGNED","assigned_to=@assigned,assigned_to_name='Usuário atribuído'","Tarefa atribuída.",ct,new{assigned});
 public Task StartAsync(Guid t,Guid id,Guid by,CancellationToken ct)=>Transition(t,id,by,"SMART_WORKFLOW_TASK_STARTED","status='IN_PROGRESS',started_at=coalesce(started_at,now())","Tarefa iniciada.",ct);
 public Task CompleteAsync(Guid t,Guid id,Guid by,string notes,CancellationToken ct)=>Transition(t,id,by,"SMART_WORKFLOW_TASK_COMPLETED","status='COMPLETED',completed_by=@by,completed_at=now(),completion_notes=@notes","Tarefa concluída por decisão humana.",ct,new{notes});
 public Task CancelAsync(Guid t,Guid id,Guid by,string reason,CancellationToken ct)=>Transition(t,id,by,"SMART_WORKFLOW_TASK_CANCELLED","status='CANCELLED',completed_by=@by,completed_at=now(),completion_notes=@reason","Tarefa cancelada por decisão humana.",ct,new{reason});
 private async Task Transition(Guid tenantId,Guid id,Guid by,string type,string set,string message,CancellationToken ct,object? extra=null){await using var c=await db.OpenAsync(ct);var p=new DynamicParameters(extra);p.Add("tenantId",tenantId);p.Add("id",id);p.Add("by",by);var changed=await c.ExecuteAsync(new CommandDefinition($"update ged.smart_workflow_task set {set} where tenant_id=@tenantId and id=@id and status not in ('COMPLETED','CANCELLED','REJECTED')",p,cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Tarefa não encontrada, encerrada ou pertencente a outro tenant.");await c.ExecuteAsync(new CommandDefinition("insert into ged.smart_workflow_event(tenant_id,task_id,event_type,event_message,performed_by) values(@tenantId,@id,@type,@message,@by)",new{tenantId,id,type,message,by},cancellationToken:ct));}
 public async Task<IReadOnlyList<SmartWorkflowRuleItem>> ListRulesAsync(Guid tenantId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var r=await c.QueryAsync<RuleRow>(new CommandDefinition("select rule_code Code,title Title,source_type SourceType,task_type TaskType,priority Priority,sla_hours SlaHours,enabled Enabled from ged.smart_workflow_rule where (tenant_id is null or tenant_id=@tenantId) and reg_status='A' order by title",new{tenantId},cancellationToken:ct));return r.Select(x=>new SmartWorkflowRuleItem(x.Code,x.Title,x.SourceType,x.TaskType,x.Priority,x.SlaHours,x.Enabled)).ToArray();}
 private static SmartWorkflowTaskItem Map(TaskRow r)=>new(r.Id,r.TaskNumber,r.SourceType,r.TaskType,r.Title,r.Priority,r.Status,r.AssignedToName,r.DueAt,r.OpenedAt);
 internal class TaskRow{public Guid Id{get;set;}public string TaskNumber{get;set;}="";public string SourceType{get;set;}="";public string TaskType{get;set;}="";public string Title{get;set;}="";public string Priority{get;set;}="";public string Status{get;set;}="";public string? AssignedToName{get;set;}public DateTimeOffset? DueAt{get;set;}public DateTimeOffset OpenedAt{get;set;}}
 internal sealed class DetailRow:TaskRow{public Guid? SourceId{get;set;}public Guid? RelatedDocumentId{get;set;}public Guid? RelatedBoxId{get;set;}public Guid? RelatedIncidentId{get;set;}public Guid? RelatedSuggestionId{get;set;}public string? Description{get;set;}public string? RecommendedAction{get;set;}public string? CompletionNotes{get;set;}}
 internal sealed class EventRow{public string EventType{get;set;}="";public string Message{get;set;}="";public string? PerformedByName{get;set;}public DateTimeOffset OccurredAt{get;set;}}
 internal sealed class DashboardRow{public int OpenTasks{get;set;}public int OverdueTasks{get;set;}public int CriticalTasks{get;set;}public int InProgressTasks{get;set;}public int CompletedToday{get;set;}public int ClassificationPending{get;set;}public int RetentionPending{get;set;}public int AssistantPending{get;set;}}
 internal sealed class RuleRow{public string Code{get;set;}="";public string Title{get;set;}="";public string SourceType{get;set;}="";public string TaskType{get;set;}="";public string Priority{get;set;}="";public int SlaHours{get;set;}public bool Enabled{get;set;}}
}
