namespace InovaGed.Application.HospitalIntelligence;
public sealed class HospitalIntelligenceFilter { public Guid TenantId { get; set; } public DateTime? From { get; set; } public DateTime? To { get; set; } public Guid? FolderId { get; set; } public string? Sector { get; set; } public string? DocumentType { get; set; } public string? Search { get; set; } public int Top { get; set; } = 10; public bool IncludeFinancial { get; set; } = true; public bool IncludeClinicalTerms { get; set; } = true; public bool IncludeOperational { get; set; } = true; public bool BypassCache { get; set; } }
public sealed class HospitalIntelligenceDashboardDto { public int TotalDocuments { get; set; } public int DocumentsWithOcr { get; set; } public int DocumentsWithoutOcr { get; set; } public int OcrPending { get; set; } public int OcrErrors { get; set; } public int UnclassifiedDocuments { get; set; } public int CriticalDocuments { get; set; } public int TotalSectors { get; set; } public IReadOnlyList<KpiCardDto> Cards { get; set; } = []; public IReadOnlyList<TermOccurrenceDto> ClinicalTerms { get; set; } = []; public IReadOnlyList<FinancialSignalDto> FinancialSignals { get; set; } = []; public IReadOnlyList<OperationalSignalDto> OperationalSignals { get; set; } = []; public IReadOnlyList<DocumentAlertDto> Alerts { get; set; } = []; public IReadOnlyList<TimeSeriesPointDto> DocumentsByMonth { get; set; } = []; public IReadOnlyList<RankingItemDto> DocumentsBySector { get; set; } = []; public IReadOnlyList<RankingItemDto> DocumentsByType { get; set; } = []; public string? Warning { get; set; } }
public sealed class KpiCardDto { public string Title { get; set; } = ""; public string Value { get; set; } = "0"; public string Subtitle { get; set; } = ""; public string Icon { get; set; } = "bi-bar-chart"; public string Color { get; set; } = "primary"; public string Trend { get; set; } = ""; }
public sealed class TermOccurrenceDto { public string Term { get; set; } = ""; public string Category { get; set; } = ""; public int Count { get; set; } public int DocumentCount { get; set; } public decimal Percentage { get; set; } public string RiskLevel { get; set; } = "Baixo"; public IReadOnlyList<DocumentReferenceDto> Examples { get; set; } = []; }
public sealed class FinancialSignalDto { public string Indicator { get; set; } = ""; public int Count { get; set; } public decimal? EstimatedValue { get; set; } public string Description { get; set; } = ""; public string RiskLevel { get; set; } = "Baixo"; public IReadOnlyList<DocumentReferenceDto> Documents { get; set; } = []; }
public sealed class OperationalSignalDto { public string Indicator { get; set; } = ""; public int Count { get; set; } public string Description { get; set; } = ""; public string Recommendation { get; set; } = ""; public string RiskLevel { get; set; } = "Baixo"; }
public sealed class DocumentAlertDto { public Guid DocumentId { get; set; } public Guid? VersionId { get; set; } public string Title { get; set; } = ""; public string Folder { get; set; } = ""; public string AlertType { get; set; } = ""; public string Description { get; set; } = ""; public string RiskLevel { get; set; } = "Médio"; public DateTime? CreatedAt { get; set; } }
public sealed class DocumentReferenceDto { public Guid DocumentId { get; set; } public Guid? VersionId { get; set; } public string Title { get; set; } = ""; public string Snippet { get; set; } = ""; public string Folder { get; set; } = ""; public DateTime? CreatedAt { get; set; } }
public sealed class TimeSeriesPointDto { public string Label { get; set; } = ""; public int Value { get; set; } }
public sealed class RankingItemDto { public string Label { get; set; } = ""; public int Value { get; set; } public decimal Percentage { get; set; } }
