using System.Security.Cryptography;
using System.Text.Json;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Continuity;

namespace InovaGed.Infrastructure.Continuity;

public sealed class BackupIntegrityService(IDbConnectionFactory db) : IBackupIntegrityService
{
 public async Task<BackupVerificationResult> VerifyAsync(Guid backupSetId,string workerId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var set=await c.QuerySingleOrDefaultAsync<(string? Path,long Size)>(new CommandDefinition("select location_internal Path,size_bytes Size from ged.backup_set where id=@backupSetId",new{backupSetId},cancellationToken:ct));var findings=new List<string>();if(string.IsNullOrWhiteSpace(set.Path)||!Directory.Exists(set.Path)){findings.Add("STORAGE_UNAVAILABLE");return await SaveAsync(c,backupSetId,workerId,"NOT_VERIFIABLE",findings,ct);}if(Directory.EnumerateFiles(set.Path,"*.partial").Any())findings.Add("PARTIAL_FILE_FOUND");var checksums=Path.Combine(set.Path,"checksums.sha256");var manifest=Path.Combine(set.Path,"manifest.json");var dump=Path.Combine(set.Path,"database.dump");foreach(var path in new[]{checksums,manifest,dump})if(!File.Exists(path))findings.Add("FILE_MISSING: "+Path.GetFileName(path));if(findings.Any(x=>x.StartsWith("FILE_MISSING",StringComparison.Ordinal)))return await SaveAsync(c,backupSetId,workerId,"INVALID",findings,ct);Dictionary<string,string> expected;try{expected=ParseChecksums(await File.ReadAllLinesAsync(checksums,ct));}catch(FormatException){findings.Add("CHECKSUM_INVALID");return await SaveAsync(c,backupSetId,workerId,"INVALID",findings,ct);}await VerifyHashAsync(dump,expected,findings,ct);await VerifyHashAsync(manifest,expected,findings,ct);try{var typed=JsonSerializer.Deserialize<BackupManifest>(await File.ReadAllTextAsync(manifest,ct));if(typed is null||typed.Artifacts.Count==0)findings.Add("MANIFEST_INVALID");else if(typed.Artifacts[0].SizeBytes!=new FileInfo(dump).Length)findings.Add("SIZE_MISMATCH");}catch(JsonException){findings.Add("MANIFEST_INVALID");}return await SaveAsync(c,backupSetId,workerId,findings.Count==0?"VALID":"INVALID",findings,ct);}
 private static Dictionary<string,string> ParseChecksums(IEnumerable<string> lines){var result=new Dictionary<string,string>(StringComparer.Ordinal);foreach(var line in lines){var parts=line.Split("  ",2,StringSplitOptions.None);if(parts.Length!=2||parts[0].Length!=64||!parts[0].All(Uri.IsHexDigit)||Path.GetFileName(parts[1])!=parts[1])throw new FormatException();result[parts[1]]=parts[0];}if(result.Count==0)throw new FormatException();return result;}
 private static async Task VerifyHashAsync(string path,IReadOnlyDictionary<string,string> expected,List<string> findings,CancellationToken ct){var name=Path.GetFileName(path);if(!expected.TryGetValue(name,out var wanted)){findings.Add("CHECKSUM_INVALID: "+name);return;}await using var stream=File.OpenRead(path);var actual=await SHA256.HashDataAsync(stream,ct);if(!CryptographicOperations.FixedTimeEquals(actual,Convert.FromHexString(wanted)))findings.Add("CHECKSUM_MISMATCH: "+name);}
 private static async Task<BackupVerificationResult> SaveAsync(System.Data.Common.DbConnection c,Guid id,string worker,string status,List<string> findings,CancellationToken ct){await using var tx=await c.BeginTransactionAsync(ct);await c.ExecuteAsync(new CommandDefinition("insert into ged.backup_verification(backup_set_id,status,findings_json,worker_id) values(@id,@status,@json::jsonb,@worker)",new{id,status,json=JsonSerializer.Serialize(findings),worker},tx,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition("update ged.backup_set set integrity_status=@status where id=@id",new{id,status},tx,cancellationToken:ct));await tx.CommitAsync(ct);return new(id,status,findings,DateTime.UtcNow);}
}
