using System.Diagnostics;
using System.Security.Cryptography;
using System.Text.Json;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Continuity;
using InovaGed.Application.SystemHealth;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace InovaGed.Infrastructure.Continuity;

public sealed class ContinuityRepository(IDbConnectionFactory db, IOptions<BackupOptions> backupOptions, IOptions<PortabilityOptions> portabilityOptions) : IBackupPolicyService, IBackupCatalogService, IRecoveryObjectiveService, IPortabilityExportService, IRecoveryPlanService, ITenantOffboardingService, IDataDeletionWorkflowService
{
    public async Task<IReadOnlyList<BackupPolicyDto>> ListPoliciesAsync(Guid? tenantId, CancellationToken ct) { await using var c = await db.OpenAsync(ct); var rows = await c.QueryAsync<BackupPolicyDto>("select id, tenant_id TenantId, name, scope, enabled, backup_type BackupType, frequency, scheduled_at ScheduledAt, timezone TimeZone, retention_days RetentionDays, destination_kind DestinationKind, encryption_enabled EncryptionEnabled, auto_verification_enabled AutoVerificationEnabled, auto_restore_test_allowed AutoRestoreTestAllowed, rpo_minutes RpoMinutes, rto_minutes RtoMinutes, status, created_at_utc CreatedAtUtc, updated_at_utc UpdatedAtUtc from ged.backup_policy where (@tenant is null or tenant_id=@tenant or tenant_id is null) order by created_at_utc desc", new { tenant = tenantId }); return rows.AsList(); }
    public async Task<BackupPolicyDto> SaveAsync(BackupPolicyDto p, string userName, string justification, CancellationToken ct) { await using var c = await db.OpenAsync(ct); var id = p.Id == Guid.Empty ? Guid.NewGuid() : p.Id; await c.ExecuteAsync("insert into ged.backup_policy(id,tenant_id,name,scope,enabled,backup_type,frequency,scheduled_at,timezone,retention_days,destination_kind,encryption_enabled,auto_verification_enabled,auto_restore_test_allowed,rpo_minutes,rto_minutes,status,created_by,change_justification) values (@id,@TenantId,@Name,@Scope,@Enabled,@BackupType,@Frequency,@ScheduledAt,@TimeZone,@RetentionDays,@DestinationKind,@EncryptionEnabled,@AutoVerificationEnabled,@AutoRestoreTestAllowed,@RpoMinutes,@RtoMinutes,@Status,@user,@just) on conflict(id) do update set name=excluded.name,enabled=excluded.enabled,frequency=excluded.frequency,retention_days=excluded.retention_days,updated_at_utc=now(),updated_by=@user,change_justification=@just", new { id, p.TenantId, p.Name, p.Scope, p.Enabled, p.BackupType, p.Frequency, p.ScheduledAt, p.TimeZone, p.RetentionDays, p.DestinationKind, p.EncryptionEnabled, p.AutoVerificationEnabled, p.AutoRestoreTestAllowed, p.RpoMinutes, p.RtoMinutes, p.Status, user=userName, just=justification }); return p with { Id = id }; }
    public async Task<IReadOnlyList<BackupSetDto>> ListAsync(Guid? tenantId, string? status, CancellationToken ct) { await using var c = await db.OpenAsync(ct); var rows = await c.QueryAsync<BackupSetDto>("select id, tenant_id TenantId, backup_type BackupType, started_at_utc StartedAtUtc, finished_at_utc FinishedAtUtc, status, size_bytes SizeBytes, file_count FileCount, integrity_status IntegrityStatus, location_masked LocationMasked, encryption_enabled EncryptionEnabled, manifest_checksum_sha256 ManifestChecksumSha256, correlation_id CorrelationId from ged.backup_set where (@tenant is null or tenant_id=@tenant) and (@status is null or status=@status) order by started_at_utc desc limit 200", new { tenant=tenantId, status }); return rows.AsList(); }
    public async Task<BackupSetDto?> GetAsync(Guid id, Guid? tenantId, CancellationToken ct) { await using var c = await db.OpenAsync(ct); return await c.QuerySingleOrDefaultAsync<BackupSetDto>("select id, tenant_id TenantId, backup_type BackupType, started_at_utc StartedAtUtc, finished_at_utc FinishedAtUtc, status, size_bytes SizeBytes, file_count FileCount, integrity_status IntegrityStatus, location_masked LocationMasked, encryption_enabled EncryptionEnabled, manifest_checksum_sha256 ManifestChecksumSha256, correlation_id CorrelationId from ged.backup_set where id=@id and (@tenant is null or tenant_id=@tenant)", new { id, tenant=tenantId }); }
    public async Task<ContinuityDashboardDto> GetDashboardAsync(Guid? tenantId, CancellationToken ct) { await using var c = await db.OpenAsync(ct); var last = await c.QuerySingleOrDefaultAsync<DateTime?>("select max(finished_at_utc) from ged.backup_set where status='COMPLETED' and (@tenant is null or tenant_id=@tenant)", new { tenant=tenantId }); var valid = await c.QuerySingleOrDefaultAsync<DateTime?>("select max(finished_at_utc) from ged.backup_set where integrity_status='VALID' and (@tenant is null or tenant_id=@tenant)", new { tenant=tenantId }); var failed = await c.QuerySingleAsync<int>("select count(*) from ged.backup_set where status='FAILED' and (@tenant is null or tenant_id=@tenant)", new { tenant=tenantId }); var dead = await c.QuerySingleAsync<int>("select count(*) from ged.operations_dead_letter where resolved_at_utc is null"); var active = await c.QuerySingleAsync<int>("select count(*) from ged.portability_export where status in ('REQUESTED','RUNNING','AVAILABLE') and (@tenant is null or tenant_id=@tenant)", new { tenant=tenantId }); var alerts = new List<string>(); if (!backupOptions.Value.Enabled) alerts.Add("Backup desabilitado por configuração."); if (last is null) alerts.Add("Nenhum backup concluído encontrado."); var rpo = valid.HasValue ? (int)(DateTime.UtcNow - valid.Value).TotalMinutes : null; return new(DateTime.UtcNow, alerts.Count == 0 ? "SAUDAVEL" : "NAO_CONFIGURADO", backupOptions.Value.Enabled, portabilityOptions.Value.Enabled, last, valid, null, null, valid.HasValue ? 100 : 0, failed, 0, backupOptions.Value.DefaultRetentionDays, null, rpo, null, null, 0, 0, active, 0, 0, dead, alerts); }
    public async Task<PortabilityExportDto> RequestAsync(Guid? tenantId, string scope, string requestedBy, string key, string correlationId, CancellationToken ct) { await using var c = await db.OpenAsync(ct); var id=Guid.NewGuid(); await c.ExecuteAsync("insert into ged.portability_export(id,tenant_id,scope,status,requested_by,idempotency_key,correlation_id,expires_at_utc) values(@id,@tenant,@scope,'REQUESTED',@requestedBy,@key,@correlationId,now()+(@days||' days')::interval) on conflict(tenant_id,idempotency_key) do nothing", new { id, tenant=tenantId, scope, requestedBy, key, correlationId, days=portabilityOptions.Value.PackageExpirationDays }); return new(id, tenantId, scope, "REQUESTED", DateTime.UtcNow, null, DateTime.UtcNow.AddDays(portabilityOptions.Value.PackageExpirationDays), 0, null, correlationId); }
    public async Task<PortabilityExportDto?> GetAsync(Guid id, Guid? tenantId, CancellationToken ct) { await using var c = await db.OpenAsync(ct); return await c.QuerySingleOrDefaultAsync<PortabilityExportDto>("select id, tenant_id TenantId, scope, status, requested_at_utc RequestedAtUtc, finished_at_utc FinishedAtUtc, expires_at_utc ExpiresAtUtc, size_bytes SizeBytes, package_sha256 PackageSha256, correlation_id CorrelationId from ged.portability_export where id=@id and (@tenant is null or tenant_id=@tenant)", new { id, tenant=tenantId }); }
    public async Task<bool> CancelAsync(Guid id, Guid? tenantId, string requestedBy, CancellationToken ct) { await using var c = await db.OpenAsync(ct); return await c.ExecuteAsync("update ged.portability_export set status='CANCELLED', updated_at_utc=now() where id=@id and (@tenant is null or tenant_id=@tenant) and status in ('REQUESTED','RUNNING')", new { id, tenant=tenantId }) > 0; }
    public async Task<IReadOnlyList<RecoveryPlanDto>> ListPlansAsync(Guid? tenantId, CancellationToken ct) { await using var c = await db.OpenAsync(ct); var rows=await c.QueryAsync<RecoveryPlanDto>("select id, tenant_id TenantId, name, current_version CurrentVersion, status, rpo_minutes RpoMinutes, rto_minutes RtoMinutes, last_test_at_utc LastTestAtUtc, last_test_result LastTestResult, next_review_at_utc NextReviewAtUtc from ged.recovery_plan where (@tenant is null or tenant_id=@tenant or tenant_id is null)", new{tenant=tenantId}); return rows.AsList(); }
    public async Task<IReadOnlyList<TenantOffboardingDto>> ListOffboardingsAsync(Guid? tenantId, CancellationToken ct) { await using var c=await db.OpenAsync(ct); var rows=await c.QueryAsync<TenantOffboardingDto>("select id, tenant_id TenantId, status, started_at_utc StartedAtUtc, effective_at_utc EffectiveAtUtc, access_until_utc AccessUntilUtc, legal_hold LegalHold, justification from ged.tenant_offboarding where (@tenant is null or tenant_id=@tenant)", new{tenant=tenantId}); return rows.AsList(); }
    public async Task<TenantOffboardingDto> StartAsync(Guid tenantId, DateTime effectiveAtUtc, string justification, string requestedBy, CancellationToken ct) { await using var c=await db.OpenAsync(ct); var id=Guid.NewGuid(); var access=effectiveAtUtc.AddDays(90); await c.ExecuteAsync("insert into ged.tenant_offboarding(id,tenant_id,status,effective_at_utc,access_until_utc,justification,requested_by) values(@id,@tenantId,'DRAFT',@effectiveAtUtc,@access,@justification,@requestedBy)", new{id,tenantId,effectiveAtUtc,access,justification,requestedBy}); return new(id,tenantId,"DRAFT",DateTime.UtcNow,effectiveAtUtc,access,false,justification); }

    Task<IReadOnlyList<BackupPolicyDto>> IBackupPolicyService.ListAsync(Guid? tenantId, CancellationToken ct) => ListPoliciesAsync(tenantId, ct);
    Task<IReadOnlyList<RecoveryPlanDto>> IRecoveryPlanService.ListAsync(Guid? tenantId, CancellationToken ct) => ListPlansAsync(tenantId, ct);
    Task<IReadOnlyList<TenantOffboardingDto>> ITenantOffboardingService.ListAsync(Guid? tenantId, CancellationToken ct) => ListOffboardingsAsync(tenantId, ct);
    public async Task<RestoreValidationResult> ApproveDeletionAsync(Guid offboardingId, string justification, CancellationToken ct) { await using var c=await db.OpenAsync(ct); var blocked=await c.QuerySingleAsync<bool>("select coalesce((select legal_hold from ged.tenant_offboarding where id=@offboardingId), true)", new{offboardingId}); if(blocked) return new(false,"Legal hold ou registro inexistente bloqueia avanço."); return new(false,"Exclusão física automática está fora do escopo desta evolução."); }
    public async Task<bool> IsDeletionBlockedAsync(Guid tenantId, CancellationToken ct) { await using var c=await db.OpenAsync(ct); return await c.QuerySingleAsync<bool>("select exists(select 1 from ged.data_retention_hold where tenant_id=@tenantId and status='ACTIVE')", new{tenantId}); }
}

public sealed class BackupOrchestrator(IDbConnectionFactory db) : IBackupOrchestrator { public async Task<OperationJobDto> EnqueueBackupAsync(Guid? tenantId, Guid? policyId, string requestedBy, string correlationId, CancellationToken ct) { await using var c=await db.OpenAsync(ct); var id=Guid.NewGuid(); await c.ExecuteAsync("insert into ged.backup_job(id,tenant_id,policy_id,job_type,status,requested_by,correlation_id) values(@id,@tenantId,@policyId,'BACKUP','PENDING',@requestedBy,@correlationId)", new{id,tenantId,policyId,requestedBy,correlationId}); return new(id,tenantId,"BACKUP","PENDING",0,"Aguardando worker",DateTime.UtcNow,null,correlationId); } public Task<int> ProcessDueJobsAsync(string workerId, CancellationToken ct)=>Task.FromResult(0); }
public sealed class BackupIntegrityService(IDbConnectionFactory db) : IBackupIntegrityService { public async Task<BackupVerificationResult> VerifyAsync(Guid backupSetId, string workerId, CancellationToken ct){ await using var c=await db.OpenAsync(ct); var set=await c.QuerySingleOrDefaultAsync<(string? Path,long Size)>("select location_masked, size_bytes from ged.backup_set where id=@backupSetId", new{backupSetId}); var findings=new List<string>(); var status="NOT_VERIFIABLE"; if(string.IsNullOrWhiteSpace(set.Path)) findings.Add("Localização não disponível para verificação pelo nó atual."); await c.ExecuteAsync("insert into ged.backup_verification(backup_set_id,status,findings_json,worker_id) values(@backupSetId,@status,@json::jsonb,@workerId)", new{backupSetId,status,json=JsonSerializer.Serialize(findings),workerId}); return new(backupSetId,status,findings,DateTime.UtcNow); } }
public sealed class RestoreValidationService(IConfiguration cfg) : IRestoreValidationService { public Task<RestoreValidationResult> ValidateTargetAsync(string host,string database,bool confirmed,string justification,CancellationToken ct){ var prod=cfg.GetConnectionString("DefaultConnection")??string.Empty; var allow=cfg.GetSection("RestoreTest:AllowedDatabases").Get<string[]>()??[]; if(!confirmed || string.IsNullOrWhiteSpace(justification)) return Task.FromResult(new RestoreValidationResult(false,"Confirmação e justificativa são obrigatórias.")); if(prod.Contains(database, StringComparison.OrdinalIgnoreCase)) return Task.FromResult(new RestoreValidationResult(false,"Destino aparenta ser produção e foi bloqueado.")); return Task.FromResult(allow.Contains(database,StringComparer.OrdinalIgnoreCase)?new RestoreValidationResult(true,"Destino autorizado para teste isolado."):new RestoreValidationResult(false,"Destino fora da allowlist.")); } }
public sealed class PortabilityManifestService : IPortabilityManifestService { public Task<PortabilityManifest> BuildAsync(Guid exportId, CancellationToken ct)=>Task.FromResult(new PortabilityManifest("1.0",exportId,null,"TENANT",DateTime.UtcNow,"PENDING",Guid.NewGuid().ToString("N"),[])); }
public sealed class PortabilityPackageVerifier : IPortabilityPackageVerifier { public async Task<PortabilityVerificationResult> VerifyAsync(string packagePath, CancellationToken ct){ if(!Directory.Exists(packagePath)) return new(false,["Pacote não encontrado."]); var manifest=Path.Combine(packagePath,"manifest.json"); if(!File.Exists(manifest)) return new(false,["manifest.json ausente."]); var findings=new List<string>(); var json=await File.ReadAllTextAsync(manifest,ct); if(json.Contains("password",StringComparison.OrdinalIgnoreCase)||json.Contains("token",StringComparison.OrdinalIgnoreCase)) findings.Add("Manifesto contém termo sensível bloqueado."); return new(findings.Count==0, findings); } }
