using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Release.Uat;

namespace InovaGed.Infrastructure.Release.Uat;
public sealed class UatService(IDbConnectionFactory db) : IUatTestPlanService,IUatExecutionService,IReleaseEvidenceService
{
 public async Task<IReadOnlyList<UatTestPlanItem>> ListPlansAsync(Guid? tenantId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var rows=await c.QueryAsync<PlanRow>(new CommandDefinition("select p.id,p.plan_code PlanCode,p.title,p.status,p.release_version ReleaseVersion,p.created_at CreatedAt,count(tc.id)::int CaseCount from ged.uat_test_plan p left join ged.uat_test_case tc on tc.plan_id=p.id and tc.reg_status='A' where p.reg_status='A' and (p.tenant_id is not distinct from @tenantId or p.tenant_id is null) group by p.id order by p.created_at desc",new{tenantId},cancellationToken:ct));return rows.Select(x=>x.Model()).ToList();}
 public async Task<UatTestPlanDetails> GetDefaultPlanAsync(Guid? tenantId,CancellationToken ct){var plans=await ListPlansAsync(tenantId,ct);var plan=plans.FirstOrDefault()??throw new InvalidOperationException("Nenhum plano de homologação foi configurado para o tenant.");await using var c=await db.OpenAsync(ct);var rows=await c.QueryAsync<CaseRow>(new CommandDefinition("select id,module_code ModuleCode,case_code CaseCode,title,description,preconditions,steps,expected_result ExpectedResult,priority,status,display_order DisplayOrder from ged.uat_test_case where plan_id=@id and reg_status='A' order by display_order,case_code",new{plan.Id},cancellationToken:ct));return new(plan,rows.Select(x=>x.Model()).ToList());}
 public async Task<Guid> CreatePlanAsync(UatTestPlanCreateCommand x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.PlanCode)||string.IsNullOrWhiteSpace(x.Title))throw new ArgumentException("Código e título são obrigatórios.");await using var c=await db.OpenAsync(ct);return await c.ExecuteScalarAsync<Guid>(new CommandDefinition("insert into ged.uat_test_plan(tenant_id,plan_code,title,description,release_version,created_by) values(@TenantId,@PlanCode,@Title,@Description,@ReleaseVersion,@CreatedBy) returning id",x,cancellationToken:ct));}
 public async Task<Guid> StartRunAsync(Guid? tenantId,Guid planId,Guid userId,CancellationToken ct){await using var c=await db.OpenAsync(ct);await using var tx=await c.BeginTransactionAsync(ct);var id=await c.ExecuteScalarAsync<Guid>(new CommandDefinition("insert into ged.uat_test_run(tenant_id,plan_id,started_by,total_cases) select @tenantId,@planId,@userId,count(*) from ged.uat_test_case where plan_id=@planId and reg_status='A' and exists(select 1 from ged.uat_test_plan p where p.id=@planId and (p.tenant_id is not distinct from @tenantId or p.tenant_id is null)) returning id",new{tenantId,planId,userId},tx,cancellationToken:ct));await c.ExecuteAsync(new CommandDefinition("insert into ged.uat_test_result(tenant_id,run_id,test_case_id,result,executed_by) select @tenantId,@id,id,'PENDING',@userId from ged.uat_test_case where plan_id=@planId and reg_status='A'",new{tenantId,id,planId,userId},tx,cancellationToken:ct));await tx.CommitAsync(ct);return id;}
 public async Task RecordResultAsync(UatTestResultCommand x,CancellationToken ct){var valid=new[]{"PENDING","PASSED","FAILED","BLOCKED","SKIPPED"};if(!valid.Contains(x.Result,StringComparer.OrdinalIgnoreCase))throw new ArgumentException("Resultado inválido.");if((x.Result is "FAILED" or "BLOCKED") && (string.IsNullOrWhiteSpace(x.ActualResult)||(string.IsNullOrWhiteSpace(x.EvidenceNotes)&&x.IncidentId is null)))throw new ArgumentException("Falhas e bloqueios exigem observação e evidência ou incidente.");await using var c=await db.OpenAsync(ct);await c.ExecuteAsync(new CommandDefinition("""
update ged.uat_test_result set reg_status='I' where run_id=@RunId and test_case_id=@TestCaseId and reg_status='A';
insert into ged.uat_test_result(tenant_id,run_id,test_case_id,result,actual_result,evidence_notes,incident_id,executed_by) select @TenantId,@RunId,@TestCaseId,upper(@Result),@ActualResult,@EvidenceNotes,@IncidentId,@ExecutedBy where exists(select 1 from ged.uat_test_run r where r.id=@RunId and r.tenant_id is not distinct from @TenantId) and exists(select 1 from ged.uat_test_case tc where tc.id=@TestCaseId and tc.plan_id=(select plan_id from ged.uat_test_run where id=@RunId));
update ged.uat_test_run r set passed_cases=q.passed,failed_cases=q.failed,blocked_cases=q.blocked,finished_at=case when q.pending=0 then now() else null end,status=case when q.pending=0 then 'COMPLETED' else 'RUNNING' end from (select count(*) filter(where result='PASSED')::int passed,count(*) filter(where result='FAILED')::int failed,count(*) filter(where result='BLOCKED')::int blocked,count(*) filter(where result='PENDING')::int pending from ged.uat_test_result rr join ged.uat_test_run r2 on r2.id=rr.run_id where rr.run_id=@RunId and rr.reg_status='A' group by r2.total_cases)q where r.id=@RunId
""",x,cancellationToken:ct));}
 public async Task<UatRunDetails> GetRunAsync(Guid runId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var run=await c.QuerySingleOrDefaultAsync<RunRow>(new CommandDefinition("select r.id,r.plan_id PlanId,p.plan_code PlanCode,p.title PlanTitle,p.release_version ReleaseVersion,r.started_by StartedBy,r.started_at StartedAt,r.finished_at FinishedAt,r.status,r.total_cases TotalCases,r.passed_cases PassedCases,r.failed_cases FailedCases,r.blocked_cases BlockedCases from ged.uat_test_run r join ged.uat_test_plan p on p.id=r.plan_id where r.id=@runId and r.reg_status='A'",new{runId},cancellationToken:ct))??throw new KeyNotFoundException("Execução não encontrada.");var results=await c.QueryAsync<ResultRow>(new CommandDefinition("select rr.id,rr.test_case_id TestCaseId,tc.case_code CaseCode,tc.module_code ModuleCode,tc.title,tc.priority,rr.result,rr.actual_result ActualResult,rr.evidence_notes EvidenceNotes,rr.incident_id IncidentId,si.status IncidentStatus,rr.executed_at ExecutedAt from ged.uat_test_result rr join ged.uat_test_case tc on tc.id=rr.test_case_id left join ged.system_incident si on si.id=rr.incident_id where rr.run_id=@runId and rr.reg_status='A' order by rr.executed_at desc",new{runId},cancellationToken:ct));return run.Model(results.Select(x=>x.Model()).ToList());}
 public async Task<UatSummary> GetSummaryAsync(Guid? tenantId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var x=await c.QuerySingleAsync<SummaryRow>(new CommandDefinition("select coalesce(r.total_cases,0) TotalCases,coalesce(r.passed_cases,0) PassedCases,coalesce(r.failed_cases,0) FailedCases,coalesce(r.blocked_cases,0) BlockedCases,greatest(coalesce(r.total_cases,0)-coalesce(r.passed_cases,0)-coalesce(r.failed_cases,0)-coalesce(r.blocked_cases,0),0) PendingCases,(select count(distinct incident_id)::int from ged.uat_test_result where incident_id is not null) IncidentCount,(select count(*)::int from ged.release_evidence where reg_status='A') EvidenceCount,coalesce(r.status,'NOT_STARTED') Status,r.id LatestRunId,p.title CurrentPlan from ged.uat_test_plan p left join lateral(select * from ged.uat_test_run x where x.plan_id=p.id and x.reg_status='A' order by x.started_at desc limit 1)r on true where p.reg_status='A' and (p.tenant_id is not distinct from @tenantId or p.tenant_id is null) order by p.created_at desc limit 1",new{tenantId},cancellationToken:ct));return x.Model();}
 public async Task<Guid> AddEvidenceAsync(ReleaseEvidenceCommand x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Title))throw new ArgumentException("Título obrigatório.");await using var c=await db.OpenAsync(ct);return await c.ExecuteScalarAsync<Guid>(new CommandDefinition("insert into ged.release_evidence(tenant_id,source_type,source_id,title,description,evidence_type,file_path,external_url,payload_json,captured_by) values(@TenantId,@SourceType,@SourceId,@Title,@Description,@EvidenceType,@FilePath,@ExternalUrl,cast(@PayloadJson as jsonb),@CapturedBy) returning id",x,cancellationToken:ct));}
 public async Task<IReadOnlyList<ReleaseEvidenceItem>> ListEvidenceAsync(string type,Guid id,CancellationToken ct){await using var c=await db.OpenAsync(ct);var x=await c.QueryAsync<EvidenceRow>(new CommandDefinition("select id,source_type SourceType,source_id SourceId,title,description,evidence_type EvidenceType,file_path FilePath,external_url ExternalUrl,payload_json::text PayloadJson,captured_at CapturedAt from ged.release_evidence where source_type=@type and source_id=@id and reg_status='A' order by captured_at desc",new{type,id},cancellationToken:ct));return x.Select(a=>a.Model()).ToList();}
 private sealed class PlanRow{public Guid Id{get;set;}public string PlanCode{get;set;}="";public string Title{get;set;}="";public string Status{get;set;}="";public string? ReleaseVersion{get;set;}public DateTimeOffset CreatedAt{get;set;}public int CaseCount{get;set;}public UatTestPlanItem Model()=>new(Id,PlanCode,Title,Status,ReleaseVersion,CreatedAt,CaseCount);}
 private sealed class CaseRow{public Guid Id{get;set;}public string ModuleCode{get;set;}="";public string CaseCode{get;set;}="";public string Title{get;set;}="";public string? Description{get;set;}public string? Preconditions{get;set;}public string Steps{get;set;}="";public string ExpectedResult{get;set;}="";public string Priority{get;set;}="";public string Status{get;set;}="";public int DisplayOrder{get;set;}public UatTestCaseItem Model()=>new(Id,ModuleCode,CaseCode,Title,Description,Preconditions,Steps,ExpectedResult,Priority,Status,DisplayOrder);}
 private sealed class RunRow{public Guid Id{get;set;}public Guid PlanId{get;set;}public string PlanCode{get;set;}="";public string PlanTitle{get;set;}="";public string? ReleaseVersion{get;set;}public Guid? StartedBy{get;set;}public DateTimeOffset StartedAt{get;set;}public DateTimeOffset? FinishedAt{get;set;}public string Status{get;set;}="";public int TotalCases{get;set;}public int PassedCases{get;set;}public int FailedCases{get;set;}public int BlockedCases{get;set;}public UatRunDetails Model(IReadOnlyList<UatResultItem>x)=>new(Id,PlanId,PlanCode,PlanTitle,ReleaseVersion,StartedBy,StartedAt,FinishedAt,Status,TotalCases,PassedCases,FailedCases,BlockedCases,x);}
 private sealed class ResultRow{public Guid Id{get;set;}public Guid TestCaseId{get;set;}public string CaseCode{get;set;}="";public string ModuleCode{get;set;}="";public string Title{get;set;}="";public string Priority{get;set;}="";public string Result{get;set;}="";public string? ActualResult{get;set;}public string? EvidenceNotes{get;set;}public Guid? IncidentId{get;set;}public string? IncidentStatus{get;set;}public DateTimeOffset ExecutedAt{get;set;}public UatResultItem Model()=>new(Id,TestCaseId,CaseCode,ModuleCode,Title,Priority,Result,ActualResult,EvidenceNotes,IncidentId,IncidentStatus,ExecutedAt);}
 private sealed class SummaryRow{public int TotalCases{get;set;}public int PassedCases{get;set;}public int FailedCases{get;set;}public int BlockedCases{get;set;}public int PendingCases{get;set;}public int IncidentCount{get;set;}public int EvidenceCount{get;set;}public string Status{get;set;}="";public Guid? LatestRunId{get;set;}public string? CurrentPlan{get;set;}public UatSummary Model()=>new(TotalCases,PassedCases,FailedCases,BlockedCases,PendingCases,IncidentCount,EvidenceCount,Status,LatestRunId,CurrentPlan,TotalCases==0?0:Math.Round(PassedCases*100m/TotalCases,1));}
 private sealed class EvidenceRow{public Guid Id{get;set;}public string SourceType{get;set;}="";public Guid? SourceId{get;set;}public string Title{get;set;}="";public string? Description{get;set;}public string EvidenceType{get;set;}="";public string? FilePath{get;set;}public string? ExternalUrl{get;set;}public string? PayloadJson{get;set;}public DateTimeOffset CapturedAt{get;set;}public ReleaseEvidenceItem Model()=>new(Id,SourceType,SourceId,Title,Description,EvidenceType,FilePath,ExternalUrl,PayloadJson,CapturedAt);}
}
