using System.Text;
using InovaGed.Application.Common.Database;
using InovaGed.Application.PhysicalArchive.Reconciliation;
using InovaGed.Web.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InovaGed.Web.Controllers;

[Authorize]
[Route("ArchiveReconciliation")]
public sealed class ArchiveReconciliationController(IDbConnectionFactory db,IArchiveReconciliationService service,IArchiveReconciliationEngine engine,IArchiveReconciliationFixService fixes):GedControllerBase(db)
{
 [HttpGet("")] public async Task<IActionResult> Index(CancellationToken ct)=>Can("archive.reconciliation.view")?View(await service.GetDashboardAsync(TenantId,ct)):Forbid();
 [HttpGet("Runs")] public async Task<IActionResult> Runs([FromQuery]ArchiveReconciliationRunFilter filter,CancellationToken ct)=>Can("archive.reconciliation.view")?View(await service.ListRunsAsync(TenantId,filter,ct)):Forbid();
 [HttpPost("RunFullDiagnosis"),ValidateAntiForgeryToken] public async Task<IActionResult> RunFullDiagnosis(CancellationToken ct){if(!Can("archive.reconciliation.run"))return Forbid();if(UserId is not Guid u)return Unauthorized();var x=await engine.RunFullDiagnosisAsync(TenantId,u,ct);TempData["Success"]=$"Diagnóstico concluído: {x.TotalIssues} inconsistência(s).";return RedirectToAction(nameof(Run),new{id=x.RunId});}
 [HttpPost("RunInventoryDiagnosis"),ValidateAntiForgeryToken] public async Task<IActionResult> RunInventoryDiagnosis(Guid inventorySessionId,CancellationToken ct){if(!Can("archive.reconciliation.run"))return Forbid();if(UserId is not Guid u)return Unauthorized();var x=await engine.RunInventoryReconciliationAsync(TenantId,inventorySessionId,u,ct);return RedirectToAction(nameof(Run),new{id=x.RunId});}
 [HttpGet("Run/{id:guid}")] public async Task<IActionResult> Run(Guid id,CancellationToken ct){if(!Can("archive.reconciliation.view"))return Forbid();var x=await service.GetRunAsync(TenantId,id,ct);return x is null?NotFound():View("RunDetails",x);}
 [HttpGet("Issues")] public async Task<IActionResult> Issues([FromQuery]ArchiveReconciliationIssueFilter filter,CancellationToken ct){if(!Can("archive.reconciliation.view"))return Forbid();ViewBag.Filter=filter;return View(await service.ListIssuesAsync(TenantId,filter,ct));}
 [HttpGet("Issue/{id:guid}")] public async Task<IActionResult> Issue(Guid id,CancellationToken ct){if(!Can("archive.reconciliation.view"))return Forbid();var x=await service.GetIssueAsync(TenantId,id,ct);return x is null?NotFound():View("IssueDetails",x);}
 [HttpPost("Issue/{id:guid}/ApplyFix"),ValidateAntiForgeryToken] public async Task<IActionResult> ApplyFix(Guid id,string? notes,CancellationToken ct){if(!Can("archive.reconciliation.fix"))return Forbid();if(UserId is not Guid u)return Unauthorized();try{await fixes.ApplyFixAsync(TenantId,id,u,notes,ct);TempData["Success"]="Correção aplicada e registrada na cadeia de custódia.";}catch(InvalidOperationException ex){TempData["Error"]=ex.Message;}return RedirectToAction(nameof(Issue),new{id});}
 [HttpPost("Issue/{id:guid}/Ignore"),ValidateAntiForgeryToken] public async Task<IActionResult> Ignore(Guid id,string reason,CancellationToken ct){if(!Can("archive.reconciliation.ignore"))return Forbid();if(UserId is not Guid u)return Unauthorized();await fixes.IgnoreIssueAsync(TenantId,id,u,reason,ct);return RedirectToAction(nameof(Issue),new{id});}
 [HttpPost("Issue/{id:guid}/Reject"),ValidateAntiForgeryToken] public async Task<IActionResult> Reject(Guid id,string reason,CancellationToken ct){if(!Can("archive.reconciliation.fix"))return Forbid();if(UserId is not Guid u)return Unauthorized();await fixes.RejectSuggestionAsync(TenantId,id,u,reason,ct);return RedirectToAction(nameof(Issue),new{id});}
 [HttpGet("Export")] public async Task<IActionResult> Export(CancellationToken ct,string report="open"){if(!Can("archive.reconciliation.export"))return Forbid();var f=report switch{"critical"=>new ArchiveReconciliationIssueFilter(Severity:ReconciliationSeverity.Critical),"fixed"=>new ArchiveReconciliationIssueFilter(Status:ArchiveReconciliationIssueStatus.Fixed),"location"=>new ArchiveReconciliationIssueFilter(IssueType:ArchiveReconciliationIssueType.LocationMismatch),"without-label"=>new ArchiveReconciliationIssueFilter(IssueType:ArchiveReconciliationIssueType.BoxWithoutLabel),"orphan-label"=>new ArchiveReconciliationIssueFilter(IssueType:ArchiveReconciliationIssueType.LabelWithoutSubject),"documents-without-box"=>new ArchiveReconciliationIssueFilter(IssueType:ArchiveReconciliationIssueType.DocumentWithoutBox),"boxes-without-documents"=>new ArchiveReconciliationIssueFilter(IssueType:ArchiveReconciliationIssueType.BoxWithoutDocuments),"all"=>new(),_=>new ArchiveReconciliationIssueFilter(Status:ArchiveReconciliationIssueStatus.Open)};var rows=await service.ListIssuesAsync(TenantId,f,ct);var lines=new[]{"Data;Severidade;Status;Tipo;Objeto;Controle;Título;Descrição;Sugestão"}.Concat(rows.Select(x=>$"{x.CreatedAt:O};{Csv(x.Severity)};{Csv(x.Status)};{Csv(x.IssueType)};{Csv(x.SubjectType)};{Csv(x.ControlNumber)};{Csv(x.Title)};{Csv(x.Description)};{Csv(x.Suggestion)}"));return File(Encoding.UTF8.GetBytes('\uFEFF'+string.Join('\n',lines)),"text/csv; charset=utf-8",$"saneamento-acervo-{report}.csv");}
 private bool Can(string permission)=>User.IsFullAdmin()||((permission is "archive.reconciliation.view" or "archive.reconciliation.run" or "archive.reconciliation.export")&&User.IsInNormalizedRole("ArquivistaOphir"))||User.Claims.Any(c=>(c.Type is "permission" or "permissions")&&c.Value.Split(' ',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Contains(permission,StringComparer.OrdinalIgnoreCase));
 private static string Csv(string? value)=>$"\"{(value??"").Replace("\"","\"\"")}\"";
}
