using System.Text;
using InovaGed.Application.Common.Database;
using InovaGed.Application.PhysicalArchive.WorkOrders;
using InovaGed.Web.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace InovaGed.Web.Controllers;
[Authorize,Route("ArchiveWorkOrders")]
public sealed class ArchiveWorkOrdersController(IDbConnectionFactory db,IArchiveWorkOrderService orders,IArchiveWorkOrderTaskService tasks,IArchiveWorkOrderSlaService sla):GedControllerBase(db){
[HttpGet("")]public async Task<IActionResult>Index([FromQuery]ArchiveWorkOrderFilter f,CancellationToken ct){if(!Can("archive.workorders.view"))return Forbid();ViewBag.Sla=await sla.GetSummaryAsync(TenantId,ct);return View(await orders.ListAsync(TenantId,f,ct));}
[HttpGet("Create")]public IActionResult Create()=>Can("archive.workorders.create")?View(new ArchiveWorkOrderCreateInput()):Forbid();
[HttpPost("Create"),ValidateAntiForgeryToken]public async Task<IActionResult>Create(ArchiveWorkOrderCreateInput x,CancellationToken ct){if(!Can("archive.workorders.create")||UserId is not Guid u)return Forbid();if(!ModelState.IsValid)return View(x);var id=await orders.CreateAsync(new(TenantId,u,x.Title,x.OrderType,x.Priority,x.Description,x.SubjectType,x.SubjectId,ControlNumber:x.ControlNumber,LocationExpected:x.LocationExpected,LocationFound:x.LocationFound,LocationTarget:x.LocationTarget,AssignedTo:x.AssignedTo,DueAt:x.DueAt),ct);return RedirectToAction(nameof(Details),new{id});}
[HttpGet("{id:guid}")]public async Task<IActionResult>Details(Guid id,CancellationToken ct){if(!Can("archive.workorders.view"))return Forbid();var x=await orders.GetAsync(TenantId,id,ct);return x is null?NotFound():View(x);}
[HttpPost("{id:guid}/Assign"),ValidateAntiForgeryToken]public Task<IActionResult>Assign(Guid id,Guid assignedTo,DateTimeOffset?dueAt,CancellationToken ct)=>Act("archive.workorders.assign",id,u=>orders.AssignAsync(TenantId,id,assignedTo,u,dueAt,ct));
[HttpPost("{id:guid}/Start"),ValidateAntiForgeryToken]public Task<IActionResult>Start(Guid id,CancellationToken ct)=>Act("archive.workorders.execute",id,u=>orders.StartAsync(TenantId,id,u,ct));
[HttpPost("{id:guid}/Complete"),ValidateAntiForgeryToken]public Task<IActionResult>Complete(Guid id,string notes,CancellationToken ct)=>Act("archive.workorders.execute",id,u=>orders.CompleteAsync(TenantId,id,u,notes,ct));
[HttpPost("{id:guid}/Close"),ValidateAntiForgeryToken]public Task<IActionResult>Close(Guid id,string notes,CancellationToken ct)=>Act("archive.workorders.close",id,u=>orders.CloseAsync(TenantId,id,u,notes,ct));
[HttpPost("{id:guid}/Cancel"),ValidateAntiForgeryToken]public Task<IActionResult>Cancel(Guid id,string reason,CancellationToken ct)=>Act("archive.workorders.cancel",id,u=>orders.CancelAsync(TenantId,id,u,reason,ct));
[HttpPost("FromAlert/{alertId:guid}"),ValidateAntiForgeryToken]public async Task<IActionResult>FromAlert(Guid alertId,CancellationToken ct){if(!Can("archive.workorders.create")||UserId is not Guid u)return Forbid();return RedirectToAction(nameof(Details),new{id=await orders.CreateFromAlertAsync(TenantId,alertId,u,ct)});}
[HttpPost("FromReconciliationIssue/{issueId:guid}"),ValidateAntiForgeryToken]public async Task<IActionResult>FromReconciliationIssue(Guid issueId,CancellationToken ct){if(!Can("archive.workorders.create")||UserId is not Guid u)return Forbid();return RedirectToAction(nameof(Details),new{id=await orders.CreateFromReconciliationIssueAsync(TenantId,issueId,u,ct)});}
[HttpPost("Task/{taskId:guid}/Complete"),ValidateAntiForgeryToken]public async Task<IActionResult>CompleteTask(Guid taskId,Guid orderId,string notes,bool scanConfirmed,Guid?labelEvidenceId,string?evidenceDescription,CancellationToken ct){if(!Can("archive.workorders.execute")||UserId is not Guid u)return Forbid();try{await tasks.CompleteTaskAsync(TenantId,taskId,u,new(notes,scanConfirmed,labelEvidenceId,evidenceDescription),ct);}catch(InvalidOperationException e){TempData["Error"]=e.Message;}return RedirectToAction(nameof(Details),new{id=orderId});}
[HttpPost("Task/{taskId:guid}/Reopen"),ValidateAntiForgeryToken]public async Task<IActionResult>ReopenTask(Guid taskId,Guid orderId,string reason,CancellationToken ct){if(!Can("archive.workorders.execute")||UserId is not Guid u)return Forbid();await tasks.ReopenTaskAsync(TenantId,taskId,u,reason,ct);return RedirectToAction(nameof(Details),new{id=orderId});}
[HttpGet("Sla")]public async Task<IActionResult>Sla(CancellationToken ct){if(!Can("archive.workorders.view"))return Forbid();ViewBag.Summary=await sla.GetSummaryAsync(TenantId,ct);return View(await sla.ListOverdueAsync(TenantId,ct));}
[HttpGet("Export")]public async Task<IActionResult>Export([FromQuery]ArchiveWorkOrderFilter f,CancellationToken ct){if(!Can("archive.workorders.export"))return Forbid();var r=await orders.ListAsync(TenantId,f,ct);var csv="Número;Tipo;Título;Prioridade;Status;Vencimento;Origem;Localização\n"+string.Join('\n',r.Select(x=>$"{C(x.OrderNumber)};{C(x.OrderType)};{C(x.Title)};{C(x.Priority)};{C(x.Status)};{x.DueAt:O};{C(x.SourceType)};{C(x.LocationTarget)}"));return File(Encoding.UTF8.GetBytes('\uFEFF'+csv),"text/csv; charset=utf-8","ordens-acervo.csv");}
async Task<IActionResult>Act(string p,Guid id,Func<Guid,Task>a){if(!Can(p)||UserId is not Guid u)return Forbid();try{await a(u);}catch(Exception e)when(e is InvalidOperationException or ArgumentException){TempData["Error"]=e.Message;}return RedirectToAction(nameof(Details),new{id});}bool Can(string p)=>User.IsFullAdmin()||User.IsInNormalizedRole("ArquivistaOphir")||User.Claims.Any(c=>(c.Type is "permission" or "permissions")&&c.Value.Split(' ').Contains(p,StringComparer.OrdinalIgnoreCase));static string C(string?x)=>$"\"{(x??"").Replace("\"","\"\"")}\"";}
public sealed class ArchiveWorkOrderCreateInput{[System.ComponentModel.DataAnnotations.Required]public string Title{get;set;}="";public string OrderType{get;set;}=ArchiveWorkOrderType.CheckLocation;public string Priority{get;set;}=ArchiveWorkOrderPriority.Medium;public string?Description{get;set;}public string?SubjectType{get;set;}public Guid?SubjectId{get;set;}public string?ControlNumber{get;set;}public string?LocationExpected{get;set;}public string?LocationFound{get;set;}public string?LocationTarget{get;set;}public Guid?AssignedTo{get;set;}public DateTimeOffset?DueAt{get;set;}}
