using System.Text;
using InovaGed.Application.Common.Database;
using InovaGed.Application.PhysicalArchive.Productivity;
using InovaGed.Web.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace InovaGed.Web.Controllers;
[Authorize,Route("ArchiveProductivity")]
public sealed class ArchiveProductivityController(IDbConnectionFactory db,IArchiveServiceCatalogService catalog,IArchiveProductivityService productivity,IArchiveBillingService billing):GedControllerBase(db){
[HttpGet("")]public IActionResult Index()=>Can("archive.productivity.view")?View():Forbid();
[HttpGet("Dashboard")]public async Task<IActionResult>Dashboard(DateOnly?competence,CancellationToken ct){if(!Can("archive.productivity.view"))return Forbid();var m=competence??new DateOnly(DateTime.Today.Year,DateTime.Today.Month,1);return View(await billing.PreviewAsync(TenantId,m,ct));}
[HttpGet("Catalog")]public async Task<IActionResult>Catalog(CancellationToken ct)=>Can("archive.productivity.view")?View(await catalog.ListAsync(TenantId,ct)):Forbid();
[HttpGet("Catalog/Create")]public IActionResult CatalogCreate()=>Can("archive.productivity.catalog.manage")?View("CatalogForm",new CatalogInput()):Forbid();
[HttpPost("Catalog/Create"),ValidateAntiForgeryToken]public async Task<IActionResult>CatalogCreate(CatalogInput x,CancellationToken ct){if(!Can("archive.productivity.catalog.manage"))return Forbid();if(!ModelState.IsValid)return View("CatalogForm",x);await catalog.CreateAsync(TenantId,x.Command,ct);return RedirectToAction(nameof(Catalog));}
[HttpGet("Catalog/Edit/{id:guid}")]public async Task<IActionResult>CatalogEdit(Guid id,CancellationToken ct){if(!Can("archive.productivity.catalog.manage"))return Forbid();var x=(await catalog.ListAsync(TenantId,ct)).FirstOrDefault(x=>x.Id==id);return x is null?NotFound():View("CatalogForm",new CatalogInput(x));}
[HttpPost("Catalog/Edit/{id:guid}"),ValidateAntiForgeryToken]public async Task<IActionResult>CatalogEdit(Guid id,CatalogInput x,CancellationToken ct){if(!Can("archive.productivity.catalog.manage"))return Forbid();await catalog.UpdateAsync(TenantId,id,x.Command,ct);return RedirectToAction(nameof(Catalog));}
[HttpGet("Entries")]public async Task<IActionResult>Entries(DateOnly?competence,string?status,CancellationToken ct)=>Can("archive.productivity.view")?View(await productivity.ListAsync(TenantId,new(competence,status),ct)):Forbid();
[HttpGet("Register")]public async Task<IActionResult>Register(CancellationToken ct){if(!Can("archive.productivity.register"))return Forbid();ViewBag.Catalog=await catalog.ListAsync(TenantId,ct);return View(new RegisterInput());}
[HttpPost("Register"),ValidateAntiForgeryToken]public async Task<IActionResult>Register(RegisterInput x,CancellationToken ct){if(!Can("archive.productivity.register")||UserId is not Guid u)return Forbid();try{await productivity.RegisterAsync(new(TenantId,x.ServiceCatalogId,u,x.CompetenceMonth,x.Quantity,x.UstQuantity,Notes:x.Notes),ct);return RedirectToAction(nameof(Entries));}catch(InvalidOperationException e){ModelState.AddModelError("",e.Message);ViewBag.Catalog=await catalog.ListAsync(TenantId,ct);return View(x);}}
[HttpPost("Entries/{id:guid}/Approve"),ValidateAntiForgeryToken]public async Task<IActionResult>Approve(Guid id,CancellationToken ct){if(!Can("archive.productivity.approve")||UserId is not Guid u)return Forbid();await productivity.ApproveAsync(TenantId,id,u,ct);return RedirectToAction(nameof(Entries));}
[HttpPost("Entries/{id:guid}/Reject"),ValidateAntiForgeryToken]public async Task<IActionResult>Reject(Guid id,string reason,CancellationToken ct){if(!Can("archive.productivity.approve")||UserId is not Guid u)return Forbid();await productivity.RejectAsync(TenantId,id,u,reason,ct);return RedirectToAction(nameof(Entries));}
[HttpGet("Billing")]public IActionResult Billing()=>Can("archive.productivity.billing.view")?View():Forbid();
[HttpGet("Billing/Preview")]public async Task<IActionResult>BillingPreview(DateOnly competence,CancellationToken ct)=>Can("archive.productivity.billing.view")?View(await billing.PreviewAsync(TenantId,competence,ct)):Forbid();
[HttpPost("Billing/Close"),ValidateAntiForgeryToken]public async Task<IActionResult>Close(DateOnly competence,string?notes,CancellationToken ct){if(!Can("archive.productivity.billing.close")||UserId is not Guid u)return Forbid();await billing.ClosePeriodAsync(TenantId,competence,u,notes,ct);return RedirectToAction(nameof(BillingPreview),new{competence});}
[HttpPost("Billing/Approve"),ValidateAntiForgeryToken]public async Task<IActionResult>ApproveBilling(DateOnly competence,CancellationToken ct){if(!Can("archive.productivity.billing.approve")||UserId is not Guid u)return Forbid();await billing.ApprovePeriodAsync(TenantId,competence,u,ct);return RedirectToAction(nameof(BillingPreview),new{competence});}
[HttpGet("Export")]public async Task<IActionResult>Export(DateOnly?competence,string?status,CancellationToken ct){if(!Can("archive.productivity.export"))return Forbid();var rows=await productivity.ListAsync(TenantId,new(competence,status),ct);var csv="Serviço;Competência;Data;Origem;Quantidade;UST;Valor;Status\n"+string.Join('\n',rows.Select(x=>$"{C(x.ServiceName)};{x.CompetenceMonth:yyyy-MM};{x.PerformedAt:O};{C(x.SourceType)};{x.Quantity};{x.UstQuantity};{x.TotalAmount};{x.Status}"));return File(Encoding.UTF8.GetBytes('\uFEFF'+csv),"text/csv; charset=utf-8","produtividade-acervo.csv");}
bool Can(string p)=>User.IsFullAdmin()||User.IsInNormalizedRole("ArquivistaOphir")||User.Claims.Any(c=>(c.Type is "permission" or "permissions")&&c.Value.Split(' ').Contains(p,StringComparer.OrdinalIgnoreCase));static string C(string?x)=>$"\"{(x??"").Replace("\"","\"\"")}\"";
public sealed class CatalogInput{public CatalogInput(){}public CatalogInput(ArchiveServiceCatalogItem x){Code=x.Code;Name=x.Name;Description=x.Description;Unit=x.Unit;UnitPrice=x.UnitPrice;DefaultUstQuantity=x.DefaultUstQuantity;CalculationRule=x.CalculationRule;DisplayOrder=x.DisplayOrder;}[System.ComponentModel.DataAnnotations.Required]public string Code{get;set;}="";[System.ComponentModel.DataAnnotations.Required]public string Name{get;set;}="";public string?Description{get;set;}public string Unit{get;set;}="UST";public decimal UnitPrice{get;set;}public decimal DefaultUstQuantity{get;set;}=1;public string CalculationRule{get;set;}="MANUAL";public int DisplayOrder{get;set;}public ArchiveServiceCatalogCommand Command=>new(Code,Name,Description,Unit,UnitPrice,DefaultUstQuantity,CalculationRule,DisplayOrder);}
public sealed class RegisterInput{public Guid ServiceCatalogId{get;set;}public DateOnly CompetenceMonth{get;set;}=new(DateTime.Today.Year,DateTime.Today.Month,1);public decimal Quantity{get;set;}=1;public decimal?UstQuantity{get;set;}public string?Notes{get;set;}}
}
