using InovaGed.Application.Common.Database;
using InovaGed.Application.ContractMeasurement;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InovaGed.Web.Controllers;

[Authorize, Route("ContractMeasurement")]
public sealed class ContractMeasurementController(IDbConnectionFactory db,IContractMeasurementDashboardService dashboard,IContractServiceCatalogService catalog,IContractProductivityService productivity,IContractMeasurementPeriodService periods,IContractGlosaService glosas,IContractMeasurementReportService reports,ILogger<ContractMeasurementController> logger) : GedControllerBase(db)
{
 [HttpGet("")] public Task<IActionResult> Index(CancellationToken ct)=>Safe(async()=>View(await dashboard.GetDashboardAsync(TenantId,ct)),ct);
 [HttpGet("ServiceCatalog")] public Task<IActionResult> ServiceCatalog(CancellationToken ct)=>Safe(async()=>View(await catalog.ListAsync(TenantId,ct)),ct);
 [HttpGet("Productivity")] public Task<IActionResult> Productivity([FromQuery]int?month,[FromQuery]int?year,[FromQuery]Guid?serviceId,[FromQuery]string?user,[FromQuery]string?source,[FromQuery]string?status,[FromQuery]string?search,CancellationToken ct)=>Safe(async()=>{ViewBag.Services=await catalog.ListAsync(TenantId,ct);return View(await productivity.ListAsync(new(TenantId,month,year,serviceId,user,source,status,search),ct));},ct);
 [HttpGet("Productivity/Create")] public Task<IActionResult> ProductivityCreate(CancellationToken ct)=>Safe(async()=>{ViewBag.Services=await catalog.ListAsync(TenantId,ct);return View(new ProductivityInput());},ct,"ProductivityCreate");
 [HttpPost("Productivity/Create"),ValidateAntiForgeryToken] public async Task<IActionResult> ProductivityCreate(ProductivityInput input,CancellationToken ct){if(UserId is not Guid u)return Forbid();if(!ModelState.IsValid){ViewBag.Services=await catalog.ListAsync(TenantId,ct);return View(input);}try{await productivity.CreateAsync(new(TenantId,input.ServiceId,input.SourceType,null,input.DocumentId,input.BoxId,input.Quantity,input.UnitValue,u,User.Identity?.Name,input.PerformedAt,input.Notes,input.EvidenceRequired),ct);TempData["Success"]="Lançamento criado para auditoria.";return RedirectToAction(nameof(Productivity));}catch(Exception ex){logger.LogWarning(ex,"CONTRACT_PRODUCTIVITY_CREATE_FAILED");ModelState.AddModelError("",ex.Message);ViewBag.Services=await catalog.ListAsync(TenantId,ct);return View(input);}}
 [HttpGet("Periods")] public Task<IActionResult> Periods(CancellationToken ct)=>Safe(async()=>View(await periods.ListAsync(TenantId,ct)),ct);
 [HttpGet("Periods/{id:guid}")] public Task<IActionResult> PeriodDetails(Guid id,CancellationToken ct)=>Safe(async()=>{var model=await periods.GetAsync(TenantId,id,ct);return model is null?NotFound():View("PeriodDetails",model);},ct,"PeriodDetails");
 [HttpPost("Periods/Create"),ValidateAntiForgeryToken] public async Task<IActionResult> CreatePeriod(int referenceMonth,int referenceYear,string?notes,CancellationToken ct){if(UserId is not Guid u)return Forbid();try{var id=await periods.CreateAsync(new(TenantId,referenceMonth,referenceYear,u,notes),ct);return RedirectToAction(nameof(PeriodDetails),new{id});}catch(Exception ex){TempData["Warning"]=ex.Message;return RedirectToAction(nameof(Periods));}}
 [HttpPost("Periods/{id:guid}/Close"),ValidateAntiForgeryToken] public Task<IActionResult> Close(Guid id,CancellationToken ct)=>PeriodCommand(id,(u)=>periods.CloseAsync(TenantId,id,u,ct));
 [HttpGet("Periods/{id:guid}/Items")] public Task<IActionResult> Items(Guid id,CancellationToken ct)=>PeriodDetails(id,ct);
 [HttpPost("Periods/{id:guid}/GenerateItems"),ValidateAntiForgeryToken] public Task<IActionResult> GenerateItems(Guid id,CancellationToken ct)=>PeriodCommand(id,(u)=>periods.GenerateItemsAsync(TenantId,id,u,ct));
 [HttpGet("Periods/{id:guid}/Evidence")] public Task<IActionResult> Evidence(Guid id,CancellationToken ct)=>PeriodDetails(id,ct);
 [HttpPost("Periods/{id:guid}/Evidence/Register"),ValidateAntiForgeryToken] public async Task<IActionResult> RegisterEvidence(Guid id,Guid?itemId,string?sourceType,string title,string?description,string?evidenceHash,CancellationToken ct){if(UserId is not Guid u)return Forbid();try{await periods.RegisterEvidenceAsync(TenantId,id,itemId,sourceType,null,title,description,evidenceHash,u,User.Identity?.Name,ct);return RedirectToAction(nameof(PeriodDetails),new{id});}catch(Exception ex){TempData["Warning"]=ex.Message;return RedirectToAction(nameof(PeriodDetails),new{id});}}
 [HttpGet("Glosas")] public Task<IActionResult> Glosas(CancellationToken ct)=>Safe(async()=>{ViewBag.Periods=await periods.ListAsync(TenantId,ct);return View(await glosas.ListAsync(TenantId,ct));},ct);
 [HttpPost("Glosas/Create"),ValidateAntiForgeryToken] public async Task<IActionResult> CreateGlosa(Guid periodId,Guid?itemId,string reason,decimal amount,CancellationToken ct){if(UserId is not Guid u)return Forbid();try{await glosas.CreateAsync(new(TenantId,periodId,itemId,reason,amount,u),ct);}catch(Exception ex){TempData["Warning"]=ex.Message;}return RedirectToAction(nameof(Glosas));}
 [HttpPost("Glosas/{id:guid}/Resolve"),ValidateAntiForgeryToken] public async Task<IActionResult> ResolveGlosa(Guid id,string notes,CancellationToken ct){if(UserId is not Guid u)return Forbid();try{await glosas.ResolveAsync(TenantId,id,u,notes,ct);}catch(Exception ex){TempData["Warning"]=ex.Message;}return RedirectToAction(nameof(Glosas));}
 [HttpGet("Acceptance")] public Task<IActionResult> Acceptance(CancellationToken ct)=>Safe(async()=>View(await periods.ListAsync(TenantId,ct)),ct);
 [HttpPost("Periods/{id:guid}/SubmitAcceptance"),ValidateAntiForgeryToken] public Task<IActionResult> SubmitAcceptance(Guid id,CancellationToken ct)=>PeriodCommand(id,u=>periods.SubmitAsync(TenantId,id,u,ct));
 [HttpPost("Periods/{id:guid}/Approve"),ValidateAntiForgeryToken] public Task<IActionResult> Approve(Guid id,string?notes,CancellationToken ct)=>PeriodCommand(id,u=>periods.ApproveAsync(TenantId,id,u,notes,ct));
 [HttpPost("Periods/{id:guid}/Reject"),ValidateAntiForgeryToken] public Task<IActionResult> Reject(Guid id,string reason,CancellationToken ct)=>PeriodCommand(id,u=>periods.RejectAsync(TenantId,id,u,reason,ct));
 [HttpGet("Reports")] public IActionResult Reports()=>View();
 [HttpGet("Export")] public async Task<IActionResult> Export(string reportType,CancellationToken ct){try{return File(await reports.ExportAsync(TenantId,reportType,ct),"text/csv; charset=utf-8",$"contract-{reportType}-{DateTime.UtcNow:yyyyMMdd}.csv");}catch(ArgumentException ex){return BadRequest(ex.Message);}catch(Exception ex){logger.LogError(ex,"CONTRACT_REPORT_EXPORTED_FAILED");TempData["Warning"]="Estrutura indisponível. Valide a prontidão do banco.";return RedirectToAction(nameof(Reports));}}
 async Task<IActionResult> PeriodCommand(Guid id,Func<Guid,Task> command){if(UserId is not Guid u)return Forbid();try{await command(u);TempData["Success"]="Operação registrada com rastreabilidade.";}catch(Exception ex){logger.LogWarning(ex,"CONTRACT_MEASUREMENT_COMMAND_FAILED");TempData["Warning"]=ex.Message;}return RedirectToAction(nameof(PeriodDetails),new{id});}
 async Task<IActionResult> Safe(Func<Task<IActionResult>> action,CancellationToken ct,string?view=null){try{return await action();}catch(Exception ex){logger.LogError(ex,"CONTRACT_MEASUREMENT_SCHEMA_INCOMPLETE");ViewData["ContractReadinessError"]="A estrutura de medição ainda não está disponível. Aplique a migration pela Prontidão do Banco.";return View(view);}}
 public sealed class ProductivityInput{public Guid ServiceId{get;set;}public string?SourceType{get;set;}public Guid?DocumentId{get;set;}public Guid?BoxId{get;set;}public decimal Quantity{get;set;}=1;public decimal UnitValue{get;set;}public DateTimeOffset PerformedAt{get;set;}=DateTimeOffset.Now;public string?Notes{get;set;}public bool EvidenceRequired{get;set;}}
}
