using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Web.Models.Branding;
using InovaGed.Web.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace InovaGed.Web.Controllers;
[Authorize(Policy=AppPolicies.FullAdminOnly)]
public sealed class LabelsBrandingController(IDbConnectionFactory dbFactory) : GedControllerBase(dbFactory)
{
 [HttpGet("/Labels/Branding")] public async Task<IActionResult> Index(CancellationToken ct){ViewBag.Assets=await Assets(ct);using var db=await OpenAsync();ViewBag.Bindings=(await db.QueryAsync<(string TemplateCode,Guid? LogoAssetId)>(new CommandDefinition("select template_code TemplateCode,logo_asset_id LogoAssetId from ged.print_template_brand_binding where tenant_id=@tenant and print_context='LABEL' and reg_status='A'",new{tenant=TenantId},cancellationToken:ct))).ToDictionary(x=>x.TemplateCode,x=>x.LogoAssetId,StringComparer.OrdinalIgnoreCase);return View("~/Views/Labels/Branding.cshtml");}
 [HttpPost("/Labels/Branding/SaveTemplateLogo"),ValidateAntiForgeryToken] public async Task<IActionResult> SaveTemplateLogo(string templateCode,Guid? logoAssetId,decimal widthMm=38,decimal? heightMm=null,bool preserveAspectRatio=true,string fitMode="CONTAIN",string position="TOP_LEFT",CancellationToken ct=default){var allowed=new[]{"LOCDESK_PASTA_V1","LOCDESK_CAIXA_V1","LOCDESK_PASTA_HOL_V1","FACTORY_BOX_V1","FACTORY_DOCUMENT_V1"};if(!allowed.Contains(templateCode,StringComparer.OrdinalIgnoreCase)||widthMm is <10 or >90||heightMm is <5 or >60||!new[]{"CONTAIN","COVER","FILL"}.Contains(fitMode)||!new[]{"TOP_LEFT","TOP_CENTER","TOP_RIGHT","CENTER","BOTTOM_LEFT","BOTTOM_CENTER","BOTTOM_RIGHT"}.Contains(position))return BadRequest();using var db=await OpenAsync();if(logoAssetId.HasValue&&!await Owns(db,logoAssetId.Value,ct))return BadRequest();using var tx=db.BeginTransaction();var args=new{tenant=TenantId,template=templateCode,logo=logoAssetId,width=widthMm,height=heightMm,preserve=preserveAspectRatio,fit=fitMode,position,user=UserId};await db.ExecuteAsync(new CommandDefinition("insert into ged.print_logo_selection(tenant_id,context,context_key,logo_asset_id,width_mm,height_mm,preserve_aspect_ratio,fit_mode,position,created_by) values(@tenant,'LABEL_TEMPLATE',@template,@logo,@width,@height,@preserve,@fit,@position,@user) on conflict (tenant_id,context,context_key) where reg_status='A' do update set logo_asset_id=excluded.logo_asset_id,width_mm=excluded.width_mm,height_mm=excluded.height_mm,preserve_aspect_ratio=excluded.preserve_aspect_ratio,fit_mode=excluded.fit_mode,position=excluded.position,updated_at=now()",args,tx,cancellationToken:ct));await db.ExecuteAsync(new CommandDefinition("insert into ged.print_template_brand_binding(tenant_id,template_code,logo_asset_id,created_by) values(@tenant,@template,@logo,@user) on conflict (coalesce(tenant_id,'00000000-0000-0000-0000-000000000000'::uuid),template_code,print_context,logo_slot) where reg_status='A' do update set logo_asset_id=excluded.logo_asset_id,enabled=true,updated_at=now()",args,tx,cancellationToken:ct));tx.Commit();return RedirectToAction(nameof(Index));}
 [HttpPost("/Labels/Branding/SetTemplateLogo"),ValidateAntiForgeryToken] public Task<IActionResult> SetTemplateLogo(string templateCode,Guid? logoAssetId,CancellationToken ct)=>SaveTemplateLogo(templateCode,logoAssetId,ct:ct);
 [HttpPost("/Labels/Branding/SetDefaultLogo"),ValidateAntiForgeryToken] public async Task<IActionResult> SetDefaultLogo(Guid logoAssetId,CancellationToken ct){using var db=await OpenAsync();if(!await Owns(db,logoAssetId,ct))return BadRequest();using var tx=db.BeginTransaction();await db.ExecuteAsync("update ged.brand_asset set is_default=false where tenant_id=@tenant and reg_status='A'",new{tenant=TenantId},tx);await db.ExecuteAsync("update ged.brand_asset set is_default=true where id=@id and tenant_id=@tenant",new{id=logoAssetId,tenant=TenantId},tx);tx.Commit();return RedirectToAction(nameof(Index));}
 [HttpGet("/Labels/Branding/TestPrint")] public async Task<IActionResult> TestPrint(CancellationToken ct){var asset=(await Assets(ct)).FirstOrDefault(x=>x.IsDefault);return View("~/Views/Administration/BrandAssets/Preview.cshtml",new PrintLogoViewModel{LogoUrl=asset?.FileUrl,Alt=asset?.AssetName??"Logo oficial",WidthMm=38});}
 private async Task<IReadOnlyList<BrandAssetVm>> Assets(CancellationToken ct){using var db=await OpenAsync();return(await db.QueryAsync<BrandAssetVm>(new CommandDefinition("select id,brand_name BrandName,asset_name AssetName,original_file_name OriginalFileName,content_type ContentType,file_extension FileExtension,file_size_bytes FileSizeBytes,storage_relative_path StorageRelativePath,is_default IsDefault,status,created_at CreatedAt from ged.brand_asset where tenant_id=@tenant and status='ACTIVE' and reg_status='A' order by is_default desc,asset_name",new{tenant=TenantId},cancellationToken:ct))).AsList();}
 private async Task<bool> Owns(System.Data.IDbConnection db,Guid id,CancellationToken ct)=>await db.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from ged.brand_asset where id=@id and tenant_id=@tenant and status='ACTIVE' and reg_status='A')",new{id,tenant=TenantId},cancellationToken:ct));
}
