using System.Text.Json;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Labels.Intelligence;
using InovaGed.Application.Labels.Tracking;
using InovaGed.Web.Models;
using InovaGed.Web.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InovaGed.Web.Controllers;

[Authorize(Policy=AppPolicies.GedAccess)]
[Route("LabelMobile")]
public sealed class LabelMobileController(IDbConnectionFactory dbFactory,ILabelTrackingService tracking,ILabelInventoryService inventory,ILabelCustodyService custody,IWebHostEnvironment environment):GedControllerBase(dbFactory)
{
 [HttpGet("")] public IActionResult Index()=>View();
 [HttpGet("Scanner")] public IActionResult Scanner(Guid? inventorySessionId,string? expectedLocation){ViewBag.InventorySessionId=inventorySessionId;ViewBag.ExpectedLocation=expectedLocation;return View();}
 [HttpGet("Inventory")] public async Task<IActionResult> Inventory(CancellationToken ct){using var db=await OpenAsync();return View("InventoryIndex",await db.QueryAsync("select id,session_number,title,expected_location,status,started_at,(select count(*) from ged.label_inventory_item i where i.tenant_id=s.tenant_id and i.session_id=s.id and i.reg_status='A') total from ged.label_inventory_session s where tenant_id=@tid and reg_status='A' order by started_at desc",new{tid=TenantId}));}
 [HttpGet("Inventory/New")] public IActionResult InventoryNew()=>View();
 [HttpPost("Inventory/New"),ValidateAntiForgeryToken] public async Task<IActionResult> InventoryNew(string title,string? expectedLocation,string? notes,CancellationToken ct){if(UserId is not Guid uid)return Unauthorized();var id=await inventory.StartSessionAsync(new(TenantId,uid,Clean(title,200)!,Clean(expectedLocation,200),Clean(notes,2000)),ct);await custody.RegisterEventAsync(new(TenantId,"INVENTORY",id,null,"INVENTORY_STARTED","Inventário mobile iniciado",notes,"label_inventory_session",id,null,expectedLocation,uid,Ip,Agent,JsonSerializer.Serialize(new{origin="MOBILE"})),ct);return RedirectToAction(nameof(InventorySession),new{id});}
 [HttpGet("Inventory/{id:guid}")] public async Task<IActionResult> InventorySession(Guid id,CancellationToken ct){var session=await inventory.GetSessionAsync(TenantId,id,ct);return session is null?NotFound():View(session);}
 [HttpPost("Inventory/{id:guid}/Close"),ValidateAntiForgeryToken] public async Task<IActionResult> CloseInventory(Guid id,string? justification,CancellationToken ct){if(UserId is not Guid uid)return Unauthorized();await inventory.CloseSessionAsync(TenantId,id,uid,Clean(justification,2000),ct);await custody.RegisterEventAsync(new(TenantId,"INVENTORY",id,null,"INVENTORY_COMPLETED","Inventário mobile concluído",justification,"label_inventory_session",id,null,null,uid,Ip,Agent,JsonSerializer.Serialize(new{origin="MOBILE"})),ct);return RedirectToAction(nameof(InventorySession),new{id});}
 [HttpGet("OfflineStatus")] public IActionResult OfflineStatus()=>View();

 [HttpPost("Scan"),ValidateAntiForgeryToken] public async Task<IActionResult> Scan([FromBody]MobileSyncItem item,CancellationToken ct){if(UserId is not Guid uid)return Unauthorized();var result=await Process(item,null,uid,ct);return Json(result);}
 [HttpPost("Sync"),ValidateAntiForgeryToken] public async Task<IActionResult> Sync([FromBody]MobileSyncRequest request,CancellationToken ct)
 {
  if(UserId is not Guid uid)return Unauthorized();if(string.IsNullOrWhiteSpace(request.ClientSyncId)||request.ClientSyncId.Length>120)return BadRequest(new{message="Identificador de sincronização inválido."});
  var items=(request.Items??[]).Take(500).ToList();using var db=await OpenAsync();
  if(await db.ExecuteScalarAsync<bool>("select exists(select 1 from ged.label_mobile_sync_log where tenant_id=@tid and client_sync_id=@id)",new{tid=TenantId,id=request.ClientSyncId}))return Json(new MobileSyncResponse(request.ClientSyncId,0,items.Count,items.Select(x=>new MobileSyncItemResult(x.ClientId,"duplicado","Sincronização já recebida.")).ToList()));
  var results=new List<MobileSyncItemResult>();foreach(var item in items){try{results.Add(await Process(item,Clean(request.DeviceId,120),uid,ct));}catch(Exception){results.Add(new(item.ClientId,"erro","Não foi possível processar esta leitura."));}}
  var accepted=results.Count(x=>x.Status is "aceito" or "divergente");
  await db.ExecuteAsync("insert into ged.label_mobile_sync_log(tenant_id,client_sync_id,device_id,user_id,sync_status,received_items,accepted_items,rejected_items,payload_json,ip_address,user_agent) values(@tid,@id,@device,@uid,'COMPLETED',@received,@accepted,@rejected,cast(@json as jsonb),cast(nullif(@ip,'') as inet),@agent)",new{tid=TenantId,id=request.ClientSyncId,device=Clean(request.DeviceId,120),uid,received=items.Count,accepted,rejected=items.Count-accepted,json=JsonSerializer.Serialize(request),ip=Ip,agent=Agent});
  return Json(new MobileSyncResponse(request.ClientSyncId,accepted,items.Count-accepted,results));
 }

 [HttpPost("Evidence"),ValidateAntiForgeryToken,RequestSizeLimit(8*1024*1024)] public async Task<IActionResult> Evidence(IFormFile file,string subjectType,Guid? subjectId,string? controlNumber,Guid? inventorySessionId,Guid? scanEventId,string? evidenceType,string? description,string? expectedLocation,string? foundLocation,string? deviceId,decimal? latitude,decimal? longitude,CancellationToken ct)
 {
  if(UserId is not Guid uid)return Unauthorized();if(file is null||file.Length==0||file.Length>8*1024*1024)return BadRequest("A foto deve ter até 8 MB.");
  var allowed=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{"image/jpeg",".jpg"},{"image/png",".png"},{"image/webp",".webp"}};if(!allowed.TryGetValue(file.ContentType,out var ext))return BadRequest("Formato de imagem não permitido.");
  subjectType=Clean(subjectType,40)??"UNKNOWN";if(subjectId.HasValue&&!await SubjectBelongs(subjectType,subjectId.Value,ct))return NotFound();
  var id=Guid.NewGuid();var now=DateTime.UtcNow;var relative=Path.Combine("label-evidence",TenantId.ToString("N"),now.ToString("yyyy"),now.ToString("MM"),id+ext);var root=Path.Combine(environment.ContentRootPath,"App_Data");var full=Path.Combine(root,relative);Directory.CreateDirectory(Path.GetDirectoryName(full)!);await using(var stream=System.IO.File.Create(full)){await file.CopyToAsync(stream,ct);}
  using var db=await OpenAsync();await db.ExecuteAsync("insert into ged.label_evidence(id,tenant_id,subject_type,subject_id,control_number,inventory_session_id,scan_event_id,evidence_type,file_name,content_type,file_size,storage_path,description,location_expected,location_found,captured_by,latitude,longitude,ip_address,user_agent,payload_json) values(@id,@tid,@subjectType,@subjectId,@controlNumber,@inventorySessionId,@scanEventId,@evidenceType,@fileName,@contentType,@size,@path,@description,@expectedLocation,@foundLocation,@uid,@latitude,@longitude,cast(nullif(@ip,'') as inet),@agent,cast(@payload as jsonb))",new{id,tid=TenantId,subjectType,subjectId,controlNumber=Clean(controlNumber,200),inventorySessionId,scanEventId,evidenceType=Clean(evidenceType,40)??"PHOTO",fileName=Path.GetFileName(file.FileName),contentType=file.ContentType,size=file.Length,path=relative,description=Clean(description,2000),expectedLocation=Clean(expectedLocation,200),foundLocation=Clean(foundLocation,200),uid,latitude,longitude,ip=Ip,agent=Agent,payload=JsonSerializer.Serialize(new{origin="MOBILE",deviceId=Clean(deviceId,120)})});
  await custody.RegisterEventAsync(new(TenantId,subjectType,subjectId,controlNumber,"EVIDENCE_CAPTURED","Evidência mobile capturada",description,"label_evidence",id,expectedLocation,foundLocation,uid,Ip,Agent,JsonSerializer.Serialize(new{origin="MOBILE",deviceId})),ct);return Json(new{id,url=Url.Action(nameof(GetEvidence),new{id})});
 }
 [HttpGet("Evidence/{id:guid}")] public async Task<IActionResult> GetEvidence(Guid id){using var db=await OpenAsync();var row=await db.QuerySingleOrDefaultAsync<EvidenceRow>("select storage_path Path,content_type ContentType,file_name FileName from ged.label_evidence where tenant_id=@tid and id=@id and reg_status='A'",new{tid=TenantId,id});if(row is null)return NotFound();var full=Path.GetFullPath(Path.Combine(environment.ContentRootPath,"App_Data",row.Path));var safe=Path.GetFullPath(Path.Combine(environment.ContentRootPath,"App_Data"));if(!full.StartsWith(safe,StringComparison.Ordinal)||!System.IO.File.Exists(full))return NotFound();return PhysicalFile(full,row.ContentType??"application/octet-stream",enableRangeProcessing:true);}
 [HttpPost("Move"),Authorize(Policy=AppPolicies.FullAdminOnly),ValidateAntiForgeryToken] public async Task<IActionResult> Move([FromBody]MobileMoveRequest request,CancellationToken ct)
 {
  if(UserId is not Guid uid)return Unauthorized();if(string.IsNullOrWhiteSpace(request.NewLocation)||string.IsNullOrWhiteSpace(request.Reason))return BadRequest(new{message="Nova localização e motivo são obrigatórios."});var trace=await tracking.TraceAsync(TenantId,request.Payload,ct);if(trace?.SubjectType!="BOX"||trace.SubjectId is not Guid boxId)return BadRequest(new{message="A etiqueta não identifica uma caixa válida."});using var db=await OpenAsync();var location=await db.QuerySingleOrDefaultAsync<(Guid Id,string Code)>("select id,full_location_code Code from ged.physical_location where tenant_id=@tid and reg_status='A' and upper(full_location_code)=upper(@code)",new{tid=TenantId,code=request.NewLocation.Trim()});if(location.Id==Guid.Empty)return BadRequest(new{message="Localização não encontrada."});var old=await db.ExecuteScalarAsync<Guid?>("select location_id from ged.box where tenant_id=@tid and id=@id and reg_status='A'",new{tid=TenantId,id=boxId});await db.ExecuteAsync("update ged.box set location_id=@newId,last_moved_at=now(),last_moved_by=@uid,updated_at=now() where tenant_id=@tid and id=@boxId and reg_status='A';insert into ged.box_location_history(tenant_id,box_id,old_location_id,new_location_id,changed_by,notes,data) values(@tid,@boxId,@old,@newId,@uid,@notes,cast(@data as jsonb));",new{tid=TenantId,boxId,old,newId=location.Id,uid,notes=Clean(request.Reason+" "+request.Observation,2000),data=JsonSerializer.Serialize(new{origin="MOBILE",request.DeviceId})});await custody.RegisterEventAsync(new(TenantId,"BOX",boxId,trace.ControlNumber,"PHYSICAL_MOVE","Movimentação física mobile",request.Reason,"box_location_history",null,trace.CurrentLocation,location.Code,uid,Ip,Agent,JsonSerializer.Serialize(new{origin="MOBILE",request.DeviceId})),ct);return Json(new{status="aceito",location=location.Code});
 }
 private async Task<MobileSyncItemResult> Process(MobileSyncItem item,string? device,Guid uid,CancellationToken ct){if(string.IsNullOrWhiteSpace(item.ClientId)||item.ClientId.Length>120||string.IsNullOrWhiteSpace(item.Payload))return new(item.ClientId??"","inválido","Leitura incompleta.");using(var db=await OpenAsync())if(await db.ExecuteScalarAsync<bool>("select exists(select 1 from ged.label_scan_event where tenant_id=@tid and mobile_client_id=@client)",new{tid=TenantId,client=item.ClientId}))return new(item.ClientId,"duplicado","Leitura já sincronizada.");var scan=item.InventorySessionId is Guid session?await InventoryScan(session,item,uid,ct):await DirectScan(item,uid,ct);using(var db=await OpenAsync())await db.ExecuteAsync("update ged.label_scan_event set mobile_client_id=@client,device_id=@device,captured_at=@captured where tenant_id=@tid and id=@id",new{client=item.ClientId,device, captured=item.CapturedAt?.UtcDateTime,tid=TenantId,id=scan.EventId});var divergent=scan.Status.Contains("DIVERG",StringComparison.OrdinalIgnoreCase);if(divergent)using(var db=await OpenAsync())await db.ExecuteAsync("insert into ged.label_alert(tenant_id,alert_type,severity,subject_type,subject_id,control_number,location,title,message) values(@tid,'LOCATION_DIVERGENCE','HIGH',@type,@subject,@control,@location,'Divergência em leitura mobile','Localização encontrada difere da esperada.') on conflict do nothing",new{tid=TenantId,type=item.SubjectType,subject=item.SubjectId,control=item.ControlNumber,location=item.FoundLocation});return new(item.ClientId,divergent?"divergente":scan.Status is "INVALID_PAYLOAD" or "NOT_FOUND"?"inválido":"aceito",scan.Message,scan.EventId);}
 private async Task<LabelScanResult> DirectScan(MobileSyncItem x,Guid uid,CancellationToken ct)=>await tracking.ScanAsync(new(TenantId,uid,x.Payload,Clean(x.FoundLocation,200),"MOBILE",Ip,Agent),ct);
 private async Task<LabelScanResult> InventoryScan(Guid session,MobileSyncItem x,Guid uid,CancellationToken ct){var r=await tracking.ScanAsync(new(TenantId,uid,x.Payload,Clean(x.FoundLocation,200),"MOBILE_OFFLINE",Ip,Agent),ct);await inventory.AddScanAsync(new(TenantId,session,uid,x.Payload,Clean(x.FoundLocation,200),Ip,Agent),ct);return r;}
 private async Task<bool> SubjectBelongs(string type,Guid id,CancellationToken ct){var table=type.ToUpperInvariant() switch{"BOX"=>"box","DOCUMENT"=>"document","FOLDER"=>"folder",_=>null};if(table is null)return true;using var db=await OpenAsync();return await db.ExecuteScalarAsync<bool>($"select exists(select 1 from ged.{table} where tenant_id=@tid and id=@id and reg_status='A')",new{tid=TenantId,id});}
 private string? Ip=>HttpContext.Connection.RemoteIpAddress?.ToString();private string? Agent=>Request.Headers.UserAgent.ToString();private static string? Clean(string? value,int max){if(string.IsNullOrWhiteSpace(value))return null;return value.Trim()[..Math.Min(value.Trim().Length,max)];}private sealed class EvidenceRow{public string Path{get;set;}="";public string? ContentType{get;set;}public string? FileName{get;set;}}
}
