using Dapper;
using InovaGed.Application.Branding;
using InovaGed.Application.Common.Database;
using InovaGed.Web.Models.Branding;
using InovaGed.Web.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InovaGed.Web.Controllers;

[Authorize(Policy=AppPolicies.Administracao)]
[Route("Administration/PrintBranding")]
public sealed class PrintBrandingController(IDbConnectionFactory factory, IPrintBrandingResolver resolver) : GedControllerBase(factory)
{
    private static readonly (string Context,string Key,string Description)[] Catalog = [
        (PrintBrandingContext.LabelTemplate,"LOCDESK_PASTA_V1","Etiqueta LocDesk Pasta"),(PrintBrandingContext.LabelTemplate,"LOCDESK_CAIXA_V1","Etiqueta LocDesk Caixa"),(PrintBrandingContext.LabelTemplate,"LOCDESK_PASTA_HOL_V1","Etiqueta LocDesk HOL"),(PrintBrandingContext.LabelTemplate,"FACTORY_BOX_V1","Etiqueta de caixa"),(PrintBrandingContext.LabelTemplate,"FACTORY_DOCUMENT_V1","Etiqueta de documento"),(PrintBrandingContext.ContractMeasurement,"CONTRACT_MEASUREMENT_REPORT","Relatório de medição"),(PrintBrandingContext.FiscalPortal,"FISCAL_ACCEPTANCE_TERM","Termo do Portal do Fiscal"),(PrintBrandingContext.GovernanceReport,"GOVERNANCE_REPORT","Relatório de governança"),(PrintBrandingContext.DocumentReport,"DOCUMENT_DISPATCH_SHEET","Folha de despacho"),(PrintBrandingContext.DocumentCover,"DOCUMENT_COVER","Documento de capa")];
    [HttpGet("")] public async Task<IActionResult> Index(CancellationToken ct) => View(await Dashboard(ct));
    [HttpGet("Profiles")] public async Task<IActionResult> Profiles(CancellationToken ct) => View("Index",await Dashboard(ct));
    [HttpGet("Profiles/Create")] public async Task<IActionResult> Create(CancellationToken ct){await Assets(ct);return View(new PrintBrandingProfileInput());}
    [HttpPost("Profiles/Create"),ValidateAntiForgeryToken] public async Task<IActionResult> Create(PrintBrandingProfileInput input,CancellationToken ct){if(!ModelState.IsValid){await Assets(ct);return View(input);} if(!await LogosBelong(input,ct)){ModelState.AddModelError("","Selecione somente logos ativas deste cliente.");await Assets(ct);return View(input);} using var db=await OpenAsync();using var tx=db.BeginTransaction();if(input.IsDefault)await db.ExecuteAsync("update ged.print_branding_profile set is_default=false where tenant_id=@tenant and reg_status='A'",new{tenant=TenantId},tx);var id=Guid.NewGuid();await db.ExecuteAsync("insert into ged.print_branding_profile(id,tenant_id,profile_code,profile_name,client_name,contract_name,organization_name,primary_logo_asset_id,secondary_logo_asset_id,header_title,header_subtitle,header_extra_line,footer_text,footer_extra_line,show_generated_at,show_page_number,show_protocol_info,logo_position,secondary_logo_position,primary_logo_width_mm,secondary_logo_width_mm,paper_size,orientation,margin_top_mm,margin_right_mm,margin_bottom_mm,margin_left_mm,is_default,created_by,created_by_name) values(@Id,@TenantId,@ProfileCode,@ProfileName,@ClientName,@ContractName,@OrganizationName,@PrimaryLogoAssetId,@SecondaryLogoAssetId,@HeaderTitle,@HeaderSubtitle,@HeaderExtraLine,@FooterText,@FooterExtraLine,@ShowGeneratedAt,@ShowPageNumber,@ShowProtocolInfo,@LogoPosition,@SecondaryLogoPosition,@PrimaryLogoWidthMm,@SecondaryLogoWidthMm,@PaperSize,@Orientation,@MarginTopMm,@MarginRightMm,@MarginBottomMm,@MarginLeftMm,@IsDefault,@UserId,@UserName)",new{id,TenantId,input.ProfileCode,input.ProfileName,input.ClientName,input.ContractName,input.OrganizationName,input.PrimaryLogoAssetId,input.SecondaryLogoAssetId,input.HeaderTitle,input.HeaderSubtitle,input.HeaderExtraLine,input.FooterText,input.FooterExtraLine,input.ShowGeneratedAt,input.ShowPageNumber,input.ShowProtocolInfo,input.LogoPosition,input.SecondaryLogoPosition,input.PrimaryLogoWidthMm,input.SecondaryLogoWidthMm,input.PaperSize,input.Orientation,input.MarginTopMm,input.MarginRightMm,input.MarginBottomMm,input.MarginLeftMm,input.IsDefault,UserId,UserName=UserNameSafe},tx);await Audit(db,tx,id,"PRINT_BRANDING_PROFILE_CREATED","Perfil visual criado",ct);tx.Commit();return RedirectToAction(nameof(Index));}
    [HttpGet("Profiles/{id:guid}")] public async Task<IActionResult> Details(Guid id,CancellationToken ct)=>await Profile(id,ct) is{} p?View("Preview",new PrintBrandingPreviewVm{Branding=await resolver.ResolveAsync(TenantId,"","",id,null,ct)}):NotFound();
    [HttpGet("Profiles/{id:guid}/Edit")] public async Task<IActionResult> Edit(Guid id,CancellationToken ct){var p=await Profile(id,ct);if(p is null)return NotFound();await Assets(ct);return View(p);}
    [HttpPost("Profiles/{id:guid}/Edit"),ValidateAntiForgeryToken] public async Task<IActionResult> Edit(Guid id,PrintBrandingProfileInput input,CancellationToken ct){input.Id=id;if(!ModelState.IsValid||!await LogosBelong(input,ct)){if(ModelState.IsValid)ModelState.AddModelError("","Selecione somente logos ativas deste cliente.");await Assets(ct);return View(input);}using var db=await OpenAsync();var changed=await db.ExecuteAsync("update ged.print_branding_profile set profile_code=@ProfileCode,profile_name=@ProfileName,client_name=@ClientName,contract_name=@ContractName,organization_name=@OrganizationName,primary_logo_asset_id=@PrimaryLogoAssetId,secondary_logo_asset_id=@SecondaryLogoAssetId,header_title=@HeaderTitle,header_subtitle=@HeaderSubtitle,header_extra_line=@HeaderExtraLine,footer_text=@FooterText,footer_extra_line=@FooterExtraLine,show_generated_at=@ShowGeneratedAt,show_page_number=@ShowPageNumber,show_protocol_info=@ShowProtocolInfo,logo_position=@LogoPosition,secondary_logo_position=@SecondaryLogoPosition,primary_logo_width_mm=@PrimaryLogoWidthMm,secondary_logo_width_mm=@SecondaryLogoWidthMm,paper_size=@PaperSize,orientation=@Orientation,margin_top_mm=@MarginTopMm,margin_right_mm=@MarginRightMm,margin_bottom_mm=@MarginBottomMm,margin_left_mm=@MarginLeftMm,updated_at=now(),updated_by=@UserId,updated_by_name=@UserName where id=@id and tenant_id=@TenantId and reg_status='A'",new{input.ProfileCode,input.ProfileName,input.ClientName,input.ContractName,input.OrganizationName,input.PrimaryLogoAssetId,input.SecondaryLogoAssetId,input.HeaderTitle,input.HeaderSubtitle,input.HeaderExtraLine,input.FooterText,input.FooterExtraLine,input.ShowGeneratedAt,input.ShowPageNumber,input.ShowProtocolInfo,input.LogoPosition,input.SecondaryLogoPosition,input.PrimaryLogoWidthMm,input.SecondaryLogoWidthMm,input.PaperSize,input.Orientation,input.MarginTopMm,input.MarginRightMm,input.MarginBottomMm,input.MarginLeftMm,UserId,UserName=UserNameSafe,id,TenantId});if(changed==0)return NotFound();return RedirectToAction(nameof(Index));}
    [HttpPost("Profiles/{id:guid}/SetDefault"),ValidateAntiForgeryToken] public async Task<IActionResult> SetDefault(Guid id,CancellationToken ct){using var db=await OpenAsync();using var tx=db.BeginTransaction();if(!await db.ExecuteScalarAsync<bool>("select exists(select 1 from ged.print_branding_profile where id=@id and tenant_id=@tenant and status='ACTIVE' and reg_status='A')",new{id,tenant=TenantId},tx))return NotFound();await db.ExecuteAsync("update ged.print_branding_profile set is_default=(id=@id) where tenant_id=@tenant and reg_status='A'",new{id,tenant=TenantId},tx);await Audit(db,tx,id,"PRINT_BRANDING_PROFILE_SET_DEFAULT","Perfil definido como padrão",ct);tx.Commit();return RedirectToAction(nameof(Index));}
    [HttpPost("Profiles/{id:guid}/Archive"),ValidateAntiForgeryToken] public async Task<IActionResult> Archive(Guid id,string? reason,CancellationToken ct){using var db=await OpenAsync();var n=await db.ExecuteAsync("update ged.print_branding_profile set status='ARCHIVED',is_default=false,archived_at=now(),archived_by=@user,archive_reason=@reason where id=@id and tenant_id=@tenant and reg_status='A'",new{id,tenant=TenantId,user=UserId,reason});return n==0?NotFound():RedirectToAction(nameof(Index));}
    [HttpGet("Profiles/{id:guid}/Preview")] public async Task<IActionResult> Preview(Guid id,CancellationToken ct){var b=await resolver.ResolveAsync(TenantId,"","",id,null,ct);if(!b.HasBranding)return NotFound();return View(new PrintBrandingPreviewVm{Branding=b});}
    [HttpGet("Bindings")] public async Task<IActionResult> Bindings(CancellationToken ct){using var db=await OpenAsync();ViewBag.Profiles=await ProfilesList(db,ct);var rows=(await db.QueryAsync<PrintBrandingBindingVm>(new CommandDefinition("select binding_context Context,binding_key BindingKey,profile_id ProfileId,p.profile_name ProfileName,case when p.primary_logo_asset_id is null then null else '/Administration/BrandAssets/'||p.primary_logo_asset_id||'/File' end LogoUrl,b.enabled Enabled from ged.print_branding_binding b join ged.print_branding_profile p on p.id=b.profile_id where b.tenant_id=@tenant and b.reg_status='A'",new{tenant=TenantId},cancellationToken:ct))).ToDictionary(x=>$"{x.Context}|{x.BindingKey}");return View(Catalog.Select(c=>rows.GetValueOrDefault($"{c.Context}|{c.Key}")??new PrintBrandingBindingVm{Context=c.Context,BindingKey=c.Key,Description=c.Description}).Select(x=>{x.Description=Catalog.First(c=>c.Context==x.Context&&c.Key==x.BindingKey).Description;return x;}).ToList());}
    [HttpPost("Bindings/Save"),ValidateAntiForgeryToken] public async Task<IActionResult> SaveBinding(PrintBrandingBindingInput input,CancellationToken ct){if(!Catalog.Any(x=>x.Context==input.Context&&x.Key==input.BindingKey))return BadRequest();using var db=await OpenAsync();if(input.ProfileId is null){await db.ExecuteAsync("update ged.print_branding_binding set reg_status='I',updated_at=now() where tenant_id=@tenant and binding_context=@context and binding_key=@key and reg_status='A'",new{tenant=TenantId,context=input.Context,key=input.BindingKey});return RedirectToAction(nameof(Bindings));}var valid=await db.ExecuteScalarAsync<bool>("select exists(select 1 from ged.print_branding_profile where id=@id and tenant_id=@tenant and status='ACTIVE' and reg_status='A')",new{id=input.ProfileId,tenant=TenantId});if(!valid)return BadRequest();await db.ExecuteAsync("insert into ged.print_branding_binding(tenant_id,binding_context,binding_key,profile_id,enabled,created_by) values(@tenant,@context,@key,@profile,@enabled,@user) on conflict (tenant_id,binding_context,binding_key) where reg_status='A' do update set profile_id=excluded.profile_id,enabled=excluded.enabled,updated_at=now()",new{tenant=TenantId,context=input.Context,key=input.BindingKey,profile=input.ProfileId,enabled=input.Enabled,user=UserId});return RedirectToAction(nameof(Bindings));}
    [HttpGet("TestPrint")] public async Task<IActionResult> TestPrint(Guid? profileId,CancellationToken ct){using var db=await OpenAsync();ViewBag.Profiles=await ProfilesList(db,ct);return View(new PrintBrandingPreviewVm{Branding=await resolver.ResolveAsync(TenantId,"TEST","TEST",profileId,null,ct)});}
    [HttpPost("TestPrint"),ValidateAntiForgeryToken] public IActionResult TestPrintPost(Guid? profileId)=>RedirectToAction(nameof(TestPrint),new{profileId});
    private async Task<PrintBrandingDashboardVm> Dashboard(CancellationToken ct){using var db=await OpenAsync();var ready=await HasTableAsync(db,"ged","print_branding_profile")&&await HasTableAsync(db,"ged","brand_asset");if(!ready)return new(){SchemaReady=false};var profiles=await ProfilesList(db,ct);var assets=await AssetsList(db,ct);var count=await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from ged.print_branding_binding where tenant_id=@tenant and enabled and reg_status='A'",new{tenant=TenantId},cancellationToken:ct));return new(){SchemaReady=true,Profiles=profiles,Assets=assets,BindingCount=count};}
    private async Task<List<PrintBrandingProfileVm>> ProfilesList(System.Data.IDbConnection db,CancellationToken ct)=>(await db.QueryAsync<PrintBrandingProfileVm>(new CommandDefinition("select p.id,p.profile_code ProfileCode,p.profile_name ProfileName,p.client_name ClientName,p.contract_name ContractName,p.organization_name OrganizationName,p.primary_logo_asset_id PrimaryLogoAssetId,p.secondary_logo_asset_id SecondaryLogoAssetId,p.header_title HeaderTitle,p.header_subtitle HeaderSubtitle,p.header_extra_line HeaderExtraLine,p.footer_text FooterText,p.footer_extra_line FooterExtraLine,p.show_generated_at ShowGeneratedAt,p.show_page_number ShowPageNumber,p.show_protocol_info ShowProtocolInfo,p.logo_position LogoPosition,p.secondary_logo_position SecondaryLogoPosition,p.primary_logo_width_mm PrimaryLogoWidthMm,p.secondary_logo_width_mm SecondaryLogoWidthMm,p.paper_size PaperSize,p.orientation,p.margin_top_mm MarginTopMm,p.margin_right_mm MarginRightMm,p.margin_bottom_mm MarginBottomMm,p.margin_left_mm MarginLeftMm,p.is_default IsDefault,p.status,a.asset_name PrimaryLogoName,s.asset_name SecondaryLogoName from ged.print_branding_profile p left join ged.brand_asset a on a.id=p.primary_logo_asset_id left join ged.brand_asset s on s.id=p.secondary_logo_asset_id where p.tenant_id=@tenant and p.reg_status='A' order by p.is_default desc,p.profile_name",new{tenant=TenantId},cancellationToken:ct))).AsList();
    private async Task<PrintBrandingProfileVm?> Profile(Guid id,CancellationToken ct){using var db=await OpenAsync();return (await ProfilesList(db,ct)).FirstOrDefault(x=>x.Id==id);}
    private async Task Assets(CancellationToken ct){using var db=await OpenAsync();ViewBag.Assets=await AssetsList(db,ct);}
    private async Task<List<BrandAssetVm>> AssetsList(System.Data.IDbConnection db,CancellationToken ct)=>(await db.QueryAsync<BrandAssetVm>(new CommandDefinition("select id,brand_name BrandName,asset_name AssetName,original_file_name OriginalFileName,content_type ContentType,file_extension FileExtension,file_size_bytes FileSizeBytes,is_default IsDefault,status,created_at CreatedAt from ged.brand_asset where tenant_id=@tenant and status='ACTIVE' and reg_status='A' order by is_default desc,asset_name",new{tenant=TenantId},cancellationToken:ct))).AsList();
    private async Task<bool> LogosBelong(PrintBrandingProfileInput i,CancellationToken ct){var ids=new[]{i.PrimaryLogoAssetId,i.SecondaryLogoAssetId}.Where(x=>x.HasValue).Select(x=>x!.Value).Distinct().ToArray();if(ids.Length==0)return true;using var db=await OpenAsync();return await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from ged.brand_asset where tenant_id=@tenant and id=any(@ids) and status='ACTIVE' and reg_status='A'",new{tenant=TenantId,ids},cancellationToken:ct))==ids.Length;}
    private async Task Audit(System.Data.IDbConnection db,System.Data.IDbTransaction tx,Guid? profile,string type,string title,CancellationToken ct)=>await db.ExecuteAsync(new CommandDefinition("insert into ged.print_branding_audit_event(tenant_id,profile_id,event_type,title,performed_by,performed_by_name) values(@tenant,@profile,@type,@title,@user,@name)",new{tenant=TenantId,profile,type,title,user=UserId,name=UserNameSafe},tx,cancellationToken:ct));
}
