namespace InovaGed.Application.PhysicalArchive.WorkOrders;

public static class ArchiveWorkOrderType { public const string PrintLabel="PRINT_LABEL",ReplaceLabel="REPLACE_LABEL",CheckLocation="CHECK_LOCATION",MoveBox="MOVE_BOX",ReconcileIssue="RECONCILE_ISSUE",InventoryDivergence="INVENTORY_DIVERGENCE",BoxConference="BOX_CONFERENCE",DocumentConference="DOCUMENT_CONFERENCE",LoanDelivery="LOAN_DELIVERY",LoanReturn="LOAN_RETURN"; }
public static class ArchiveWorkOrderStatus { public const string Open="OPEN",Assigned="ASSIGNED",InProgress="IN_PROGRESS",WaitingValidation="WAITING_VALIDATION",Completed="COMPLETED",Closed="CLOSED",Cancelled="CANCELLED"; }
public static class ArchiveWorkOrderPriority { public const string Low="LOW",Medium="MEDIUM",High="HIGH",Critical="CRITICAL"; }
public sealed record ArchiveWorkOrderCreateCommand(Guid TenantId,Guid UserId,string Title,string OrderType,string Priority=ArchiveWorkOrderPriority.Medium,string? Description=null,string? SubjectType=null,Guid? SubjectId=null,Guid? BoxId=null,Guid? DocumentId=null,string? ControlNumber=null,string? LocationExpected=null,string? LocationFound=null,string? LocationTarget=null,string? SourceType=null,Guid? SourceId=null,Guid? AssignedTo=null,DateTimeOffset? DueAt=null);
public sealed record ArchiveWorkOrderFilter(string? Status=null,string? OrderType=null,string? Priority=null,Guid? AssignedTo=null,string? Location=null,string? ControlNumber=null,string? SourceType=null,string? Due=null);
public sealed record ArchiveWorkOrderListItem(Guid Id,string OrderNumber,string Title,string OrderType,string Priority,string Status,Guid? AssignedTo,string? AssignedName,DateTimeOffset? DueAt,string? SourceType,string? LocationTarget,string? ControlNumber,DateTimeOffset CreatedAt);
public sealed record ArchiveWorkOrderTaskItem(Guid Id,string Title,string? Description,string TaskType,string Status,int DisplayOrder,bool RequiresScan,bool RequiresEvidence,Guid? AssignedTo,DateTimeOffset? CompletedAt,string? ResultNotes);
public sealed record ArchiveWorkOrderEventItem(Guid Id,Guid? TaskId,string EventType,string EventTitle,string? EventDescription,string? FromStatus,string? ToStatus,Guid? PerformedBy,DateTimeOffset PerformedAt);
public sealed record ArchiveWorkOrderEvidenceItem(Guid Id,Guid? TaskId,Guid? LabelEvidenceId,string? Description,Guid? AttachedBy,DateTimeOffset AttachedAt);
public sealed record ArchiveWorkOrderDetails(ArchiveWorkOrderListItem Order,string? Description,string? SubjectType,Guid? SubjectId,Guid? BoxId,Guid? DocumentId,string? LocationExpected,string? LocationFound,DateTimeOffset? StartedAt,DateTimeOffset? CompletedAt,DateTimeOffset? ClosedAt,string? CloseNotes,IReadOnlyList<ArchiveWorkOrderTaskItem> Tasks,IReadOnlyList<ArchiveWorkOrderEventItem> Events,IReadOnlyList<ArchiveWorkOrderEvidenceItem> Evidences);
public sealed record ArchiveWorkOrderTaskResult(string Notes,bool ScanConfirmed=false,Guid? LabelEvidenceId=null,string? EvidenceDescription=null);
public sealed record ArchiveWorkOrderSlaSummary(int Open,int InProgress,int Overdue,int Critical,int WaitingValidation,int CompletedThisMonth,double AverageCompletionHours,int ActiveOperators);
public sealed record ArchiveWorkOrderSlaItem(Guid Id,string OrderNumber,string Title,string Priority,Guid? AssignedTo,string? AssignedName,DateTimeOffset DueAt,double OverdueHours);
public interface IArchiveWorkOrderService { Task<Guid>CreateAsync(ArchiveWorkOrderCreateCommand command,CancellationToken ct); Task<Guid>CreateFromAlertAsync(Guid tenantId,Guid alertId,Guid userId,CancellationToken ct); Task<Guid>CreateFromReconciliationIssueAsync(Guid tenantId,Guid issueId,Guid userId,CancellationToken ct); Task<ArchiveWorkOrderDetails?>GetAsync(Guid tenantId,Guid orderId,CancellationToken ct); Task<IReadOnlyList<ArchiveWorkOrderListItem>>ListAsync(Guid tenantId,ArchiveWorkOrderFilter filter,CancellationToken ct); Task AssignAsync(Guid tenantId,Guid orderId,Guid assignedTo,Guid assignedBy,DateTimeOffset? dueAt,CancellationToken ct); Task StartAsync(Guid tenantId,Guid orderId,Guid userId,CancellationToken ct); Task CompleteAsync(Guid tenantId,Guid orderId,Guid userId,string notes,CancellationToken ct); Task CloseAsync(Guid tenantId,Guid orderId,Guid userId,string notes,CancellationToken ct); Task CancelAsync(Guid tenantId,Guid orderId,Guid userId,string reason,CancellationToken ct); }
public interface IArchiveWorkOrderTaskService { Task CompleteTaskAsync(Guid tenantId,Guid taskId,Guid userId,ArchiveWorkOrderTaskResult result,CancellationToken ct); Task ReopenTaskAsync(Guid tenantId,Guid taskId,Guid userId,string reason,CancellationToken ct); }
public interface IArchiveWorkOrderSlaService { Task<ArchiveWorkOrderSlaSummary>GetSummaryAsync(Guid tenantId,CancellationToken ct); Task<IReadOnlyList<ArchiveWorkOrderSlaItem>>ListOverdueAsync(Guid tenantId,CancellationToken ct); }
