using System.Text.Json;
using Dapper;
using InovaGed.Application.Audit;
using InovaGed.Application.Common.Database;
using InovaGed.Application.SmartGed.Assistant;

namespace InovaGed.Infrastructure.SmartGed.Assistant;
public sealed class SmartGedAssistantService(IDbConnectionFactory db,ISmartAssistantRetrievalService retrieval,ISmartAssistantAnswerComposer composer,ISmartAssistantIntentResolver intentResolver,IAuditWriter audit):ISmartGedAssistantService
{
 public async Task<SmartAssistantSessionDetails> StartSessionAsync(Guid tenantId,Guid userId,string? title,CancellationToken ct)
 {
  var id=Guid.NewGuid(); var safe=LocalSmartAssistantRetrievalService.Mask(string.IsNullOrWhiteSpace(title)?"Nova conversa documental":title.Trim()); await using var c=await db.OpenAsync(ct);
  await c.ExecuteAsync(new CommandDefinition("insert into ged.smart_assistant_session(id,tenant_id,user_id,title) values(@id,@tenantId,@userId,@safe)",new{id,tenantId,userId,safe},cancellationToken:ct));
  await Audit(tenantId,userId,"SMART_ASSISTANT_SESSION_STARTED",id,new{title=safe},ct); return new(id,safe,"ACTIVE",DateTimeOffset.UtcNow,[]);
 }
 public async Task<SmartAssistantAnswer> AskAsync(SmartAssistantQuestionCommand command,CancellationToken ct)
 {
  var question=LocalSmartAssistantRetrievalService.Mask(command.Question.Trim()); if(question.Length<3)throw new ArgumentException("Informe uma pergunta com pelo menos três caracteres.");
  await using var c=await db.OpenAsync(ct); var owns=await c.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from ged.smart_assistant_session where id=@SessionId and tenant_id=@TenantId and user_id=@UserId and reg_status='A')",command,cancellationToken:ct)); if(!owns)throw new InvalidOperationException("Sessão não encontrada para o usuário autenticado.");
  var userMessage=Guid.NewGuid(); await c.ExecuteAsync(new CommandDefinition("insert into ged.smart_assistant_message(id,tenant_id,session_id,user_id,role,content,normalized_content) values(@id,@TenantId,@SessionId,@UserId,'USER',@question,lower(@question))",new{id=userMessage,command.TenantId,command.SessionId,command.UserId,question},cancellationToken:ct));
  await Audit(command.TenantId,command.UserId,"SMART_ASSISTANT_QUESTION_ASKED",userMessage,new{sessionId=command.SessionId},ct);
  var history=(await c.QueryAsync<ConversationRow>(new CommandDefinition("select role Role,left(content,2000) Content from ged.smart_assistant_message where tenant_id=@TenantId and session_id=@SessionId and user_id=@UserId and reg_status='A' order by created_at desc limit 6",command,cancellationToken:ct))).Reverse().Select(x=>new SmartAssistantConversationMessage(x.Role,x.Content)).ToArray();
  var resolved=intentResolver.Resolve(question,history);var found=await retrieval.RetrieveAsync(new(command.TenantId,question,8,command.UserId,command.SessionId,history,resolved,600),ct); var draft=await composer.ComposeAsync(new(question,found,resolved,history,found.Structured),ct); var answerId=Guid.NewGuid();
  await using var tx=await c.BeginTransactionAsync(ct);
  await c.ExecuteAsync(new CommandDefinition("insert into ged.smart_assistant_message(id,tenant_id,session_id,user_id,role,content,normalized_content,confidence,answer_status,payload_json) values(@id,@TenantId,@SessionId,@UserId,'ASSISTANT',@content,lower(@content),@confidence,@status,cast(@payload as jsonb))",new{id=answerId,command.TenantId,command.SessionId,command.UserId,content=LocalSmartAssistantRetrievalService.Mask(draft.Content),confidence=draft.Confidence,status=draft.Status,payload=JsonSerializer.Serialize(new{warnings=draft.Warnings,resolvedIntent=resolved.Intent,confidenceBand=draft.Confidence>=85?"HIGH":draft.Confidence>=70?"MEDIUM":draft.Confidence>=55?"LOW":"INSUFFICIENT",retrievalDurationMs=found.DurationMs,sourceCount=found.Evidence.Count})},tx,cancellationToken:ct));
  var citations=new List<SmartAssistantCitation>(); foreach(var e in found.Evidence){var id=Guid.NewGuid();await c.ExecuteAsync(new CommandDefinition("insert into ged.smart_assistant_citation(id,tenant_id,message_id,source_type,source_id,source_title,source_excerpt,source_url,confidence) values(@id,@TenantId,@messageId,@SourceType,@SourceId,@Title,@Excerpt,@Url,@Confidence)",new{id,command.TenantId,messageId=answerId,e.SourceType,e.SourceId,e.Title,e.Excerpt,e.Url,e.Confidence},tx,cancellationToken:ct));citations.Add(new(id,e.SourceType,e.SourceId,e.Title,e.Excerpt,e.Url,e.Confidence));}
  var actions=new List<SmartAssistantAction>(); foreach(var a in draft.Actions){var id=Guid.NewGuid();var safeUrl=SmartAssistantActionUrlPolicy.Normalize(a.Url);await c.ExecuteAsync(new CommandDefinition("insert into ged.smart_assistant_action_suggestion(id,tenant_id,message_id,action_type,title,description,target_type,target_id,target_url) values(@id,@TenantId,@messageId,@ActionType,@Title,@Description,@TargetType,@TargetId,@TargetUrl)",new{id,command.TenantId,messageId=answerId,a.ActionType,a.Title,a.Description,a.TargetType,a.TargetId,TargetUrl=safeUrl},tx,cancellationToken:ct));actions.Add(new(id,a.ActionType,a.Title,a.Description,"PENDING",safeUrl));}
  await c.ExecuteAsync(new CommandDefinition("update ged.smart_assistant_session set last_message_at=now() where id=@SessionId and tenant_id=@TenantId and user_id=@UserId",command,tx,cancellationToken:ct)); await tx.CommitAsync(ct);
  await Audit(command.TenantId,command.UserId,"SMART_ASSISTANT_ANSWER_CREATED",answerId,new{citations=citations.Count,actions=actions.Count},ct);
  foreach(var citation in citations)await Audit(command.TenantId,command.UserId,"SMART_ASSISTANT_CITATION_CREATED",citation.Id,new{messageId=answerId,citation.SourceType},ct);
  foreach(var action in actions)await Audit(command.TenantId,command.UserId,"SMART_ASSISTANT_ACTION_SUGGESTED",action.Id,new{messageId=answerId,action.ActionType},ct);
  return new(answerId,draft.Content,draft.Confidence,draft.Status,citations,actions,draft.Warnings);
 }
 public async Task<IReadOnlyList<SmartAssistantSessionItem>> ListSessionsAsync(Guid tenantId,Guid userId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var rows=await c.QueryAsync<SessionRow>(new CommandDefinition("select id as Id,title as Title,status as Status,created_at as CreatedAt,last_message_at as LastMessageAt from ged.smart_assistant_session where tenant_id=@tenantId and user_id=@userId and reg_status='A' order by coalesce(last_message_at,created_at) desc",new{tenantId,userId},cancellationToken:ct));return rows.Select(Map).ToArray();}
 public async Task<SmartAssistantSessionDetails?> GetSessionAsync(Guid tenantId,Guid userId,Guid sessionId,CancellationToken ct){await using var c=await db.OpenAsync(ct);var s=await c.QuerySingleOrDefaultAsync<SessionRow>(new CommandDefinition("select id as Id,title as Title,status as Status,created_at as CreatedAt,last_message_at as LastMessageAt from ged.smart_assistant_session where tenant_id=@tenantId and user_id=@userId and id=@sessionId and reg_status='A'",new{tenantId,userId,sessionId},cancellationToken:ct));if(s is null)return null;var rows=await c.QueryAsync<MessageRow>(new CommandDefinition("select id as Id,role as Role,content as Content,confidence as Confidence,answer_status as Status,created_at as CreatedAt from ged.smart_assistant_message where tenant_id=@tenantId and user_id=@userId and session_id=@sessionId and reg_status='A' order by created_at",new{tenantId,userId,sessionId},cancellationToken:ct));var messages=new List<SmartAssistantMessage>();foreach(var r in rows){var cs=await LoadCitations(c,tenantId,userId,r.Id,ct);var acts=(await c.QueryAsync<ActionRow>(new CommandDefinition("select a.id as Id,a.action_type as ActionType,a.title as Title,a.description as Description,a.status as Status,a.target_type as TargetType,a.target_url as TargetUrl from ged.smart_assistant_action_suggestion a join ged.smart_assistant_message m on m.id=a.message_id join ged.smart_assistant_session s on s.id=m.session_id where a.tenant_id=@tenantId and s.user_id=@userId and a.message_id=@messageId and a.reg_status='A'",new{tenantId,userId,messageId=r.Id},cancellationToken:ct))).Select(Map).ToArray();messages.Add(new(r.Id,r.Role,r.Content,r.Confidence,r.Status,r.CreatedAt,cs,acts));}return new(s.Id,s.Title,s.Status,s.CreatedAt,messages);}
 public async Task<IReadOnlyList<SmartAssistantCitation>> GetCitationsAsync(Guid tenantId,Guid userId,Guid messageId,CancellationToken ct){await using var c=await db.OpenAsync(ct);return await LoadCitations(c,tenantId,userId,messageId,ct);}
 public async Task ReviewActionAsync(Guid tenantId,Guid actionId,Guid userId,bool accept,string? notes,CancellationToken ct){var status=accept?"ACCEPTED":"REJECTED";await using var c=await db.OpenAsync(ct);var changed=await c.ExecuteAsync(new CommandDefinition("update ged.smart_assistant_action_suggestion a set status=@status,reviewed_by=@userId,reviewed_at=now(),review_notes=@notes from ged.smart_assistant_message m,ged.smart_assistant_session s where a.tenant_id=@tenantId and a.id=@actionId and a.status='PENDING' and m.id=a.message_id and s.id=m.session_id and s.tenant_id=@tenantId and s.user_id=@userId",new{status,userId,notes,tenantId,actionId},cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Ação não encontrada, já revisada ou pertence a outro usuário.");await Audit(tenantId,userId,$"SMART_ASSISTANT_ACTION_{status}",actionId,new{notes},ct);}
 private static async Task<IReadOnlyList<SmartAssistantCitation>> LoadCitations(System.Data.Common.DbConnection c,Guid tenantId,Guid userId,Guid messageId,CancellationToken ct)=>(await c.QueryAsync<CitationRow>(new CommandDefinition("select c.id as Id,c.source_type as SourceType,c.source_id as SourceId,c.source_title as Title,c.source_excerpt as Excerpt,c.source_url as Url,c.confidence as Confidence from ged.smart_assistant_citation c join ged.smart_assistant_message m on m.id=c.message_id join ged.smart_assistant_session s on s.id=m.session_id where c.tenant_id=@tenantId and s.user_id=@userId and c.message_id=@messageId and c.reg_status='A'",new{tenantId,userId,messageId},cancellationToken:ct))).Select(Map).ToArray();
 private Task Audit(Guid tenantId,Guid? userId,string action,Guid? id,object data,CancellationToken ct)=>audit.WriteAsync(tenantId,userId,action,"SMART_ASSISTANT",id,action,null,null,data,ct);
 private static SmartAssistantSessionItem Map(SessionRow x)=>new(x.Id,x.Title,x.Status,x.CreatedAt,x.LastMessageAt); private static SmartAssistantCitation Map(CitationRow x)=>new(x.Id,x.SourceType,x.SourceId,x.Title,x.Excerpt,x.Url,x.Confidence);private static SmartAssistantAction Map(ActionRow x)=>new(x.Id,x.ActionType,x.Title,x.Description,x.Status,SmartAssistantActionUrlPolicy.Normalize(x.TargetUrl));
 private sealed class SessionRow{public Guid Id{get;set;}public string Title{get;set;}="";public string Status{get;set;}="";public DateTimeOffset CreatedAt{get;set;}public DateTimeOffset? LastMessageAt{get;set;}}
 private sealed class MessageRow{public Guid Id{get;set;}public string Role{get;set;}="";public string Content{get;set;}="";public decimal Confidence{get;set;}public string Status{get;set;}="";public DateTimeOffset CreatedAt{get;set;}}
 private sealed class CitationRow{public Guid Id{get;set;}public string SourceType{get;set;}="";public Guid? SourceId{get;set;}public string Title{get;set;}="";public string Excerpt{get;set;}="";public string? Url{get;set;}public decimal Confidence{get;set;}}
 private sealed class ActionRow{public Guid Id{get;set;}public string ActionType{get;set;}="";public string Title{get;set;}="";public string? Description{get;set;}public string Status{get;set;}="";public string? TargetType{get;set;}public string? TargetUrl{get;set;}}
 private sealed class ConversationRow{public string Role{get;set;}="";public string Content{get;set;}="";}
}

public static class SmartAssistantActionUrlPolicy
{
 public static string? Normalize(string? url)=>!string.IsNullOrWhiteSpace(url)&&url.Length<=500&&url.StartsWith("/",StringComparison.Ordinal)&&!url.StartsWith("//",StringComparison.Ordinal)&&!url.Contains('\\')&&!url.Contains('\r')&&!url.Contains('\n')?url:null;
}
