using System.IO.Compression; using System.Security.Cryptography; using System.Text; using System.Text.Json; using InovaGed.Deployment; using Xunit;
namespace InovaGed.Deployment.Tool.Tests;
public sealed class ReleaseManifestTests { [Fact] public void DefaultsPreserveOfficialRuntimeContract(){var m=new ReleaseManifest();Assert.Equal("net8.0",m.TargetFramework);Assert.Equal("framework-dependent",m.RuntimeMode);Assert.Equal("inprocess",m.HostingModel);} }
public sealed class RollbackCompatibilityTests { [Theory][InlineData("4.1.22","4.1.20","4.1.24",true)][InlineData("4.2.0","4.1.20","4.1.24",false)]public void EnforcesSchemaRange(string c,string min,string max,bool expected)=>Assert.Equal(expected,RollbackCompatibility.IsCompatible(c,min,max)); }
public sealed class MigrationDeploymentSafetyTests { [Fact] public void DestructiveIsNeverAdditive()=>Assert.NotEqual(DeploymentSafety.Additive,DeploymentSafety.DestructiveBlocked); }
public sealed class PackageStructureTests { [Fact] public void MissingManifestIsRejected(){using var p=new TemporaryPackage(new Dictionary<string,string>{{"checksums.sha256",""}});Assert.Contains(PackageVerifier.Verify(p.Path).Issues,x=>x.Code=="REQUIRED_FILE_MISSING");} }
public sealed class PackageSecurityTests { [Fact] public void PrivateKeyIsRejected(){using var p=new TemporaryPackage(new Dictionary<string,string>{{"notes.txt","BEGIN PRIVATE KEY"},{"checksums.sha256",""}});Assert.Contains(PackageVerifier.Verify(p.Path).Issues,x=>x.Code=="SECRET_PATTERN");} }
public sealed class PackageChecksumTests { [Fact] public void AlteredFileIsRejected(){using var p=new TemporaryPackage(new Dictionary<string,string>{{"x.txt","changed"},{"checksums.sha256",new string('0',64)+"  x.txt"}});Assert.Contains(PackageVerifier.Verify(p.Path).Issues,x=>x.Code=="CHECKSUM_MISMATCH");} }
public sealed class DeploymentConfigurationTests { [Fact] public void AbsoluteWindowsPathIsRecognizedByContract()=>Assert.True(Path.IsPathFullyQualified(Path.GetFullPath("config.json"))); }
public sealed class IisConfigurationModelTests { [Fact] public void HealthEndpointsAreSeparate()=>Assert.NotEqual(new HealthEndpoints().Live,new HealthEndpoints().Ready); }
public sealed class DeploymentReportSanitizationTests { [Fact] public void IssuesNeverContainFileContents(){using var p=new TemporaryPackage(new Dictionary<string,string>{{"a.txt","Password=supersecret"},{"checksums.sha256",""}});Assert.DoesNotContain("supersecret",JsonSerializer.Serialize(PackageVerifier.Verify(p.Path)));} }
file sealed class TemporaryPackage:IDisposable { public string Path{get;}=System.IO.Path.GetTempFileName(); public TemporaryPackage(Dictionary<string,string> files){File.Delete(Path);using var z=ZipFile.Open(Path,ZipArchiveMode.Create);foreach(var f in files){var e=z.CreateEntry(f.Key);using var w=new StreamWriter(e.Open(),Encoding.UTF8);w.Write(f.Value);}}public void Dispose()=>File.Delete(Path); }
