using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.SystemHealth.Incidents;

namespace InovaGed.Infrastructure.SystemHealth.Incidents;

public sealed class SystemIncidentService(IDbConnectionFactory db) : ISystemIncidentService, IRouteHealthRecorder
{
    public async Task<Guid> RegisterAsync(SystemIncidentCreateCommand c,CancellationToken ct)
    {
        var signature=Hash(string.Join('|',c.IncidentType,c.ExceptionType,c.SqlState,c.Controller,c.Action,c.Path,c.DatabaseObject,Normalize(c.Message)));
        await using var cn=await db.OpenAsync(ct); await using var tx=await cn.BeginTransactionAsync(ct);
        var id=await cn.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from ged.system_incident where signature_hash=@signature and status in ('OPEN','IN_REVIEW') and (@TenantId is null or tenant_id=@TenantId) order by last_seen_at desc limit 1 for update",new{signature,c.TenantId},tx,cancellationToken:ct));
        var grouped=id.HasValue;
        if(grouped) await cn.ExecuteAsync(new CommandDefinition("update ged.system_incident set occurrence_count=occurrence_count+1,last_seen_at=now(),correlation_id=coalesce(@CorrelationId,correlation_id) where id=@id",new{id,c.CorrelationId},tx,cancellationToken:ct));
        else id=await cn.ExecuteScalarAsync<Guid>(new CommandDefinition("""
insert into ged.system_incident(tenant_id,correlation_id,incident_type,severity,signature_hash,title,message,technical_message,recommended_action,recommended_script,controller,action,path,http_method,sql_state,database_object,exception_type,stack_trace,payload_json)
values(@TenantId,@CorrelationId,@IncidentType,@Severity,@signature,@Title,@Message,@TechnicalMessage,@RecommendedAction,@RecommendedScript,@Controller,@Action,@Path,@HttpMethod,@SqlState,@DatabaseObject,@ExceptionType,@StackTrace,cast(@PayloadJson as jsonb)) returning id
""",new{c.TenantId,c.CorrelationId,c.IncidentType,c.Severity,signature,c.Title,c.Message,c.TechnicalMessage,c.RecommendedAction,c.RecommendedScript,c.Controller,c.Action,c.Path,c.HttpMethod,c.SqlState,c.DatabaseObject,c.ExceptionType,c.StackTrace,PayloadJson=Redact(c.PayloadJson)},tx,cancellationToken:ct));
        await cn.ExecuteAsync(new CommandDefinition("insert into ged.system_incident_event(incident_id,tenant_id,correlation_id,event_type,event_message) values(@id,@TenantId,@CorrelationId,@event,@message)",new{id,c.TenantId,c.CorrelationId,event=grouped?"OCCURRENCE":"CREATED",message=c.Title},tx,cancellationToken:ct));
        await tx.CommitAsync(ct); return id.Value;
    }
    public async Task<IReadOnlyList<SystemIncidentListItem>> ListAsync(SystemIncidentFilter f,CancellationToken ct){await using var c=await db.OpenAsync(ct);var rows=await c.QueryAsync<SystemIncidentListItem>(new CommandDefinition("""
select id,incident_type "IncidentType",severity,status,title,message,recommended_action "RecommendedAction",controller,action,path,correlation_id "CorrelationId",occurrence_count "OccurrenceCount",first_seen_at "FirstSeenAt",last_seen_at "LastSeenAt" from ged.system_incident where reg_status='A' and (@Type is null or incident_type=@Type) and (@Severity is null or severity=@Severity) and (@Status is null or status=@Status) and (@Controller is null or controller ilike '%'||@Controller||'%') and (@Action is null or action ilike '%'||@Action||'%') and (@Path is null or path ilike '%'||@Path||'%') and (@CorrelationId is null or correlation_id=@CorrelationId) and (@From is null or last_seen_at>=@From) and (@To is null or last_seen_at<=@To) and (@TenantId is null or tenant_id=@TenantId) order by last_seen_at desc limit @Limit
""",f,cancellationToken:ct));return rows.AsList();}
    public async Task<SystemIncidentDetails?> GetAsync(Guid id,CancellationToken ct){await using var c=await db.OpenAsync(ct);var row=await c.QuerySingleOrDefaultAsync<DetailRow>(new CommandDefinition("select *,incident_type IncidentType,technical_message TechnicalMessage,recommended_action RecommendedAction,recommended_script RecommendedScript,http_method HttpMethod,correlation_id CorrelationId,sql_state SqlState,database_object DatabaseObject,exception_type ExceptionType,stack_trace StackTrace,occurrence_count OccurrenceCount,first_seen_at FirstSeenAt,last_seen_at LastSeenAt,resolved_by ResolvedBy,resolved_at ResolvedAt,resolution_notes ResolutionNotes from ged.system_incident where id=@id and reg_status='A'",new{id},cancellationToken:ct));if(row is null)return null;var events=(await c.QueryAsync<SystemIncidentEvent>(new CommandDefinition("select id,event_type EventType,event_message EventMessage,occurred_at OccurredAt,correlation_id CorrelationId,user_name UserName from ged.system_incident_event where incident_id=@id order by occurred_at desc",new{id},cancellationToken:ct))).AsList();return row.ToModel(events);}
    public Task ResolveAsync(Guid id,Guid userId,string notes,CancellationToken ct)=>SetStatus(id,userId,IncidentStatus.Resolved,notes,ct);
    public Task IgnoreAsync(Guid id,Guid userId,string reason,CancellationToken ct)=>SetStatus(id,userId,IncidentStatus.Ignored,reason,ct);
    private async Task SetStatus(Guid id,Guid user,string status,string notes,CancellationToken ct){await using var c=await db.OpenAsync(ct);await c.ExecuteAsync(new CommandDefinition("update ged.system_incident set status=@status,resolved_by=@user,resolved_at=now(),resolution_notes=@notes where id=@id; insert into ged.system_incident_event(incident_id,event_type,event_message,user_id) values(@id,@status,@notes,@user)",new{id,user,status,notes},cancellationToken:ct));}
    public async Task RecordAsync(RouteHealthRecordCommand x,CancellationToken ct){await using var c=await db.OpenAsync(ct);await c.ExecuteAsync(new CommandDefinition("insert into ged.route_health_snapshot(route_path,http_method,expected_status,actual_status,success,duration_ms,error_message,correlation_id,payload_json) values(@RoutePath,@HttpMethod,@ExpectedStatus,@ActualStatus,@Success,@DurationMs,@ErrorMessage,@CorrelationId,cast(@PayloadJson as jsonb))",x with{PayloadJson=Redact(x.PayloadJson)},cancellationToken:ct));}
    public async Task<IReadOnlyList<RouteHealthListItem>> ListAsync(CancellationToken ct){await using var c=await db.OpenAsync(ct);return (await c.QueryAsync<RouteHealthListItem>(new CommandDefinition("select id,route_path RoutePath,http_method HttpMethod,expected_status ExpectedStatus,actual_status ActualStatus,success,duration_ms DurationMs,checked_at CheckedAt,error_message ErrorMessage,correlation_id CorrelationId from ged.route_health_snapshot where reg_status='A' order by checked_at desc limit 250",cancellationToken:ct))).AsList();}
    private static string Normalize(string s)=>Regex.Replace(s.ToLowerInvariant(),@"\b[0-9a-f]{8,}\b|\b\d+\b","#");private static string Hash(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s))).ToLowerInvariant();
    private static string? Redact(string? s)=>s is null?null:Regex.Replace(s,"(?i)(password|token|secret|connectionstring)\\s*[:=]\\s*[^,;}]+","$1=***");
    private sealed class DetailRow { public Guid Id{get;set;} public string IncidentType{get;set;}="";public string Severity{get;set;}="";public string Status{get;set;}="";public string Title{get;set;}="";public string Message{get;set;}="";public string? TechnicalMessage{get;set;}public string? RecommendedAction{get;set;}public string? RecommendedScript{get;set;}public string? Controller{get;set;}public string? Action{get;set;}public string? Path{get;set;}public string? HttpMethod{get;set;}public string? CorrelationId{get;set;}public string? SqlState{get;set;}public string? DatabaseObject{get;set;}public string? ExceptionType{get;set;}public string? StackTrace{get;set;}public int OccurrenceCount{get;set;}public DateTimeOffset FirstSeenAt{get;set;}public DateTimeOffset LastSeenAt{get;set;}public Guid? ResolvedBy{get;set;}public DateTimeOffset? ResolvedAt{get;set;}public string? ResolutionNotes{get;set;} public SystemIncidentDetails ToModel(IReadOnlyList<SystemIncidentEvent> e)=>new(Id,IncidentType,Severity,Status,Title,Message,TechnicalMessage,RecommendedAction,RecommendedScript,Controller,Action,Path,HttpMethod,CorrelationId,SqlState,DatabaseObject,ExceptionType,StackTrace,OccurrenceCount,FirstSeenAt,LastSeenAt,ResolvedBy,ResolvedAt,ResolutionNotes,e);}
}
