[CmdletBinding(SupportsShouldProcess)]param([Parameter(Mandatory)][ValidateSet('Validate','Install','Update','Rollback','Status')][string]$Mode,[string]$PackagePath,[Parameter(Mandatory)][string]$ConfigurationPath,[string]$ReleaseId)
$ErrorActionPreference='Stop'; Import-Module (Join-Path $PSScriptRoot 'InovaGed.IisDeployment.psm1') -Force
$id=[guid]::NewGuid().ToString('n'); $events=@('DEPLOYMENT_STARTED'); try{$c=Read-InovaGedConfiguration $ConfigurationPath
 if($Mode-eq'Status'){Import-Module WebAdministration; [pscustomobject]@{site=$c.siteName;physicalPath=(Get-ItemProperty "IIS:\Sites\$($c.siteName)").physicalPath};exit 0}
 if($Mode-eq'Validate'){ $v=Test-InovaGedServer $c $PackagePath; $dir=Split-Path $ConfigurationPath; $v|ConvertTo-Json -Depth 8|Set-Content (Join-Path $dir 'deployment-validation-report.json'); $v|Format-List|Out-String|Set-Content (Join-Path $dir 'deployment-validation-report.txt'); if(-not$v.ready){exit 2};if($v.warnings){exit 1};exit 0 }
 if($Mode-eq'Rollback'){if(!$ReleaseId){throw 'ReleaseId obrigatório.'};$target=Join-Path $c.releasesRoot $ReleaseId;if(!(Test-Path $target)){throw 'Release anterior ausente.'};$events+='DEPLOYMENT_ROLLBACK_STARTED';Switch-InovaGedRelease $c $target -WhatIf:$WhatIfPreference;if(-not$WhatIfPreference-and-not(Invoke-InovaGedHealthCheck $c.healthCheckBaseUrl $c.deploymentTimeoutSeconds)){throw 'Health check falhou após rollback.'};$events+='DEPLOYMENT_ROLLBACK_COMPLETED'}
 else {Test-InovaGedPackage $PackagePath (Join-Path $PSScriptRoot 'InovaGed.Deployment.Tool.dll');$events+='DEPLOYMENT_PACKAGE_VERIFIED';$zip=Get-Item $PackagePath;$release=$zip.BaseName-replace '^InovaGED-','';$target=Join-Path $c.releasesRoot $release;if(Test-Path $target){throw 'Release já extraída.'};if($PSCmdlet.ShouldProcess($target,'Extrair release isolada')){New-Item $target -ItemType Directory -Force|Out-Null;Expand-Archive $PackagePath $target};$events+='DEPLOYMENT_CUTOVER_STARTED';Switch-InovaGedRelease $c (Join-Path $target 'app') -WhatIf:$WhatIfPreference;if(-not$WhatIfPreference-and-not(Invoke-InovaGedHealthCheck $c.healthCheckBaseUrl $c.deploymentTimeoutSeconds)){throw 'Health check falhou; efetue rollback binário.'};$events+='DEPLOYMENT_COMPLETED'}
 if(-not$WhatIfPreference){Write-InovaGedReport $c $id $Mode 'Succeeded' $events $ReleaseId|Out-Null};exit 0
}catch{Write-Error (Protect-InovaGedText $_.Exception.Message);exit 4}
