using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.PhysicalArchive.Productivity;

namespace InovaGed.Infrastructure.PhysicalArchive;

public sealed class ArchiveProductivityService(IDbConnectionFactory factory) : IArchiveServiceCatalogService, IArchiveProductivityService, IArchiveBillingService
{
    public async Task<IReadOnlyList<ArchiveServiceCatalogItem>> ListAsync(Guid tenantId,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return (await db.QueryAsync<ArchiveServiceCatalogItem>(new CommandDefinition("select id,code,name,description,unit,unit_price UnitPrice,default_ust_quantity DefaultUstQuantity,calculation_rule CalculationRule,is_active IsActive,display_order DisplayOrder from ged.archive_service_catalog where reg_status='A' and (tenant_id is null or tenant_id=@tenantId) order by display_order,name",new{tenantId},cancellationToken:ct))).AsList();}
    public async Task<Guid> CreateAsync(Guid t,ArchiveServiceCatalogCommand c,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var id=Guid.NewGuid();await db.ExecuteAsync(new CommandDefinition("insert into ged.archive_service_catalog(id,tenant_id,code,name,description,unit,unit_price,default_ust_quantity,calculation_rule,display_order) values(@id,@t,upper(@Code),@Name,@Description,@Unit,@UnitPrice,@DefaultUstQuantity,@CalculationRule,@DisplayOrder); insert into ged.archive_productivity_audit(tenant_id,entity_type,entity_id,action,after_snapshot) values(@t,'CATALOG',@id,'CREATED',to_jsonb(@Name::text))",new{id,t,c.Code,c.Name,c.Description,c.Unit,c.UnitPrice,c.DefaultUstQuantity,c.CalculationRule,c.DisplayOrder},cancellationToken:ct));return id;}
    public async Task UpdateAsync(Guid t,Guid id,ArchiveServiceCatalogCommand c,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var n=await db.ExecuteAsync(new CommandDefinition("with old as (select to_jsonb(x) snapshot from ged.archive_service_catalog x where tenant_id=@t and id=@id) update ged.archive_service_catalog set code=upper(@Code),name=@Name,description=@Description,unit=@Unit,unit_price=@UnitPrice,default_ust_quantity=@DefaultUstQuantity,calculation_rule=@CalculationRule,display_order=@DisplayOrder,updated_at=now() where tenant_id=@t and id=@id and reg_status='A'; insert into ged.archive_productivity_audit(tenant_id,entity_type,entity_id,action,notes) values(@t,'CATALOG',@id,'UPDATED','Catálogo e valor unitário alterados')",new{id,t,c.Code,c.Name,c.Description,c.Unit,c.UnitPrice,c.DefaultUstQuantity,c.CalculationRule,c.DisplayOrder},cancellationToken:ct));if(n==0)throw new KeyNotFoundException();}
    public Task ActivateAsync(Guid t,Guid id,CancellationToken ct)=>Toggle(t,id,true,ct); public Task DeactivateAsync(Guid t,Guid id,CancellationToken ct)=>Toggle(t,id,false,ct);
    async Task Toggle(Guid t,Guid id,bool active,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition("update ged.archive_service_catalog set is_active=@active,updated_at=now() where tenant_id=@t and id=@id",new{t,id,active},cancellationToken:ct));}
    public async Task<Guid> RegisterAsync(ArchiveProductivityRegisterCommand c,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);if(await IsLocked(db,c.TenantId,c.CompetenceMonth,ct,tx))throw new InvalidOperationException("A competência fechada bloqueia alterações para preservar a integridade da medição.");var s=await db.QuerySingleOrDefaultAsync<Service>(new CommandDefinition("select unit_price UnitPrice,default_ust_quantity DefaultUstQuantity,calculation_rule CalculationRule from ged.archive_service_catalog where id=@ServiceCatalogId and (tenant_id is null or tenant_id=@TenantId) and is_active and reg_status='A'",c,tx,cancellationToken:ct))??throw new KeyNotFoundException("Serviço não encontrado.");var ust=s.CalculationRule==ArchiveCalculationRule.Manual?(c.UstQuantity??0):c.Quantity*s.DefaultUstQuantity;var id=Guid.NewGuid();await db.ExecuteAsync(new CommandDefinition("insert into ged.archive_productivity_entry(id,tenant_id,service_catalog_id,competence_month,performed_at,performed_by,team_id,sector_id,source_type,source_id,subject_type,subject_id,box_id,document_id,work_order_id,inventory_session_id,label_print_history_id,quantity,ust_quantity,unit_price,total_amount,status,notes,created_by) values(@id,@TenantId,@ServiceCatalogId,@CompetenceMonth,@PerformedAt,@UserId,@TeamId,@SectorId,@SourceType,@SourceId,@SubjectType,@SubjectId,@BoxId,@DocumentId,@WorkOrderId,@InventorySessionId,@LabelPrintHistoryId,@Quantity,@ust,@price,@total,'SUBMITTED',@Notes,@UserId) on conflict do nothing",new{id,c.TenantId,c.ServiceCatalogId,CompetenceMonth=c.CompetenceMonth.ToDateTime(TimeOnly.MinValue),PerformedAt=c.PerformedAt??DateTimeOffset.UtcNow,c.UserId,c.TeamId,c.SectorId,c.SourceType,c.SourceId,c.SubjectType,c.SubjectId,c.BoxId,c.DocumentId,c.WorkOrderId,c.InventorySessionId,c.LabelPrintHistoryId,c.Quantity,ust,price=s.UnitPrice,total=ust*s.UnitPrice,c.Notes},tx,cancellationToken:ct));await Audit(db,tx,c.TenantId,id,"ENTRY_REGISTERED",c.UserId,ct);await tx.CommitAsync(ct);return id;}
    public Task RegisterFromWorkOrderAsync(Guid t,Guid id,Guid u,CancellationToken ct)=>Automatic(t,"ORDEM_SERVICO_EXECUTADA","WORK_ORDER",id,u,"select 1::numeric",ct,work:id);
    public Task RegisterFromLabelPrintAsync(Guid t,Guid id,Guid u,CancellationToken ct)=>Automatic(t,"IMPRESSAO_ETIQUETA_PADRAO","LABEL_PRINT",id,u,"select 1::numeric",ct,label:id);
    public Task RegisterFromInventoryAsync(Guid t,Guid id,Guid u,CancellationToken ct)=>Automatic(t,"INVENTARIO_ETIQUETA","INVENTORY_SESSION",id,u,"select greatest(count(*),1)::numeric from ged.label_inventory_item where tenant_id=@t and session_id=@id and reg_status='A'",ct,inventory:id);
    async Task Automatic(Guid t,string code,string type,Guid source,Guid user,string quantitySql,CancellationToken ct,Guid?work=null,Guid?label=null,Guid?inventory=null){await using var db=await factory.OpenAsync(ct);var service=await db.ExecuteScalarAsync<Guid?>(new CommandDefinition("select id from ged.archive_service_catalog where code=@code and (tenant_id is null or tenant_id=@t) and is_active order by tenant_id nulls last limit 1",new{t,code},cancellationToken:ct));if(service is null)return;var q=await db.ExecuteScalarAsync<decimal>(new CommandDefinition(quantitySql,new{t,id=source},cancellationToken:ct));await RegisterAsync(new(t,service.Value,user,DateOnly.FromDateTime(DateTime.UtcNow),q,SourceType:type,SourceId:source,WorkOrderId:work,LabelPrintHistoryId:label,InventorySessionId:inventory),ct);}
    public async Task<IReadOnlyList<ArchiveProductivityEntryItem>> ListAsync(Guid t,ArchiveProductivityFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<ArchiveProductivityEntryItem>(new CommandDefinition("select e.id,e.service_catalog_id ServiceCatalogId,s.code ServiceCode,s.name ServiceName,e.competence_month CompetenceMonth,e.performed_at PerformedAt,e.performed_by PerformedBy,e.source_type SourceType,e.source_id SourceId,e.quantity,e.ust_quantity UstQuantity,e.unit_price UnitPrice,e.total_amount TotalAmount,e.status,e.notes,e.rejection_reason RejectionReason from ged.archive_productivity_entry e join ged.archive_service_catalog s on s.id=e.service_catalog_id where e.tenant_id=@t and e.reg_status='A' and (@month is null or e.competence_month=@month) and (coalesce(@Status,'')='' or e.status=@Status) and (@PerformedBy is null or e.performed_by=@PerformedBy) and (coalesce(@SourceType,'')='' or e.source_type=@SourceType) order by e.performed_at desc",new{t,month=f.CompetenceMonth?.ToDateTime(TimeOnly.MinValue),f.Status,f.PerformedBy,f.SourceType},cancellationToken:ct))).AsList();}
    public Task ApproveAsync(Guid t,Guid id,Guid u,CancellationToken ct)=>Review(t,id,u,true,null,ct);public Task RejectAsync(Guid t,Guid id,Guid u,string reason,CancellationToken ct)=>Review(t,id,u,false,reason,ct);
    async Task Review(Guid t,Guid id,Guid u,bool approve,string? reason,CancellationToken ct){if(!approve&&string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Informe o motivo da rejeição.");await using var db=await factory.OpenAsync(ct);var n=await db.ExecuteAsync(new CommandDefinition(approve?"update ged.archive_productivity_entry set status='APPROVED',approved_by=@u,approved_at=now() where tenant_id=@t and id=@id and reg_status='A' and status in('DRAFT','SUBMITTED') and coalesce(created_by,'00000000-0000-0000-0000-000000000000')<>@u":"update ged.archive_productivity_entry set status='REJECTED',rejected_by=@u,rejected_at=now(),rejection_reason=@reason where tenant_id=@t and id=@id and reg_status='A' and status in('DRAFT','SUBMITTED')",new{t,id,u,reason},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Apontamento inválido, bloqueado ou aprovação própria não permitida.");}
    public async Task<ArchiveBillingPreview> PreviewAsync(Guid t,DateOnly month,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var lines=(await db.QueryAsync<ArchiveBillingLine>(new CommandDefinition("select s.id ServiceCatalogId,s.code,s.name Service,sum(e.quantity) Quantity,sum(e.ust_quantity) UstQuantity,case when sum(e.ust_quantity)=0 then 0 else sum(e.total_amount)/sum(e.ust_quantity) end UnitPrice,sum(e.total_amount) TotalAmount,count(*) Entries from ged.archive_productivity_entry e join ged.archive_service_catalog s on s.id=e.service_catalog_id where e.tenant_id=@t and e.competence_month=@m and e.reg_status='A' and e.status<>'CANCELLED' group by s.id,s.code,s.name order by s.name",new{t,m=month.ToDateTime(TimeOnly.MinValue)},cancellationToken:ct))).AsList();var status=await db.ExecuteScalarAsync<string?>(new CommandDefinition("select status from ged.archive_billing_period where tenant_id=@t and competence_month=@m and reg_status='A'",new{t,m=month.ToDateTime(TimeOnly.MinValue)},cancellationToken:ct))??ArchiveBillingPeriodStatus.Open;var pending=await db.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from ged.archive_productivity_entry where tenant_id=@t and competence_month=@m and reg_status='A' and status<>'APPROVED'",new{t,m=month.ToDateTime(TimeOnly.MinValue)},cancellationToken:ct));return new(month,status,lines.Sum(x=>x.Entries),lines.Sum(x=>x.Quantity),lines.Sum(x=>x.UstQuantity),lines.Sum(x=>x.TotalAmount),pending,lines);}
    public async Task<Guid> OpenPeriodAsync(Guid t,DateOnly m,Guid u,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return await db.ExecuteScalarAsync<Guid>(new CommandDefinition("insert into ged.archive_billing_period(tenant_id,competence_month,opened_by) values(@t,@m,@u) on conflict(tenant_id,competence_month) where reg_status='A' do update set status='OPEN' returning id",new{t,m=m.ToDateTime(TimeOnly.MinValue),u},cancellationToken:ct));}
    public async Task ClosePeriodAsync(Guid t,DateOnly m,Guid u,string? notes,CancellationToken ct){var p=await PreviewAsync(t,m,ct);if(p.Pending>0&&string.IsNullOrWhiteSpace(notes))throw new InvalidOperationException("Revise os itens pendentes antes de fechar a competência ou informe uma justificativa administrativa.");await SavePeriod(t,m,u,notes,"CLOSED",p,ct);}
    public async Task ApprovePeriodAsync(Guid t,DateOnly m,Guid u,CancellationToken ct){var p=await PreviewAsync(t,m,ct);if(p.Status!="CLOSED")throw new InvalidOperationException("Somente uma competência fechada pode ser aprovada.");await SavePeriod(t,m,u,null,"APPROVED",p,ct);}
    async Task SavePeriod(Guid t,DateOnly m,Guid u,string? notes,string status,ArchiveBillingPreview p,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition("insert into ged.archive_billing_period(tenant_id,competence_month,status,total_entries,total_quantity,total_ust,total_amount,opened_by,closed_by,closed_at,approved_by,approved_at,notes) values(@t,@m,@status,@TotalEntries,@TotalQuantity,@TotalUst,@TotalAmount,@u,case when @status='CLOSED' then @u end,case when @status='CLOSED' then now() end,case when @status='APPROVED' then @u end,case when @status='APPROVED' then now() end,@notes) on conflict(tenant_id,competence_month) where reg_status='A' do update set status=@status,total_entries=@TotalEntries,total_quantity=@TotalQuantity,total_ust=@TotalUst,total_amount=@TotalAmount,closed_by=case when @status='CLOSED' then @u else archive_billing_period.closed_by end,closed_at=case when @status='CLOSED' then now() else archive_billing_period.closed_at end,approved_by=case when @status='APPROVED' then @u end,approved_at=case when @status='APPROVED' then now() end,notes=coalesce(@notes,archive_billing_period.notes)",new{t,m=m.ToDateTime(TimeOnly.MinValue),u,notes,status,p.TotalEntries,p.TotalQuantity,p.TotalUst,p.TotalAmount},cancellationToken:ct));}
    static async Task<bool> IsLocked(System.Data.Common.DbConnection db,Guid t,DateOnly m,CancellationToken ct,System.Data.Common.DbTransaction tx)=>await db.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from ged.archive_billing_period where tenant_id=@t and competence_month=@m and status in('CLOSED','APPROVED') and reg_status='A')",new{t,m=m.ToDateTime(TimeOnly.MinValue)},tx,cancellationToken:ct));
    static Task Audit(System.Data.Common.DbConnection db,System.Data.Common.DbTransaction tx,Guid t,Guid id,string action,Guid u,CancellationToken ct)=>db.ExecuteAsync(new CommandDefinition("insert into ged.archive_productivity_audit(tenant_id,entity_type,entity_id,action,performed_by) values(@t,'ENTRY',@id,@action,@u)",new{t,id,action,u},tx,cancellationToken:ct));
    sealed class Service{public decimal UnitPrice{get;set;}public decimal DefaultUstQuantity{get;set;}public string CalculationRule{get;set;}="";}
}
