using System.Data.Common;
using System.Text.Json;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.PhysicalArchive.Reconciliation;

namespace InovaGed.Infrastructure.PhysicalArchive;

public sealed class ArchiveReconciliationService(IDbConnectionFactory factory) : IArchiveReconciliationService,IArchiveReconciliationEngine,IArchiveReconciliationFixService
{
 public Task<Guid> StartRunAsync(ArchiveReconciliationStartCommand c,CancellationToken ct)=>c.InventorySessionId is Guid inventory
  ?RunInventoryReconciliationAsync(c.TenantId,inventory,c.UserId,ct).ContinueWith(x=>x.Result.RunId,ct,TaskContinuationOptions.ExecuteSynchronously,TaskScheduler.Default)
  :RunFullDiagnosisAsync(c.TenantId,c.UserId,ct).ContinueWith(x=>x.Result.RunId,ct,TaskContinuationOptions.ExecuteSynchronously,TaskScheduler.Default);

 public async Task<ArchiveReconciliationResult> RunFullDiagnosisAsync(Guid tenantId,Guid userId,CancellationToken ct)=>await Run(tenantId,userId,"MANUAL",null,FullDiagnosisSql,ct);
 public async Task<ArchiveReconciliationResult> RunInventoryReconciliationAsync(Guid tenantId,Guid inventorySessionId,Guid userId,CancellationToken ct)=>await Run(tenantId,userId,"INVENTORY",inventorySessionId,InventorySql,ct);

 private async Task<ArchiveReconciliationResult> Run(Guid tenantId,Guid userId,string source,Guid? inventorySessionId,string diagnosisSql,CancellationToken ct)
 {
  await using var db=await factory.OpenAsync(ct);await using var tx=await ((DbConnection)db).BeginTransactionAsync(ct);
  var id=Guid.NewGuid();var number=$"SAN-{DateTime.UtcNow:yyyyMMddHHmmss}-{id.ToString("N")[..6].ToUpperInvariant()}";
  await db.ExecuteAsync(new CommandDefinition("insert into ged.archive_reconciliation_run(id,tenant_id,run_number,source,inventory_session_id,started_by) values(@id,@tenantId,@number,@source,@inventorySessionId,@userId)",new{id,tenantId,number,source,inventorySessionId,userId},tx,cancellationToken:ct));
  try
  {
   await db.ExecuteAsync(new CommandDefinition(diagnosisSql,new{tenantId,runId=id,inventorySessionId},tx,cancellationToken:ct));
   var totals=await db.QuerySingleAsync<(int Checked,int Issues,int Critical,int High,int Medium,int Low)>(new CommandDefinition("""
select (select count(*)::int from ged.box where tenant_id=@tenantId and reg_status='A')+(select count(*)::int from ged.document where tenant_id=@tenantId and reg_status='A')+(select count(*)::int from ged.label_print_history where tenant_id=@tenantId and reg_status='A') Checked,count(*)::int Issues,count(*) filter(where severity='CRITICAL')::int Critical,count(*) filter(where severity='HIGH')::int High,count(*) filter(where severity='MEDIUM')::int Medium,count(*) filter(where severity='LOW')::int Low from ged.archive_reconciliation_issue where run_id=@runId
""",new{tenantId,runId=id},tx,cancellationToken:ct));
   await db.ExecuteAsync(new CommandDefinition("update ged.archive_reconciliation_run set status='COMPLETED',finished_at=now(),total_checked=@Checked,total_issues=@Issues,total_critical=@Critical,total_high=@High,total_medium=@Medium,total_low=@Low where id=@id and tenant_id=@tenantId",new{totals.Checked,totals.Issues,totals.Critical,totals.High,totals.Medium,totals.Low,id,tenantId},tx,cancellationToken:ct));
   await tx.CommitAsync(ct);return new(id,totals.Checked,totals.Issues,totals.Critical,totals.High,totals.Medium,totals.Low);
  }
  catch(Exception ex){await db.ExecuteAsync(new CommandDefinition("update ged.archive_reconciliation_run set status='FAILED',finished_at=now(),error_message=@message where id=@id",new{id,message=ex.Message},tx,cancellationToken:ct));await tx.CommitAsync(ct);throw;}
 }

 public async Task<ArchiveReconciliationDashboard> GetDashboardAsync(Guid tenantId,CancellationToken ct)
 {
  await using var db=await factory.OpenAsync(ct);var row=await db.QuerySingleAsync<DashboardRow>(new CommandDefinition("""
select (select count(*) from ged.box where tenant_id=@tenantId and reg_status='A') Boxes,(select count(*) from ged.document where tenant_id=@tenantId and reg_status='A') Documents,(select count(*) from ged.label_print_history where tenant_id=@tenantId and reg_status='A') Labels,count(*) filter(where status in ('OPEN','IN_REVIEW')) OpenIssues,count(*) filter(where status='FIXED') FixedIssues,count(*) filter(where status in ('OPEN','IN_REVIEW') and severity='CRITICAL') CriticalIssues,count(*) filter(where status='IGNORED') IgnoredIssues,count(*) filter(where status in ('OPEN','IN_REVIEW') and issue_type='LOCATION_MISMATCH') LocationMismatches,count(*) filter(where status in ('OPEN','IN_REVIEW') and issue_type in ('BOX_WITHOUT_LABEL','DOCUMENT_WITHOUT_LABEL')) WithoutLabel,count(*) filter(where status in ('OPEN','IN_REVIEW') and issue_type='LABEL_WITHOUT_SUBJECT') OrphanLabels,coalesce(sum(case severity when 'CRITICAL' then 5 when 'HIGH' then 3 when 'MEDIUM' then 2 else 1 end) filter(where status in ('OPEN','IN_REVIEW')),0) Weighted from ged.archive_reconciliation_issue where tenant_id=@tenantId and reg_status='A'
""",new{tenantId},cancellationToken:ct));var checkedTotal=Math.Max(1,row.Boxes+row.Documents+row.Labels);var quality=Math.Max(0,100m-(row.Weighted*100m/checkedTotal));return new(row.Boxes,row.Documents,row.Labels,row.OpenIssues,row.FixedIssues,row.CriticalIssues,row.IgnoredIssues,row.LocationMismatches,row.WithoutLabel,row.OrphanLabels,Math.Round(quality,1),await ListRunsAsync(tenantId,new(),ct));
 }
 public async Task<IReadOnlyList<ArchiveReconciliationRunItem>> ListRunsAsync(Guid t,ArchiveReconciliationRunFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<ArchiveReconciliationRunItem>(new CommandDefinition("select id,run_number RunNumber,source,status,total_checked TotalChecked,total_issues TotalIssues,total_critical TotalCritical,total_high TotalHigh,total_medium TotalMedium,total_low TotalLow,started_at StartedAt,finished_at FinishedAt from ged.archive_reconciliation_run where tenant_id=@t and reg_status='A' and (coalesce(@Status,'')='' or status=@Status) and (coalesce(@Source,'')='' or source=@Source) order by started_at desc limit 100",new{t,f.Status,f.Source},cancellationToken:ct))).AsList();}
 public async Task<IReadOnlyList<ArchiveReconciliationIssueItem>> ListIssuesAsync(Guid t,ArchiveReconciliationIssueFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<ArchiveReconciliationIssueItem>(new CommandDefinition("select id,run_id RunId,issue_type IssueType,severity,subject_type SubjectType,subject_id SubjectId,control_number ControlNumber,title,description,suggestion,proposed_action ProposedAction,status,created_at CreatedAt from ged.archive_reconciliation_issue where tenant_id=@t and reg_status='A' and (coalesce(@Status,'')='' or status=@Status) and (coalesce(@Severity,'')='' or severity=@Severity) and (coalesce(@IssueType,'')='' or issue_type=@IssueType) and (@RunId is null or run_id=@RunId) and (coalesce(@Search,'')='' or control_number ilike '%'||@Search||'%' or title ilike '%'||@Search||'%') order by case severity when 'CRITICAL' then 1 when 'HIGH' then 2 when 'MEDIUM' then 3 else 4 end,created_at desc limit 2000",new{t,f.Status,f.Severity,f.IssueType,f.RunId,f.Search},cancellationToken:ct))).AsList();}
 public async Task<ArchiveReconciliationRunDetails?> GetRunAsync(Guid t,Guid id,CancellationToken ct){var runs=await ListRunsAsync(t,new(),ct);var run=runs.FirstOrDefault(x=>x.Id==id);return run is null?null:new(run,await ListIssuesAsync(t,new(RunId:id),ct));}
 public async Task<ArchiveReconciliationIssueDetails?> GetIssueAsync(Guid t,Guid id,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var x=await db.QuerySingleOrDefaultAsync<IssueDetailsRow>(new CommandDefinition("select id,run_id RunId,issue_type IssueType,severity,subject_type SubjectType,subject_id SubjectId,control_number ControlNumber,title,description,suggestion,proposed_action ProposedAction,status,created_at CreatedAt,expected_value ExpectedValue,found_value FoundValue,proposed_payload::text ProposedPayload,resolution_notes ResolutionNotes,resolved_at ResolvedAt from ged.archive_reconciliation_issue where tenant_id=@t and id=@id and reg_status='A'",new{t,id},cancellationToken:ct));return x is null?null:new(new(x.Id,x.RunId,x.IssueType,x.Severity,x.SubjectType,x.SubjectId,x.ControlNumber,x.Title,x.Description,x.Suggestion,x.ProposedAction,x.Status,x.CreatedAt),x.ExpectedValue,x.FoundValue,x.ProposedPayload,x.ResolutionNotes,x.ResolvedAt);}

 public Task IgnoreIssueAsync(Guid t,Guid id,Guid u,string reason,CancellationToken ct)=>Resolve(t,id,u,reason,"IGNORED","RECONCILIATION_ISSUE_IGNORED",ct);
 public Task RejectSuggestionAsync(Guid t,Guid id,Guid u,string reason,CancellationToken ct)=>Resolve(t,id,u,reason,"REJECTED","RECONCILIATION_SUGGESTION_REJECTED",ct);
 private async Task Resolve(Guid t,Guid id,Guid u,string reason,string status,string eventType,CancellationToken ct){if(string.IsNullOrWhiteSpace(reason))throw new InvalidOperationException("Informe uma justificativa para fins de auditoria.");await using var db=await factory.OpenAsync(ct);await using var tx=await ((DbConnection)db).BeginTransactionAsync(ct);var issue=await Load(db,t,id,tx,ct);if(issue is null||issue.Status is not ("OPEN" or "IN_REVIEW"))throw new InvalidOperationException("Inconsistência não encontrada ou já encerrada.");await db.ExecuteAsync(new CommandDefinition("update ged.archive_reconciliation_issue set status=@status,resolved_by=@u,resolved_at=now(),resolution_notes=@reason where tenant_id=@t and id=@id",new{status,u,reason,t,id},tx,cancellationToken:ct));await Custody(db,issue,t,u,eventType,reason,tx,ct);await tx.CommitAsync(ct);}
 public async Task ApplyFixAsync(Guid t,Guid id,Guid u,string? notes,CancellationToken ct)
 {
  await using var db=await factory.OpenAsync(ct);await using var tx=await ((DbConnection)db).BeginTransactionAsync(ct);var issue=await Load(db,t,id,tx,ct);if(issue is null||issue.Status is not ("OPEN" or "IN_REVIEW"))throw new InvalidOperationException("Inconsistência não encontrada ou já encerrada.");string before,after;
  if(issue.IssueType==ArchiveReconciliationIssueType.MultipleActiveLabels&&issue.SubjectId is Guid subject){before=JsonSerializer.Serialize(await db.QueryAsync<object>(new CommandDefinition("select id,printed_at,reg_status from ged.label_print_history where tenant_id=@t and label_subject_type=@SubjectType and label_subject_id=@subject and reg_status='A' order by printed_at desc",new{t,issue.SubjectType,subject},tx,cancellationToken:ct)));await db.ExecuteAsync(new CommandDefinition("update ged.label_print_history set reg_status='I' where tenant_id=@t and label_subject_type=@SubjectType and label_subject_id=@subject and reg_status='A' and id<>(select id from ged.label_print_history where tenant_id=@t and label_subject_type=@SubjectType and label_subject_id=@subject and reg_status='A' order by printed_at desc limit 1)",new{t,issue.SubjectType,subject},tx,cancellationToken:ct));after=JsonSerializer.Serialize(await db.QueryAsync<object>(new CommandDefinition("select id,printed_at,reg_status from ged.label_print_history where tenant_id=@t and label_subject_type=@SubjectType and label_subject_id=@subject order by printed_at desc",new{t,issue.SubjectType,subject},tx,cancellationToken:ct)));}
  else if(issue.IssueType==ArchiveReconciliationIssueType.LocationMismatch&&issue.SubjectType=="BOX"&&issue.SubjectId is Guid box&&!string.IsNullOrWhiteSpace(issue.FoundValue)){before=JsonSerializer.Serialize(await db.QuerySingleAsync<object>(new CommandDefinition("select id,location_id from ged.box where tenant_id=@t and id=@box",new{t,box},tx,cancellationToken:ct)));var changed=await db.ExecuteAsync(new CommandDefinition("update ged.box b set location_id=p.id,updated_at=now() from ged.physical_location p where b.tenant_id=@t and b.id=@box and p.tenant_id=b.tenant_id and (p.location_code=@found or p.full_location_code=@found)",new{t,box,found=issue.FoundValue},tx,cancellationToken:ct));if(changed==0)throw new InvalidOperationException("Esta correção precisa de revisão manual. Nenhuma alteração foi aplicada.");after=JsonSerializer.Serialize(await db.QuerySingleAsync<object>(new CommandDefinition("select id,location_id from ged.box where tenant_id=@t and id=@box",new{t,box},tx,cancellationToken:ct)));}
  else throw new InvalidOperationException("Esta correção precisa de revisão manual. Nenhuma alteração foi aplicada.");
  await db.ExecuteAsync(new CommandDefinition("insert into ged.archive_reconciliation_fix(tenant_id,issue_id,action_type,before_json,after_json,applied_by,notes) values(@t,@id,@action,cast(@before as jsonb),cast(@after as jsonb),@u,@notes);update ged.archive_reconciliation_issue set status='FIXED',resolved_by=@u,resolved_at=now(),resolution_notes=@notes where tenant_id=@t and id=@id",new{t,id,action=issue.ProposedAction??issue.IssueType,before,after,u,notes},tx,cancellationToken:ct));await Custody(db,issue,t,u,"RECONCILIATION_FIX_APPLIED",notes,tx,ct);await tx.CommitAsync(ct);
 }
 private static Task<IssueRow?> Load(System.Data.IDbConnection db,Guid t,Guid id,System.Data.IDbTransaction tx,CancellationToken ct)=>db.QuerySingleOrDefaultAsync<IssueRow>(new CommandDefinition("select id,issue_type IssueType,subject_type SubjectType,subject_id SubjectId,control_number ControlNumber,found_value FoundValue,proposed_action ProposedAction,status from ged.archive_reconciliation_issue where tenant_id=@t and id=@id and reg_status='A' for update",new{t,id},tx,cancellationToken:ct));
 private static async Task Custody(System.Data.IDbConnection db,IssueRow i,Guid t,Guid u,string type,string? notes,System.Data.IDbTransaction tx,CancellationToken ct)=>await db.ExecuteAsync(new CommandDefinition("insert into ged.label_custody_event(tenant_id,subject_type,subject_id,control_number,event_type,event_title,event_description,source_table,source_id,performed_by,payload_json) values(@t,coalesce(@SubjectType,'ARCHIVE'),@SubjectId,@ControlNumber,@type,'Saneamento inteligente do acervo',@notes,'archive_reconciliation_issue',@Id,@u,jsonb_build_object('issueType',@IssueType))",new{t,i.SubjectType,i.SubjectId,i.ControlNumber,type,notes,i.Id,u,i.IssueType},tx,cancellationToken:ct));
 private sealed record IssueRow(Guid Id,string IssueType,string? SubjectType,Guid? SubjectId,string? ControlNumber,string? FoundValue,string? ProposedAction,string Status);
 private sealed record IssueDetailsRow(Guid Id,Guid RunId,string IssueType,string Severity,string? SubjectType,Guid? SubjectId,string? ControlNumber,string Title,string Description,string? Suggestion,string? ProposedAction,string Status,DateTime CreatedAt,string? ExpectedValue,string? FoundValue,string? ProposedPayload,string? ResolutionNotes,DateTime? ResolvedAt);
 private sealed record DashboardRow(int Boxes,int Documents,int Labels,int OpenIssues,int FixedIssues,int CriticalIssues,int IgnoredIssues,int LocationMismatches,int WithoutLabel,int OrphanLabels,int Weighted);

 private const string FullDiagnosisSql="""
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,box_id,title,description,suggestion,proposed_action)
select @tenantId,@runId,'BOX_WITHOUT_DOCUMENTS','HIGH','BOX',b.id,b.box_no,b.id,'Caixa sem documentos','A caixa ativa não possui documentos vinculados.','Revisar a caixa ou vincular os documentos encontrados.','MANUAL_REVIEW' from ged.box b where b.tenant_id=@tenantId and b.reg_status='A' and not exists(select 1 from ged.batch_item i where i.tenant_id=b.tenant_id and i.box_id=b.id and i.reg_status='A');
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,document_id,title,description,suggestion,proposed_action)
select @tenantId,@runId,'DOCUMENT_WITHOUT_BOX','HIGH','DOCUMENT',d.id,d.id::text,d.id,'Documento físico sem caixa','O documento não está vinculado a uma caixa ativa.','Vincular documento à caixa indicada pela última leitura ou inventário.','LINK_DOCUMENT_TO_BOX' from ged.document d where d.tenant_id=@tenantId and d.reg_status='A' and not exists(select 1 from ged.batch_item i where i.tenant_id=d.tenant_id and i.document_id=d.id and i.box_id is not null and i.reg_status='A');
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,box_id,title,description,suggestion,proposed_action)
select @tenantId,@runId,'BOX_WITHOUT_LABEL','MEDIUM','BOX',b.id,b.box_no,b.id,'Caixa sem etiqueta','Não há impressão ativa registrada para esta caixa.','Enviar caixa para a fila usando o modelo padrão ativo.','QUEUE_LABEL_PRINT' from ged.box b where b.tenant_id=@tenantId and b.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=b.tenant_id and h.label_subject_type='BOX' and h.label_subject_id=b.id and h.reg_status='A');
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,document_id,title,description,suggestion)
select @tenantId,@runId,'DOCUMENT_WITHOUT_LABEL','MEDIUM','DOCUMENT',d.id,d.id::text,d.id,'Documento sem etiqueta','Não há impressão ativa registrada para este documento.','Enviar documento para a fila de impressão.' from ged.document d where d.tenant_id=@tenantId and d.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=d.tenant_id and h.label_subject_type='DOCUMENT' and h.label_subject_id=d.id and h.reg_status='A');
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,title,description,suggestion)
select @tenantId,@runId,'LABEL_WITHOUT_SUBJECT','CRITICAL',h.label_subject_type,h.label_subject_id,h.control_number,'Etiqueta sem objeto válido','A etiqueta aponta para um objeto inexistente ou inativo.','Bloquear a etiqueta e conferir fisicamente o item.' from ged.label_print_history h where h.tenant_id=@tenantId and h.reg_status='A' and ((h.label_subject_type='BOX' and not exists(select 1 from ged.box b where b.tenant_id=h.tenant_id and b.id=h.label_subject_id and b.reg_status='A')) or (h.label_subject_type='DOCUMENT' and not exists(select 1 from ged.document d where d.tenant_id=h.tenant_id and d.id=h.label_subject_id and d.reg_status='A')));
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,title,description,suggestion,proposed_action)
select @tenantId,@runId,'MULTIPLE_ACTIVE_LABELS','HIGH',h.label_subject_type,h.label_subject_id,max(h.control_number),'Múltiplas etiquetas ativas','Mais de uma etiqueta ativa aponta para o mesmo objeto.','Manter a etiqueta mais recente e substituir as anteriores.','KEEP_LATEST_LABEL' from ged.label_print_history h where h.tenant_id=@tenantId and h.reg_status='A' group by h.label_subject_type,h.label_subject_id having count(*)>1;
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,expected_value,found_value,title,description,suggestion,proposed_action)
select @tenantId,@runId,'LOCATION_MISMATCH','HIGH',s.subject_type,s.subject_id,s.control_number,s.location_expected,s.location_scanned,'Divergência de localização','A última leitura encontrou o objeto em localização diferente.','Atualizar a localização para o valor confirmado no inventário.','UPDATE_BOX_LOCATION' from (select distinct on(subject_type,subject_id) * from ged.label_scan_event where tenant_id=@tenantId and reg_status='A' and scan_status='LOCATION_DIVERGENCE' order by subject_type,subject_id,scanned_at desc)s;
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,title,description,suggestion)
select @tenantId,@runId,'REPLACED_LABEL_IN_USE','CRITICAL',s.subject_type,s.subject_id,s.control_number,'Etiqueta substituída ainda em uso','Uma etiqueta já substituída voltou a ser lida.','Bloquear a etiqueta antiga e solicitar leitura da vigente.' from ged.label_scan_event s join ged.label_replacement_request r on r.tenant_id=s.tenant_id and r.old_label_print_history_id=s.label_print_history_id and r.status='COMPLETED' where s.tenant_id=@tenantId and s.reg_status='A';
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,box_id,title,description,suggestion)
select @tenantId,@runId,'MIXED_BOX_REQUIRES_REVIEW','MEDIUM','BOX',v.box_id,v.box_no,v.box_id,'Caixa com conteúdo misto','A caixa reúne classificações ou temporalidades distintas.','Revisar classificação, temporalidade e possível desmembramento.' from ged.vw_physical_map v where v.tenant_id=@tenantId and (v.classification_count>1 or v.retention_count>1);
""";
 private const string InventorySql="""
insert into ged.archive_reconciliation_issue(tenant_id,run_id,issue_type,severity,subject_type,subject_id,control_number,expected_value,found_value,title,description,suggestion,proposed_action)
select @tenantId,@runId,case when i.status='UNKNOWN' then 'INVENTORY_UNEXPECTED_ITEM' else 'LOCATION_MISMATCH' end,case when i.status='UNKNOWN' then 'CRITICAL' else 'HIGH' end,i.subject_type,i.subject_id,i.control_number,i.expected_location,i.found_location,case when i.status='UNKNOWN' then 'Item inesperado no inventário' else 'Localização divergente no inventário' end,coalesce(i.divergence_message,'O inventário encontrou uma divergência física.'),'Validar o item e atualizar o cadastro somente após conferência.','UPDATE_BOX_LOCATION' from ged.label_inventory_item i where i.tenant_id=@tenantId and i.session_id=@inventorySessionId and i.reg_status='A' and i.status in ('UNKNOWN','DIVERGENT_LOCATION');
""";
}
