using System.Text.Json;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Labels.Tracking;

namespace InovaGed.Infrastructure.PhysicalArchive;

public sealed class LabelTrackingService(IDbConnectionFactory factory) : ILabelTrackingService
{
    public async Task<LabelTraceDetails?> TraceAsync(Guid tenantId,string value,CancellationToken ct)
    {
        var key=Parse(value); if(key is null)return null;
        await using var db=await factory.OpenAsync(ct);
        return await db.QueryFirstOrDefaultAsync<LabelTraceDetails>(new CommandDefinition("""
select h.id PrintHistoryId,h.label_subject_type SubjectType,h.label_subject_id SubjectId,
coalesce(h.snapshot_json->>'controlNumber',h.snapshot_json->>'code',h.snapshot_json->>'labelCode') ControlNumber,
h.template_code TemplateCode,coalesce(h.print_mode,'FACTORY') PrintMode,
coalesce(pl.location_code,h.snapshot_json->>'location') ExpectedLocation,coalesce(pl.location_code,h.snapshot_json->>'location') CurrentLocation,
h.printed_at PrintedAt,(select max(e.scanned_at) from ged.label_scan_event e where e.tenant_id=h.tenant_id and e.label_print_history_id=h.id) LastScanAt,
case when exists(select 1 from ged.label_replacement_request r where r.tenant_id=h.tenant_id and r.old_label_print_history_id=h.id and r.status='COMPLETED') then 'REPLACED' else 'VALID' end Status
from ged.label_print_history h left join ged.box b on h.label_subject_type='BOX' and b.tenant_id=h.tenant_id and b.id=h.label_subject_id left join ged.physical_location pl on pl.tenant_id=b.tenant_id and pl.id=b.location_id
where h.tenant_id=@tenantId and h.reg_status='A' and (h.id::text=@key or h.label_subject_id::text=@key or h.snapshot_json->>'controlNumber'=@key or h.snapshot_json->>'code'=@key or h.snapshot_json->>'labelCode'=@key)
order by h.printed_at desc limit 1
""",new{tenantId,key},cancellationToken:ct));
    }
    public async Task<LabelScanResult> ScanAsync(LabelScanCommand x,CancellationToken ct)
    {
        if(x.UserId==Guid.Empty)throw new InvalidOperationException("Usuário autenticado obrigatório.");
        var trace=await TraceAsync(x.TenantId,x.Payload,ct); var status=trace?.Status??(Parse(x.Payload) is null?LabelScanStatus.InvalidPayload:LabelScanStatus.NotFound);
        if(trace is not null&&status==LabelScanStatus.Valid&&!string.IsNullOrWhiteSpace(x.Location)&&!string.IsNullOrWhiteSpace(trace.ExpectedLocation)&&!string.Equals(x.Location,trace.ExpectedLocation,StringComparison.OrdinalIgnoreCase))status=LabelScanStatus.LocationDivergence;
        var message=status switch { LabelScanStatus.Valid=>"Etiqueta válida e compatível com este acervo.",LabelScanStatus.Replaced=>"Esta etiqueta já foi substituída. Use a nova etiqueta vinculada ao objeto.",LabelScanStatus.LocationDivergence=>"Divergência encontrada: a localização lida não corresponde à localização esperada.",LabelScanStatus.InvalidPayload=>"QR Code inválido ou sem payload reconhecido.",_=>"Etiqueta não encontrada neste acervo."};
        await using var db=await factory.OpenAsync(ct);var id=Guid.NewGuid();
        await db.ExecuteAsync(new CommandDefinition("insert into ged.label_scan_event(id,tenant_id,label_print_history_id,template_code,subject_type,subject_id,control_number,location_expected,location_scanned,scan_source,scan_status,validation_message,scanned_payload,scanned_by,ip_address,user_agent) values(@id,@TenantId,@PrintHistoryId,@TemplateCode,coalesce(@SubjectType,'UNKNOWN'),@SubjectId,@ControlNumber,@ExpectedLocation,nullif(@Location,''),@Source,@status,@message,@Payload,@UserId,cast(nullif(@IpAddress,'') as inet),@UserAgent)",new{id,x.TenantId,trace?.PrintHistoryId,trace?.TemplateCode,trace?.SubjectType,trace?.SubjectId,trace?.ControlNumber,trace?.ExpectedLocation,x.Location,x.Source,status,message,x.Payload,x.UserId,x.IpAddress,x.UserAgent},cancellationToken:ct));
        return new(id,status,message,trace);
    }
    public async Task<IReadOnlyList<LabelScanEventItem>> ListEventsAsync(Guid tenantId,LabelScanEventFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<LabelScanEventItem>(new CommandDefinition("select id,subject_type SubjectType,control_number ControlNumber,location_scanned LocationScanned,scan_status Status,validation_message Message,scanned_at ScannedAt from ged.label_scan_event where tenant_id=@tenantId and reg_status='A' and (@From is null or scanned_at>=@From) and (@To is null or scanned_at<@To+interval '1 day') and (coalesce(@Status,'')='' or scan_status=@Status) and (coalesce(@ControlNumber,'')='' or control_number ilike '%'||@ControlNumber||'%') order by scanned_at desc limit 1000",new{tenantId,f.From,f.To,f.Status,f.ControlNumber},cancellationToken:ct))).AsList();}
    private static string? Parse(string raw){if(string.IsNullOrWhiteSpace(raw)||raw.Length>2048||raw.Contains('<'))return null;raw=raw.Trim();if(Uri.TryCreate(raw,UriKind.Absolute,out var u)){var q=Microsoft.AspNetCore.WebUtilities.QueryHelpers.ParseQuery(u.Query);foreach(var n in new[]{"payload","code","id"})if(q.TryGetValue(n,out var v)&&!string.IsNullOrWhiteSpace(v))return v.ToString();var part=u.Segments.LastOrDefault()?.Trim('/');return string.IsNullOrWhiteSpace(part)?null:part;}if(raw.StartsWith('{'))try{using var j=JsonDocument.Parse(raw);foreach(var n in new[]{"printHistoryId","subjectId","controlNumber","code"})if(j.RootElement.TryGetProperty(n,out var p))return p.ToString();return null;}catch(JsonException){return null;}return raw.Length>=2?raw:null;}
}

public sealed class LabelInventoryService(IDbConnectionFactory factory,ILabelTrackingService tracking):ILabelInventoryService
{
 public async Task<Guid> StartSessionAsync(LabelInventoryStartCommand x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Title))throw new InvalidOperationException("Informe o título.");await using var db=await factory.OpenAsync(ct);var id=Guid.NewGuid();await db.ExecuteAsync(new CommandDefinition("insert into ged.label_inventory_session(id,tenant_id,session_number,title,expected_location,started_by,notes) values(@id,@TenantId,@number,@Title,nullif(@ExpectedLocation,''),@UserId,nullif(@Notes,''))",new{id,x.TenantId,number=$"INV-{DateTime.UtcNow:yyyyMMddHHmmss}-{Random.Shared.Next(100,999)}",x.Title,x.ExpectedLocation,x.UserId,x.Notes},cancellationToken:ct));return id;}
 public async Task<LabelInventoryDetails?> GetSessionAsync(Guid tid,Guid id,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var h=await db.QuerySingleOrDefaultAsync<SessionRow>(new CommandDefinition("select id,session_number SessionNumber,title,expected_location ExpectedLocation,status,started_at StartedAt,notes from ged.label_inventory_session where tenant_id=@tid and id=@id and reg_status='A'",new{tid,id},cancellationToken:ct));if(h is null)return null;var items=(await db.QueryAsync<LabelInventoryItem>(new CommandDefinition("select id,subject_type SubjectType,control_number ControlNumber,expected_location ExpectedLocation,found_location FoundLocation,status,divergence_message DivergenceMessage,scanned_at ScannedAt from ged.label_inventory_item where tenant_id=@tid and session_id=@id and reg_status='A' order by display_order",new{tid,id},cancellationToken:ct))).AsList();return new(h.Id,h.SessionNumber,h.Title,h.ExpectedLocation,h.Status,h.StartedAt,h.Notes,items);}
 public async Task<LabelInventoryScanResult> AddScanAsync(LabelInventoryScanCommand x,CancellationToken ct){var s=await GetSessionAsync(x.TenantId,x.SessionId,ct)??throw new KeyNotFoundException();if(s.Status!="OPEN")throw new InvalidOperationException("Inventário encerrado.");var scan=await tracking.ScanAsync(new(x.TenantId,x.UserId,x.Payload,x.FoundLocation,"INVENTORY",x.IpAddress,x.UserAgent),ct);var duplicate=scan.Trace?.SubjectId is Guid sid&&s.Items.Any(i=>i.ControlNumber==scan.Trace.ControlNumber);var status=duplicate?LabelInventoryItemStatus.Duplicated:scan.Trace is null?LabelInventoryItemStatus.Unknown:scan.Status==LabelScanStatus.LocationDivergence||(!string.IsNullOrWhiteSpace(s.ExpectedLocation)&&!string.Equals(s.ExpectedLocation,x.FoundLocation,StringComparison.OrdinalIgnoreCase))?LabelInventoryItemStatus.DivergentLocation:LabelInventoryItemStatus.Found;var id=Guid.NewGuid();await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition("insert into ged.label_inventory_item(id,tenant_id,session_id,scan_event_id,subject_type,subject_id,control_number,expected_location,found_location,status,divergence_message,scanned_by,display_order) values(@id,@TenantId,@SessionId,@eventId,coalesce(@type,'UNKNOWN'),@subjectId,@control,@expected,@FoundLocation,@status,@msg,@UserId,@order)",new{id,x.TenantId,x.SessionId,eventId=scan.EventId,type=scan.Trace?.SubjectType,subjectId=scan.Trace?.SubjectId,control=scan.Trace?.ControlNumber,expected=s.ExpectedLocation,x.FoundLocation,status,msg=status=="DIVERGENT_LOCATION"?"Localização divergente.":null,x.UserId,order=s.Items.Count},cancellationToken:ct));return new(id,status,status=="DUPLICATED"?"Etiqueta já lida nesta sessão.":scan.Message);}
 public async Task CloseSessionAsync(Guid tid,Guid id,Guid uid,string? notes,CancellationToken ct){var s=await GetSessionAsync(tid,id,ct)??throw new KeyNotFoundException();if(s.Items.Count==0)throw new InvalidOperationException("Não é permitido fechar inventário vazio.");if(s.Items.Any(i=>i.Status=="DIVERGENT_LOCATION")&&string.IsNullOrWhiteSpace(notes))throw new InvalidOperationException("Informe uma observação para concluir com divergências.");await Set(tid,id,uid,"CLOSED",notes,ct);}
 public Task CancelSessionAsync(Guid tid,Guid id,Guid uid,string reason,CancellationToken ct)=>string.IsNullOrWhiteSpace(reason)?throw new InvalidOperationException("Informe o motivo."):Set(tid,id,uid,"CANCELLED",reason,ct);
 private async Task Set(Guid tid,Guid id,Guid uid,string status,string? notes,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var n=await db.ExecuteAsync(new CommandDefinition("update ged.label_inventory_session set status=@status,finished_by=@uid,finished_at=now(),notes=concat_ws(E'\\n',notes,@notes) where tenant_id=@tid and id=@id and status='OPEN'",new{tid,id,uid,status,notes},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Sessão não está aberta.");}
 private sealed class SessionRow{public Guid Id{get;set;}public string SessionNumber{get;set;}="";public string Title{get;set;}="";public string? ExpectedLocation{get;set;}public string Status{get;set;}="";public DateTime StartedAt{get;set;}public string? Notes{get;set;}}
}

public sealed class LabelReplacementService(IDbConnectionFactory factory):ILabelReplacementService
{
 public async Task<Guid> RequestReplacementAsync(LabelReplacementRequestCommand x,CancellationToken ct){if(string.IsNullOrWhiteSpace(x.Reason))throw new InvalidOperationException("Informe o motivo da substituição.");await using var db=await factory.OpenAsync(ct);var id=Guid.NewGuid();await db.ExecuteAsync(new CommandDefinition("insert into ged.label_replacement_request(id,tenant_id,old_label_print_history_id,old_template_code,subject_type,subject_id,control_number,reason,requested_by) values(@id,@TenantId,@OldPrintHistoryId,@OldTemplateCode,@SubjectType,@SubjectId,@ControlNumber,@Reason,@UserId)",new{id,x.TenantId,x.OldPrintHistoryId,x.OldTemplateCode,x.SubjectType,x.SubjectId,x.ControlNumber,x.Reason,x.UserId},cancellationToken:ct));return id;}
 public Task ApproveAsync(Guid t,Guid r,Guid u,CancellationToken c)=>Set(t,r,u,"APPROVED",null,null,c); public Task RejectAsync(Guid t,Guid r,Guid u,string reason,CancellationToken c)=>string.IsNullOrWhiteSpace(reason)?throw new InvalidOperationException("Informe o motivo."):Set(t,r,u,"REJECTED",null,reason,c); public Task CompleteAsync(Guid t,Guid r,Guid n,Guid u,CancellationToken c)=>n==Guid.Empty?throw new InvalidOperationException("Nova impressão obrigatória."):Set(t,r,u,"COMPLETED",n,null,c);
 private async Task Set(Guid t,Guid r,Guid u,string status,Guid? print,string? reason,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var allowed=status=="APPROVED"?"REQUESTED":status=="COMPLETED"?"APPROVED":"REQUESTED";var sql=status=="APPROVED"?"update ged.label_replacement_request set status=@status,approved_by=@u,approved_at=now() where tenant_id=@t and id=@r and status=@allowed":status=="COMPLETED"?"update ged.label_replacement_request set status=@status,new_label_print_history_id=@print,completed_by=@u,completed_at=now() where tenant_id=@t and id=@r and status=@allowed":"update ged.label_replacement_request set status=@status,reason=reason||E'\\nRejeição: '||@reason,completed_by=@u,completed_at=now() where tenant_id=@t and id=@r and status=@allowed";if(await db.ExecuteAsync(new CommandDefinition(sql,new{t,r,u,status,allowed,print,reason},cancellationToken:ct))==0)throw new InvalidOperationException("Solicitação não encontrada ou transição inválida.");}
 public async Task<IReadOnlyList<LabelReplacementItem>> ListAsync(Guid tenantId,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<LabelReplacementItem>(new CommandDefinition("select id,subject_type SubjectType,control_number ControlNumber,reason,status,requested_at RequestedAt from ged.label_replacement_request where tenant_id=@tenantId and reg_status='A' order by requested_at desc",new{tenantId},cancellationToken:ct))).AsList();}
}
