using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Labels.Intelligence;

namespace InovaGed.Infrastructure.PhysicalArchive;

public sealed class LabelIntelligenceService(IDbConnectionFactory factory) : ILabelIntelligenceService
{
 public async Task<LabelIntelligenceDashboard> GetDashboardAsync(Guid tenantId,LabelIntelligenceFilter f,CancellationToken ct)
 {
  await using var db=await factory.OpenAsync(ct);
  using var grid=await db.QueryMultipleAsync(new CommandDefinition("""
select count(*) from ged.label_print_history where tenant_id=@tenantId and reg_status='A' and (@From is null or printed_at>=@From) and (@To is null or printed_at<@To+interval '1 day');
select count(*) from ged.label_scan_event where tenant_id=@tenantId and reg_status='A' and (@From is null or scanned_at>=@From) and (@To is null or scanned_at<@To+interval '1 day');
select count(*) from ged.label_print_history h where h.tenant_id=@tenantId and h.reg_status='A' and not exists(select 1 from ged.label_scan_event s where s.tenant_id=h.tenant_id and s.label_print_history_id=h.id);
select count(*) from ged.label_scan_event where tenant_id=@tenantId and reg_status='A' and scan_status='LOCATION_DIVERGENCE';
select count(*) from ged.label_replacement_request where tenant_id=@tenantId and reg_status='A' and status='COMPLETED';
select count(*) from ged.box b where b.tenant_id=@tenantId and b.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=b.tenant_id and h.label_subject_type='BOX' and h.label_subject_id=b.id and h.reg_status='A');
select count(*) from ged.document d where d.tenant_id=@tenantId and d.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=d.tenant_id and h.label_subject_type='DOCUMENT' and h.label_subject_id=d.id and h.reg_status='A');
select count(*) from ged.label_alert where tenant_id=@tenantId and reg_status='A' and status in ('OPEN','IN_PROGRESS');
select to_char(scanned_at::date,'DD/MM') Label,count(*)::int Value from ged.label_scan_event where tenant_id=@tenantId and scanned_at>=current_date-13 group by scanned_at::date order by scanned_at::date;
select coalesce(location_scanned,'Não informada') Label,count(*)::int Value from ged.label_scan_event where tenant_id=@tenantId and scan_status='LOCATION_DIVERGENCE' group by 1 order by 2 desc limit 10;
select coalesce(template_code,'Sem modelo') Label,count(*)::int Value from ged.label_print_history where tenant_id=@tenantId and reg_status='A' group by 1 order by 2 desc limit 10;
select coalesce(printed_by::text,'Sistema') Label,count(*)::int Value from ged.label_print_history where tenant_id=@tenantId and reg_status='A' group by 1 order by 2 desc limit 10;
select severity Label,count(*)::int Value from ged.label_alert where tenant_id=@tenantId and status in ('OPEN','IN_PROGRESS') and reg_status='A' group by severity order by 2 desc;
""",new{tenantId,f.From,f.To},cancellationToken:ct));
  var printed=await grid.ReadSingleAsync<int>();var scanned=await grid.ReadSingleAsync<int>();var never=await grid.ReadSingleAsync<int>();var divergences=await grid.ReadSingleAsync<int>();var replacements=await grid.ReadSingleAsync<int>();var boxes=await grid.ReadSingleAsync<int>();var docs=await grid.ReadSingleAsync<int>();var alerts=await grid.ReadSingleAsync<int>();
  return new(printed,scanned,never,divergences,replacements,boxes,docs,alerts,(await grid.ReadAsync<LabelMetric>()).AsList(),(await grid.ReadAsync<LabelMetric>()).AsList(),(await grid.ReadAsync<LabelMetric>()).AsList(),(await grid.ReadAsync<LabelMetric>()).AsList(),(await grid.ReadAsync<LabelMetric>()).AsList());
 }
 public async Task<IReadOnlyList<LabelDivergenceItem>> ListDivergencesAsync(Guid tenantId,LabelIntelligenceFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<LabelDivergenceItem>(new CommandDefinition("select id,subject_type SubjectType,subject_id SubjectId,control_number ControlNumber,location_expected ExpectedLocation,location_scanned FoundLocation,scanned_at DetectedAt,scan_source Source from ged.label_scan_event where tenant_id=@tenantId and reg_status='A' and scan_status='LOCATION_DIVERGENCE' and (@From is null or scanned_at>=@From) and (@To is null or scanned_at<@To+interval '1 day') and (coalesce(@Location,'')='' or coalesce(location_scanned,'') ilike '%'||@Location||'%') order by scanned_at desc limit 2000",new{tenantId,f.From,f.To,f.Location},cancellationToken:ct))).AsList();}
 public async Task<IReadOnlyList<LabelNeverScannedItem>> ListNeverScannedAsync(Guid tenantId,LabelIntelligenceFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<LabelNeverScannedItem>(new CommandDefinition("select h.id PrintHistoryId,h.label_subject_type SubjectType,h.label_subject_id SubjectId,coalesce(h.control_number,h.snapshot_json->>'controlNumber',h.snapshot_json->>'code') ControlNumber,h.template_code TemplateCode,coalesce(h.location,h.snapshot_json->>'location') Location,h.printed_at PrintedAt,h.printed_by PrintedBy from ged.label_print_history h where h.tenant_id=@tenantId and h.reg_status='A' and not exists(select 1 from ged.label_scan_event s where s.tenant_id=h.tenant_id and s.label_print_history_id=h.id) and (@From is null or h.printed_at>=@From) and (@To is null or h.printed_at<@To+interval '1 day') order by h.printed_at desc limit 2000",new{tenantId,f.From,f.To},cancellationToken:ct))).AsList();}
 public async Task<IReadOnlyList<LabelWithoutPrintItem>> ListObjectsWithoutLabelAsync(Guid tenantId,string subjectType,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var box=subjectType.Equals("BOX",StringComparison.OrdinalIgnoreCase);var sql=box?"select b.id SubjectId,'BOX' SubjectType,b.box_no ControlNumber,pl.location_code Location,b.created_at CreatedAt from ged.box b left join ged.physical_location pl on pl.tenant_id=b.tenant_id and pl.id=b.location_id where b.tenant_id=@tenantId and b.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=b.tenant_id and h.label_subject_type='BOX' and h.label_subject_id=b.id and h.reg_status='A') order by b.created_at desc limit 2000":"select d.id SubjectId,'DOCUMENT' SubjectType,d.id::text ControlNumber,null::text Location,d.created_at CreatedAt from ged.document d where d.tenant_id=@tenantId and d.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=d.tenant_id and h.label_subject_type='DOCUMENT' and h.label_subject_id=d.id and h.reg_status='A') order by 5 desc limit 2000";return(await db.QueryAsync<LabelWithoutPrintItem>(new CommandDefinition(sql,new{tenantId},cancellationToken:ct))).AsList();}
}

public sealed class LabelAlertService(IDbConnectionFactory factory) : ILabelAlertService
{
 public async Task<int> DetectAlertsAsync(Guid tenantId,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var sql="""
insert into ged.label_alert(tenant_id,alert_type,severity,subject_type,subject_id,control_number,location,title,message)
select h.tenant_id,'PRINTED_NEVER_SCANNED','MEDIUM',h.label_subject_type,h.label_subject_id,coalesce(h.control_number,h.snapshot_json->>'controlNumber'),coalesce(h.location,h.snapshot_json->>'location'),'Etiqueta impressa e nunca lida','Esta etiqueta foi impressa há mais de 7 dias, mas ainda não possui nenhuma leitura registrada.' from ged.label_print_history h where h.tenant_id=@tenantId and h.reg_status='A' and h.printed_at<now()-interval '7 days' and not exists(select 1 from ged.label_scan_event s where s.tenant_id=h.tenant_id and s.label_print_history_id=h.id) on conflict do nothing;
insert into ged.label_alert(tenant_id,alert_type,severity,subject_type,subject_id,control_number,location,title,message)
select s.tenant_id,'LOCATION_DIVERGENCE','HIGH',s.subject_type,s.subject_id,s.control_number,s.location_scanned,'Divergência de localização','A localização encontrada não confere com a localização esperada.' from ged.label_scan_event s where s.tenant_id=@tenantId and s.reg_status='A' and s.scan_status='LOCATION_DIVERGENCE' on conflict do nothing;
insert into ged.label_alert(tenant_id,alert_type,severity,subject_type,subject_id,control_number,title,message)
select b.tenant_id,'BOX_WITHOUT_LABEL','MEDIUM','BOX',b.id,b.box_no,'Caixa sem etiqueta','Esta caixa ainda não possui etiqueta impressa.' from ged.box b where b.tenant_id=@tenantId and b.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=b.tenant_id and h.label_subject_type='BOX' and h.label_subject_id=b.id and h.reg_status='A') on conflict do nothing;
insert into ged.label_alert(tenant_id,alert_type,severity,subject_type,subject_id,control_number,title,message)
select d.tenant_id,'DOCUMENT_WITHOUT_LABEL','MEDIUM','DOCUMENT',d.id,d.id::text,'Documento sem etiqueta','Este documento físico ainda não possui etiqueta impressa.' from ged.document d where d.tenant_id=@tenantId and d.reg_status='A' and not exists(select 1 from ged.label_print_history h where h.tenant_id=d.tenant_id and h.label_subject_type='DOCUMENT' and h.label_subject_id=d.id and h.reg_status='A') on conflict do nothing;
insert into ged.label_alert(tenant_id,alert_type,severity,subject_type,subject_id,control_number,title,message)
select s.tenant_id,'REPLACED_LABEL_SCANNED','CRITICAL',s.subject_type,s.subject_id,s.control_number,'Etiqueta substituída foi lida','Uma etiqueta marcada como substituída voltou a circular e requer conferência imediata.' from ged.label_scan_event s join ged.label_replacement_request r on r.tenant_id=s.tenant_id and r.old_label_print_history_id=s.label_print_history_id and r.status='COMPLETED' where s.tenant_id=@tenantId and s.reg_status='A' on conflict do nothing;
insert into ged.label_alert(tenant_id,alert_type,severity,subject_type,subject_id,control_number,title,message)
select s.tenant_id,'DUPLICATE_SCAN','HIGH',max(s.subject_type),s.subject_id,s.control_number,'Leituras excessivas em curto período','A mesma etiqueta foi lida mais de cinco vezes em dez minutos.' from ged.label_scan_event s where s.tenant_id=@tenantId and s.reg_status='A' and s.scanned_at>now()-interval '10 minutes' group by s.tenant_id,s.subject_id,s.control_number having count(*)>5 on conflict do nothing;
""";return await db.ExecuteAsync(new CommandDefinition(sql,new{tenantId},cancellationToken:ct));}
 public async Task<IReadOnlyList<LabelAlertItem>> ListAsync(Guid tenantId,LabelAlertFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<LabelAlertItem>(new CommandDefinition("select id,alert_type AlertType,severity,subject_type SubjectType,subject_id SubjectId,control_number ControlNumber,location,title,message,status,detected_at DetectedAt,resolution_notes ResolutionNotes from ged.label_alert where tenant_id=@tenantId and reg_status='A' and (coalesce(@Status,'')='' or status=@Status) and (coalesce(@Severity,'')='' or severity=@Severity) and (coalesce(@Type,'')='' or alert_type=@Type) order by case severity when 'CRITICAL' then 1 when 'HIGH' then 2 when 'MEDIUM' then 3 else 4 end,detected_at desc limit 2000",new{tenantId,f.Status,f.Severity,f.Type},cancellationToken:ct))).AsList();}
 public Task ResolveAsync(Guid t,Guid id,Guid u,string notes,CancellationToken ct)=>Set(t,id,u,notes,LabelAlertStatus.Resolved,ct); public Task IgnoreAsync(Guid t,Guid id,Guid u,string notes,CancellationToken ct)=>Set(t,id,u,notes,LabelAlertStatus.Ignored,ct);
 private async Task Set(Guid t,Guid id,Guid u,string notes,string status,CancellationToken ct){if(string.IsNullOrWhiteSpace(notes))throw new InvalidOperationException("Informe uma observação ou motivo.");await using var db=await factory.OpenAsync(ct);if(await db.ExecuteAsync(new CommandDefinition("update ged.label_alert set status=@status,resolved_by=@u,resolved_at=now(),resolution_notes=@notes where tenant_id=@t and id=@id and reg_status='A' and status in ('OPEN','IN_PROGRESS')",new{t,id,u,notes,status},cancellationToken:ct))==0)throw new KeyNotFoundException("Alerta não encontrado ou já encerrado.");}
}

public sealed class LabelCustodyService(IDbConnectionFactory factory) : ILabelCustodyService
{
 public async Task RegisterEventAsync(LabelCustodyEventCommand x,CancellationToken ct){if(x.TenantId==Guid.Empty)throw new InvalidOperationException("Tenant obrigatório.");await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition("insert into ged.label_custody_event(tenant_id,subject_type,subject_id,control_number,event_type,event_title,event_description,source_table,source_id,location_from,location_to,performed_by,ip_address,user_agent,payload_json) values(@TenantId,@SubjectType,@SubjectId,@ControlNumber,@EventType,@EventTitle,@EventDescription,@SourceTable,@SourceId,@LocationFrom,@LocationTo,@PerformedBy,cast(nullif(@IpAddress,'') as inet),@UserAgent,cast(nullif(@PayloadJson,'') as jsonb))",x,cancellationToken:ct));}
 public Task<LabelCustodyTimeline> GetTimelineAsync(Guid t,string type,Guid id,CancellationToken ct)=>Get(t,"subject_type=@type and subject_id=@id",new{t,type,id},type,id,null,ct);
 public Task<LabelCustodyTimeline> GetTimelineByControlAsync(Guid t,string control,CancellationToken ct)=>Get(t,"control_number=@control",new{t,control},"",null,control,ct);
 private async Task<LabelCustodyTimeline> Get(Guid t,string predicate,object args,string type,Guid? id,string? control,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var rows=(await db.QueryAsync<LabelCustodyEventItem>(new CommandDefinition($"select id,event_type EventType,event_title EventTitle,event_description EventDescription,source_table SourceTable,source_id SourceId,location_from LocationFrom,location_to LocationTo,performed_by PerformedBy,performed_at PerformedAt,ip_address::text IpAddress,user_agent UserAgent from ged.label_custody_event where tenant_id=@t and reg_status='A' and {predicate} order by performed_at",args,cancellationToken:ct))).AsList();return new(type,id,control,rows);}
}
