using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.PhysicalArchive;
namespace InovaGed.Infrastructure.PhysicalArchive;
public sealed class LabelTemplateCatalogService(IDbConnectionFactory dbFactory):ILabelTemplateCatalogService {
 public async Task<IReadOnlyList<LabelTemplateOption>> GetTemplatesAsync(Guid tenantId,string subjectType,string? mode,CancellationToken ct){await using var db=await dbFactory.OpenAsync(ct);return (await db.QueryAsync<LabelTemplateOption>(new CommandDefinition("""select code,name,print_mode Mode,subject_type SubjectType,coalesce(description,'') Description,view_name ViewName,version::text Version,supports_batch SupportsBatch,allows_manual_fields AllowsManualFields,is_system_template IsSystemTemplate,id,is_default IsDefault from ged.label_template where (tenant_id=@tenantId or tenant_id is null) and subject_type=@subjectType and (@mode is null or print_mode=@mode) and is_active and reg_status='A' order by is_default desc,display_order,name""",new{tenantId,subjectType,mode=string.IsNullOrWhiteSpace(mode)?null:mode},cancellationToken:ct))).AsList();}
 public async Task<LabelTemplateOption> GetTemplateAsync(Guid tenantId,string templateCode,CancellationToken ct){await using var db=await dbFactory.OpenAsync(ct);return await db.QuerySingleOrDefaultAsync<LabelTemplateOption>(new CommandDefinition("""select code,name,print_mode Mode,subject_type SubjectType,coalesce(description,'') Description,view_name ViewName,version::text Version,supports_batch SupportsBatch,allows_manual_fields AllowsManualFields,is_system_template IsSystemTemplate,id,is_default IsDefault from ged.label_template where (tenant_id=@tenantId or tenant_id is null) and code=@templateCode and is_active and reg_status='A'""",new{tenantId,templateCode},cancellationToken:ct))??throw new KeyNotFoundException("Modelo de etiqueta não encontrado.");}
 public async Task<bool> IsCompatibleAsync(Guid tenantId,string templateCode,string subjectType,CancellationToken ct){await using var db=await dbFactory.OpenAsync(ct);return await db.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from ged.label_template where (tenant_id=@tenantId or tenant_id is null) and code=@templateCode and subject_type=@subjectType and is_active and reg_status='A')",new{tenantId,templateCode,subjectType},cancellationToken:ct));}
}
