using System.Data;
using System.Text.Json;
using System.Text.RegularExpressions;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Labels;
using Npgsql;

namespace InovaGed.Infrastructure.PhysicalArchive;

public sealed class LabelTemplateManager(IDbConnectionFactory dbFactory) : ILabelTemplateManager, ILabelTemplateVersioningService, ILabelTemplateRenderer
{
 private const string Scope="(tenant_id=@tenantId or tenant_id is null)";
 public async Task<IReadOnlyList<LabelTemplateListItem>> ListAsync(Guid tenantId,CancellationToken ct) { await using var db=await dbFactory.OpenAsync(ct); return (await db.QueryAsync<LabelTemplateListItem>(new CommandDefinition($"""
select id,code,name,description,print_mode PrintMode,subject_type SubjectType,view_name ViewName,version,is_system_template IsSystemTemplate,is_custom_template IsCustomTemplate,is_active IsActive,is_default IsDefault,supports_batch SupportsBatch,allows_manual_fields AllowsManualFields,display_order DisplayOrder from ged.label_template where {Scope} and reg_status='A' order by display_order,name
""",new{tenantId},cancellationToken:ct))).AsList(); }
 public async Task<LabelTemplateDetails?> GetAsync(Guid tenantId,Guid templateId,CancellationToken ct) { await using var db=await dbFactory.OpenAsync(ct); return await LoadAsync(db,tenantId,templateId,ct); }
 public async Task<Guid> CreateCustomAsync(Guid tenantId,LabelTemplateEditCommand command,CancellationToken ct) {
  Validate(command); await using var db=await dbFactory.OpenAsync(ct); await using var tx=await db.BeginTransactionAsync(ct); try {
   var id=Guid.NewGuid(); await db.ExecuteAsync(new CommandDefinition("""insert into ged.label_template(id,tenant_id,code,name,description,print_mode,subject_type,view_name,is_custom_template,is_active,supports_batch,allows_manual_fields) values(@id,@tenantId,@Code,@Name,@Description,'CUSTOM',@SubjectType,case when @SubjectType='BOX' then 'LocDeskBoxLabel' else 'LocDeskFolderLabel' end,true,@IsActive,@SupportsBatch,@AllowsManualFields)""",new{id,tenantId,command.Code,command.Name,command.Description,SubjectType=NormalizeSubject(command.SubjectType),command.IsActive,command.SupportsBatch,command.AllowsManualFields},tx,cancellationToken:ct));
   await SaveConfigAndFields(db,tx,id,tenantId,command,ct); await tx.CommitAsync(ct); return id;
  } catch(PostgresException ex) when(ex.SqlState=="23505") { await tx.RollbackAsync(ct); throw new InvalidOperationException("Já existe um modelo com este código.",ex); }
 }
 public async Task UpdateAsync(Guid tenantId,Guid templateId,LabelTemplateEditCommand command,CancellationToken ct) {
  Validate(command); await using var db=await dbFactory.OpenAsync(ct); var current=await LoadAsync(db,tenantId,templateId,ct) ?? throw new KeyNotFoundException("Modelo não encontrado.");
  if(current.Template.IsSystemTemplate) throw new InvalidOperationException("Modelos de fábrica têm estrutura protegida."); await using var tx=await db.BeginTransactionAsync(ct); try {
   await db.ExecuteAsync(new CommandDefinition("""update ged.label_template set code=@Code,name=@Name,description=@Description,subject_type=@SubjectType,is_active=@IsActive,supports_batch=@SupportsBatch,allows_manual_fields=@AllowsManualFields,updated_at=now() where id=@templateId and tenant_id=@tenantId and reg_status='A'""",new{command.Code,command.Name,command.Description,SubjectType=NormalizeSubject(command.SubjectType),command.IsActive,command.SupportsBatch,command.AllowsManualFields,templateId,tenantId},tx,cancellationToken:ct));
   await SaveConfigAndFields(db,tx,templateId,tenantId,command,ct); await tx.CommitAsync(ct);
  } catch(PostgresException ex) when(ex.SqlState=="23505") { await tx.RollbackAsync(ct); throw new InvalidOperationException("Já existe um modelo com este código.",ex); }
 }
 public Task ActivateAsync(Guid tenantId,Guid templateId,CancellationToken ct)=>SetActive(tenantId,templateId,true,ct);
 public async Task DeactivateAsync(Guid tenantId,Guid templateId,CancellationToken ct) {
  await using var db=await dbFactory.OpenAsync(ct); var item=await LoadAsync(db,tenantId,templateId,ct)??throw new KeyNotFoundException("Modelo não encontrado.");
  var count=await db.ExecuteScalarAsync<int>(new CommandDefinition($"select count(*) from ged.label_template where {Scope} and subject_type=@subject and print_mode=@mode and is_active and reg_status='A' and id<>@templateId",new{tenantId,subject=item.Template.SubjectType,mode=item.Template.PrintMode,templateId},cancellationToken:ct));
  if(count==0) throw new InvalidOperationException("Não é possível desativar o único modelo ativo deste tipo."); await SetActive(tenantId,templateId,false,ct);
 }
 public async Task SetDefaultAsync(Guid tenantId,Guid templateId,CancellationToken ct) { await using var db=await dbFactory.OpenAsync(ct); var item=await LoadAsync(db,tenantId,templateId,ct)??throw new KeyNotFoundException("Modelo não encontrado."); if(!item.Template.IsActive) throw new InvalidOperationException("Ative o modelo antes de defini-lo como padrão."); await using var tx=await db.BeginTransactionAsync(ct); await db.ExecuteAsync(new CommandDefinition("update ged.label_template set is_default=false,updated_at=now() where tenant_id=@tenantId and subject_type=@subject and print_mode=@mode and reg_status='A'",new{tenantId,subject=item.Template.SubjectType,mode=item.Template.PrintMode},tx,cancellationToken:ct)); await db.ExecuteAsync(new CommandDefinition("update ged.label_template set is_default=true,updated_at=now() where id=@templateId and (tenant_id=@tenantId or tenant_id is null)",new{templateId,tenantId},tx,cancellationToken:ct)); await tx.CommitAsync(ct); }
 public async Task<int> PublishVersionAsync(Guid tenantId,Guid templateId,Guid userId,string? notes,CancellationToken ct) { await using var db=await dbFactory.OpenAsync(ct); var detail=await LoadAsync(db,tenantId,templateId,ct)??throw new KeyNotFoundException("Modelo não encontrado."); if(!detail.Fields.Any(x=>x.IsVisible) && detail.Template.IsCustomTemplate) throw new InvalidOperationException("Publique somente modelos com pelo menos um campo visível."); await using var tx=await db.BeginTransactionAsync(ct); var next=await db.ExecuteScalarAsync<int>(new CommandDefinition("select coalesce(max(version_number),0)+1 from ged.label_template_version where template_id=@templateId",new{templateId},tx,cancellationToken:ct)); var snapshot=JsonSerializer.Serialize(detail); await db.ExecuteAsync(new CommandDefinition("insert into ged.label_template_version(template_id,version_number,snapshot_json,published_by,change_notes) values(@templateId,@next,cast(@snapshot as jsonb),@userId,@notes)",new{templateId,next,snapshot,userId,notes},tx,cancellationToken:ct)); await db.ExecuteAsync(new CommandDefinition("update ged.label_template set version=@next,updated_at=now(),updated_by=@userId where id=@templateId",new{next,userId,templateId},tx,cancellationToken:ct)); await tx.CommitAsync(ct); return next; }
 public async Task<IReadOnlyList<LabelTemplateVersionItem>> ListVersionsAsync(Guid tenantId,Guid templateId,CancellationToken ct) { await using var db=await dbFactory.OpenAsync(ct); if(await LoadAsync(db,tenantId,templateId,ct) is null) return []; return (await db.QueryAsync<LabelTemplateVersionItem>(new CommandDefinition("select id,version_number VersionNumber,published_by PublishedBy,published_at PublishedAt,change_notes ChangeNotes from ged.label_template_version where template_id=@templateId and reg_status='A' order by version_number desc",new{templateId},cancellationToken:ct))).AsList(); }
 public async Task<LabelTemplateVersionDetails?> GetVersionAsync(Guid tenantId,Guid versionId,CancellationToken ct) { await using var db=await dbFactory.OpenAsync(ct); return await db.QuerySingleOrDefaultAsync<LabelTemplateVersionDetails>(new CommandDefinition($"""select v.id,v.template_id TemplateId,v.version_number VersionNumber,v.snapshot_json::text SnapshotJson,v.published_by PublishedBy,v.published_at PublishedAt,v.change_notes ChangeNotes from ged.label_template_version v join ged.label_template t on t.id=v.template_id where v.id=@versionId and {Scope.Replace("tenant_id","t.tenant_id")} and v.reg_status='A'""",new{versionId,tenantId},cancellationToken:ct)); }
 public async Task<LabelRenderDefinition?> BuildAsync(Guid tenantId,Guid templateId,IReadOnlyDictionary<string,string?> values,CancellationToken ct) { var t=await GetAsync(tenantId,templateId,ct); return t is null?null:new(t,values); }
 private async Task SetActive(Guid tenantId,Guid templateId,bool active,CancellationToken ct) { await using var db=await dbFactory.OpenAsync(ct); var changed=await db.ExecuteAsync(new CommandDefinition("update ged.label_template set is_active=@active,is_default=case when @active then is_default else false end,updated_at=now() where id=@templateId and (tenant_id=@tenantId or tenant_id is null) and reg_status='A'",new{active,templateId,tenantId},cancellationToken:ct)); if(changed==0) throw new KeyNotFoundException("Modelo não encontrado."); }
 private static async Task<LabelTemplateDetails?> LoadAsync(IDbConnection db,Guid tenantId,Guid id,CancellationToken ct) { var t=await db.QuerySingleOrDefaultAsync<LabelTemplateListItem>(new CommandDefinition($"select id,code,name,description,print_mode PrintMode,subject_type SubjectType,view_name ViewName,version,is_system_template IsSystemTemplate,is_custom_template IsCustomTemplate,is_active IsActive,is_default IsDefault,supports_batch SupportsBatch,allows_manual_fields AllowsManualFields,display_order DisplayOrder from ged.label_template where id=@id and {Scope} and reg_status='A'",new{id,tenantId},cancellationToken:ct)); if(t is null)return null; var c=await db.QuerySingleOrDefaultAsync<LabelTemplateConfigDetails>(new CommandDefinition("select header_text HeaderText,logo_svg LogoSvg,primary_color PrimaryColor,secondary_color SecondaryColor,border_color BorderColor,text_color TextColor,accent_color AccentColor,page_size PageSize,label_width_mm LabelWidthMm,label_height_mm LabelHeightMm,labels_per_page LabelsPerPage,orientation,custom_css CustomCss,margin_top_mm MarginTopMm,margin_right_mm MarginRightMm,margin_bottom_mm MarginBottomMm,margin_left_mm MarginLeftMm from ged.label_template_config where template_id=@id and reg_status='A'",new{id},cancellationToken:ct))??new LabelTemplateConfigDetails(); var f=(await db.QueryAsync<LabelTemplateFieldItem>(new CommandDefinition("select id,field_key FieldKey,field_label FieldLabel,field_type FieldType,is_visible IsVisible,is_required IsRequired,is_editable IsEditable,default_value DefaultValue,display_order DisplayOrder,css_class CssClass from ged.label_template_field where template_id=@id and reg_status='A' order by display_order",new{id},cancellationToken:ct))).AsList(); return new(t,c,f); }
 private static async Task SaveConfigAndFields(IDbConnection db,IDbTransaction tx,Guid id,Guid tenantId,LabelTemplateEditCommand x,CancellationToken ct) { var c=x.Config; await db.ExecuteAsync(new CommandDefinition("""insert into ged.label_template_config(template_id,tenant_id,header_text,logo_svg,primary_color,secondary_color,border_color,text_color,accent_color,page_size,label_width_mm,label_height_mm,labels_per_page,orientation,custom_css,margin_top_mm,margin_right_mm,margin_bottom_mm,margin_left_mm) values(@id,@tenantId,@HeaderText,@LogoSvg,@PrimaryColor,@SecondaryColor,@BorderColor,@TextColor,@AccentColor,@PageSize,@LabelWidthMm,@LabelHeightMm,@LabelsPerPage,@Orientation,@CustomCss,@MarginTopMm,@MarginRightMm,@MarginBottomMm,@MarginLeftMm) on conflict(template_id) where reg_status='A' do update set header_text=excluded.header_text,logo_svg=excluded.logo_svg,primary_color=excluded.primary_color,secondary_color=excluded.secondary_color,border_color=excluded.border_color,text_color=excluded.text_color,accent_color=excluded.accent_color,page_size=excluded.page_size,label_width_mm=excluded.label_width_mm,label_height_mm=excluded.label_height_mm,labels_per_page=excluded.labels_per_page,orientation=excluded.orientation,custom_css=excluded.custom_css,margin_top_mm=excluded.margin_top_mm,margin_right_mm=excluded.margin_right_mm,margin_bottom_mm=excluded.margin_bottom_mm,margin_left_mm=excluded.margin_left_mm,updated_at=now()""",new{id,tenantId,c.HeaderText,c.LogoSvg,c.PrimaryColor,c.SecondaryColor,c.BorderColor,c.TextColor,c.AccentColor,c.PageSize,c.LabelWidthMm,c.LabelHeightMm,c.LabelsPerPage,c.Orientation,c.CustomCss,c.MarginTopMm,c.MarginRightMm,c.MarginBottomMm,c.MarginLeftMm},tx,cancellationToken:ct)); await db.ExecuteAsync(new CommandDefinition("update ged.label_template_field set reg_status='E',updated_at=now() where template_id=@id",new{id},tx,cancellationToken:ct)); foreach(var f in x.Fields) await db.ExecuteAsync(new CommandDefinition("insert into ged.label_template_field(template_id,field_key,field_label,field_type,is_visible,is_required,is_editable,default_value,display_order,css_class) values(@id,@FieldKey,@FieldLabel,@FieldType,@IsVisible,@IsRequired,@IsEditable,@DefaultValue,@DisplayOrder,@CssClass)",new{id,f.FieldKey,f.FieldLabel,f.FieldType,f.IsVisible,f.IsRequired,f.IsEditable,f.DefaultValue,f.DisplayOrder,f.CssClass},tx,cancellationToken:ct)); }
 private static void Validate(LabelTemplateEditCommand x) { x.Name=x.Name?.Trim()??""; x.Code=x.Code?.Trim().ToUpperInvariant()??""; if(x.Name.Length==0)throw new InvalidOperationException("Informe o nome do modelo."); if(!Regex.IsMatch(x.Code,"^[A-Z0-9_]{3,80}$"))throw new InvalidOperationException("Código interno inválido."); var svg=x.Config.LogoSvg??""; if(Regex.IsMatch(svg,@"<\s*script|on\w+\s*=|javascript:",RegexOptions.IgnoreCase))throw new InvalidOperationException("O SVG contém conteúdo não permitido."); foreach(var color in new[]{x.Config.PrimaryColor,x.Config.SecondaryColor,x.Config.BorderColor,x.Config.TextColor,x.Config.AccentColor}.Where(v=>!string.IsNullOrWhiteSpace(v))) if(!Regex.IsMatch(color!,"^#[0-9a-fA-F]{6}$")) throw new InvalidOperationException("Use cores no formato hexadecimal #RRGGBB."); var css=x.Config.CustomCss??""; if(Regex.IsMatch(css,"position\\s*:\\s*fixed|<\\s*script|url\\s*\\(\\s*['\"]?\\s*javascript:",RegexOptions.IgnoreCase))throw new InvalidOperationException("O CSS contém conteúdo não permitido."); if(x.Config.LabelsPerPage<1||x.Config.LabelsPerPage>100)throw new InvalidOperationException("Quantidade por página inválida."); }
 private static string NormalizeSubject(string value)=>value.Equals("DOCUMENT",StringComparison.OrdinalIgnoreCase)?"DOCUMENT":"BOX";
}
