-- Evolução 04.1.31: persistência aditiva, idempotente e isolada por tenant do Workspace Premium.
CREATE SCHEMA IF NOT EXISTS ged;
CREATE TABLE IF NOT EXISTS ged.user_workspace_preference (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,user_id uuid NOT NULL,sidebar_collapsed boolean NOT NULL DEFAULT false,density text NOT NULL DEFAULT 'comfortable',home_page text NULL,items_per_page integer NOT NULL DEFAULT 25,preview_open boolean NOT NULL DEFAULT true,reduce_motion boolean NOT NULL DEFAULT false,settings_json jsonb NOT NULL DEFAULT '{}'::jsonb,created_at_utc timestamptz NOT NULL DEFAULT now(),updated_at_utc timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS ged.user_favorite (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,user_id uuid NOT NULL,item_type text NOT NULL,item_key text NOT NULL,title text NOT NULL,target_url text NOT NULL,icon text NULL,sort_order integer NOT NULL DEFAULT 0,created_at_utc timestamptz NOT NULL DEFAULT now(),updated_at_utc timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id,item_type,item_key));
CREATE TABLE IF NOT EXISTS ged.user_recent_item (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,user_id uuid NOT NULL,item_type text NOT NULL,item_key text NOT NULL,title text NOT NULL,target_url text NOT NULL,icon text NULL,last_accessed_at_utc timestamptz NOT NULL DEFAULT now(),created_at_utc timestamptz NOT NULL DEFAULT now(),updated_at_utc timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id,item_type,item_key));
CREATE TABLE IF NOT EXISTS ged.user_saved_view (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,user_id uuid NOT NULL,module text NOT NULL,name text NOT NULL,configuration_json jsonb NOT NULL DEFAULT '{}'::jsonb,is_default boolean NOT NULL DEFAULT false,created_at_utc timestamptz NOT NULL DEFAULT now(),updated_at_utc timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,user_id,module,name));
CREATE TABLE IF NOT EXISTS ged.user_notification (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,user_id uuid NOT NULL,category text NOT NULL,title text NOT NULL,message text NOT NULL,status text NOT NULL DEFAULT 'UNREAD',target_url text NULL,payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,read_at_utc timestamptz NULL,archived_at_utc timestamptz NULL,created_at_utc timestamptz NOT NULL DEFAULT now(),updated_at_utc timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ged.user_activity (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,user_id uuid NOT NULL,activity_type text NOT NULL,title text NOT NULL,status text NOT NULL,progress smallint NULL,target_url text NULL,details_json jsonb NOT NULL DEFAULT '{}'::jsonb,started_at_utc timestamptz NULL,finished_at_utc timestamptz NULL,created_at_utc timestamptz NOT NULL DEFAULT now(),updated_at_utc timestamptz NOT NULL DEFAULT now(),CHECK(progress IS NULL OR progress BETWEEN 0 AND 100));
CREATE INDEX IF NOT EXISTS ix_workspace_favorite_user ON ged.user_favorite(tenant_id,user_id,sort_order);
CREATE INDEX IF NOT EXISTS ix_workspace_recent_user ON ged.user_recent_item(tenant_id,user_id,last_accessed_at_utc DESC);
CREATE INDEX IF NOT EXISTS ix_workspace_saved_view_user ON ged.user_saved_view(tenant_id,user_id,module);
CREATE INDEX IF NOT EXISTS ix_workspace_notification_user ON ged.user_notification(tenant_id,user_id,status,created_at_utc DESC);
CREATE INDEX IF NOT EXISTS ix_workspace_activity_user ON ged.user_activity(tenant_id,user_id,status,created_at_utc DESC);
