create schema if not exists ged;
create extension if not exists pgcrypto;
create table if not exists ged.smart_workflow_task(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,task_number varchar(40) not null,source_type varchar(80) not null,source_id uuid null,related_document_id uuid null,related_box_id uuid null,related_incident_id uuid null,related_suggestion_id uuid null,task_type varchar(80) not null,title text not null,description text null,recommended_action text null,priority varchar(30) not null default 'MEDIUM',status varchar(40) not null default 'OPEN',assigned_to uuid null,assigned_to_name text null,due_at timestamptz null,opened_by uuid null,opened_at timestamptz not null default now(),started_at timestamptz null,completed_by uuid null,completed_at timestamptz null,completion_notes text null,payload_json jsonb null,reg_status char(1) not null default 'A');
create table if not exists ged.smart_workflow_event(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,task_id uuid not null references ged.smart_workflow_task(id),event_type varchar(80) not null,event_message text not null,performed_by uuid null,performed_by_name text null,occurred_at timestamptz not null default now(),payload_json jsonb null,reg_status char(1) not null default 'A');
create table if not exists ged.smart_workflow_rule(id uuid primary key default gen_random_uuid(),tenant_id uuid null,rule_code varchar(80) not null,title text not null,description text null,source_type varchar(80) not null,task_type varchar(80) not null,priority varchar(30) not null default 'MEDIUM',sla_hours integer not null default 48,enabled boolean not null default true,payload_json jsonb null,created_at timestamptz not null default now(),reg_status char(1) not null default 'A');
create table if not exists ged.smart_workflow_dashboard_snapshot(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,open_tasks integer not null default 0,overdue_tasks integer not null default 0,critical_tasks integer not null default 0,completed_today integer not null default 0,generated_at timestamptz not null default now(),payload_json jsonb null,reg_status char(1) not null default 'A');
create unique index if not exists ux_smart_workflow_task_number on ged.smart_workflow_task(tenant_id,task_number) where reg_status='A';
create index if not exists ix_smart_workflow_task_status on ged.smart_workflow_task(tenant_id,status,priority,due_at);
create index if not exists ix_smart_workflow_task_source on ged.smart_workflow_task(tenant_id,source_type,source_id);
create index if not exists ix_smart_workflow_task_document on ged.smart_workflow_task(tenant_id,related_document_id);
create index if not exists ix_smart_workflow_event_task on ged.smart_workflow_event(task_id,occurred_at desc);
create unique index if not exists ux_smart_workflow_rule_code on ged.smart_workflow_rule(coalesce(tenant_id,'00000000-0000-0000-0000-000000000000'::uuid),rule_code) where reg_status='A';
insert into ged.smart_workflow_rule(rule_code,title,source_type,task_type,priority,sla_hours) values
('CLASSIFICATION_REVIEW','Revisar sugestão de classificação','document_classification_suggestion','CLASSIFICATION_SUGGESTION_REVIEW','MEDIUM',48),('RETENTION_REVIEW','Revisar sugestão de temporalidade','document_retention_suggestion','RETENTION_SUGGESTION_REVIEW','MEDIUM',48),('QUALITY_REVIEW','Revisar qualidade documental','document_quality_issue','QUALITY_ISSUE_REVIEW','MEDIUM',48),('SENSITIVE_REVIEW','Revisar indicador de dado sensível','document_ai_analysis','SENSITIVE_DATA_REVIEW','HIGH',8),('INCIDENT_REVIEW','Revisar incidente prioritário','system_incident','INCIDENT_REVIEW','HIGH',8),('ASSISTANT_REVIEW','Revisar ação do assistente','smart_assistant_action_suggestion','ASSISTANT_ACTION_REVIEW','MEDIUM',48) on conflict do nothing;
