-- Valora Insight™ public/commercial foundation. Idempotent and non-destructive.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS commercial_plans (code varchar(24) PRIMARY KEY,name varchar(80) NOT NULL,monthly_price numeric(12,2) NOT NULL DEFAULT 0,diagnostics_limit integer NOT NULL,responses_limit integer NOT NULL,reports varchar(80) NOT NULL,certificates varchar(80) NOT NULL,intelligence varchar(80) NOT NULL,benchmark varchar(80) NOT NULL,units varchar(40) NOT NULL,users varchar(40) NOT NULL,integrations varchar(80) NOT NULL,support varchar(80) NOT NULL,is_active boolean NOT NULL DEFAULT true,display_order integer NOT NULL DEFAULT 0);
INSERT INTO commercial_plans VALUES
('FREE','Grátis',0,1,100,'Essencial','Não','Não','Não','1','1','Não','Base de conhecimento',true,1),
('START','Start',297,3,500,'Executivo','Sim','Assistida','Setorial','1','3','Não','E-mail',true,2),
('GROWTH','Growth',697,10,2500,'Completo','Sim','Avançada','Comparativo','3','10','API','Prioritário',true,3),
('ENTERPRISE','Enterprise',0,2147483647,2147483647,'Sob medida','Sim','Avançada','Customizado','Ilimitadas','Ilimitados','Completas','Consultivo',true,4)
ON CONFLICT (code) DO NOTHING;
CREATE TABLE IF NOT EXISTS commercial_organizations(id uuid PRIMARY KEY,name varchar(160) NOT NULL,cnpj varchar(14),tenant_code varchar(80) NOT NULL UNIQUE,onboarding_status varchar(24) NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS ux_commercial_organizations_cnpj ON commercial_organizations(cnpj) WHERE cnpj IS NOT NULL;
CREATE TABLE IF NOT EXISTS commercial_users(id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES commercial_organizations(id),name varchar(120) NOT NULL,normalized_email varchar(180) NOT NULL UNIQUE,email varchar(180) NOT NULL,phone varchar(30) NOT NULL,job_title varchar(80) NOT NULL,password_hash text NOT NULL,role varchar(40) NOT NULL,email_confirmed boolean NOT NULL DEFAULT false,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS trial_subscriptions(id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES commercial_organizations(id),plan_code varchar(24) NOT NULL REFERENCES commercial_plans(code),status varchar(20) NOT NULL CHECK(status IN('trialing','active','expired','cancelled')),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_trial_subscriptions_status_end ON trial_subscriptions(status,ends_at);
CREATE TABLE IF NOT EXISTS commercial_leads(id uuid PRIMARY KEY,name varchar(120) NOT NULL,company varchar(160) NOT NULL,email varchar(180) NOT NULL,phone varchar(30) NOT NULL,job_title varchar(80) NOT NULL,company_size varchar(40) NOT NULL,main_interest varchar(80) NOT NULL,message varchar(1200),status varchar(20) NOT NULL DEFAULT 'new' CHECK(status IN('new','contacted','converted','lost')),origin varchar(40) NOT NULL,ip_address varchar(64),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz);
CREATE INDEX IF NOT EXISTS ix_commercial_leads_status_created ON commercial_leads(status,created_at DESC);
CREATE TABLE IF NOT EXISTS lead_notes(id uuid PRIMARY KEY,lead_id uuid NOT NULL REFERENCES commercial_leads(id) ON DELETE CASCADE,note text NOT NULL,created_by uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public_signup_attempts(id uuid PRIMARY KEY,email varchar(180) NOT NULL,ip_address varchar(64),succeeded boolean NOT NULL,error_code varchar(80),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS email_confirmations(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES commercial_users(id),token_hash char(64) NOT NULL UNIQUE,expires_at timestamptz NOT NULL,used_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS password_reset_tokens(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES commercial_users(id),token_hash char(64) NOT NULL UNIQUE,expires_at timestamptz NOT NULL,used_at timestamptz,requested_ip varchar(64),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS onboarding_states(id uuid PRIMARY KEY,organization_id uuid NOT NULL REFERENCES commercial_organizations(id),user_id uuid NOT NULL REFERENCES commercial_users(id),current_step varchar(40) NOT NULL,status varchar(20) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);
CREATE TABLE IF NOT EXISTS commercial_events(id uuid PRIMARY KEY,organization_id uuid,event_type varchar(80) NOT NULL,payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commercial_outbox(id uuid PRIMARY KEY,event_type varchar(80) NOT NULL,recipient varchar(180) NOT NULL,payload jsonb NOT NULL,status varchar(20) NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz);
CREATE TABLE IF NOT EXISTS canonical_permissions(code varchar(80) PRIMARY KEY,description varchar(180) NOT NULL);
INSERT INTO canonical_permissions(code,description) VALUES ('leads.read','Consultar leads'),('leads.manage','Gerenciar leads'),('trials.read','Consultar trials'),('trials.manage','Gerenciar trials'),('commercial.read','Consultar operação comercial'),('commercial.manage','Gerenciar operação comercial'),('onboarding.read','Consultar onboarding'),('onboarding.manage','Gerenciar onboarding') ON CONFLICT(code) DO NOTHING;
