create schema if not exists ged;
create extension if not exists pgcrypto;
create table if not exists ged.archive_service_catalog(id uuid primary key default gen_random_uuid(),tenant_id uuid null,code varchar(80) not null,name text not null,description text null,unit varchar(40) not null default 'UST',unit_price numeric(18,4) not null default 0,default_ust_quantity numeric(18,4) not null default 1,calculation_rule varchar(80) not null default 'MANUAL',is_active boolean not null default true,display_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz null,reg_status char(1) not null default 'A');
create table if not exists ged.archive_productivity_entry(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,service_catalog_id uuid not null references ged.archive_service_catalog(id),competence_month date not null,performed_at timestamptz not null default now(),performed_by uuid null,team_id uuid null,sector_id uuid null,source_type varchar(80) null,source_id uuid null,subject_type varchar(40) null,subject_id uuid null,box_id uuid null,document_id uuid null,work_order_id uuid null,inventory_session_id uuid null,label_print_history_id uuid null,quantity numeric(18,4) not null default 1,ust_quantity numeric(18,4) not null default 0,unit_price numeric(18,4) not null default 0,total_amount numeric(18,4) not null default 0,status varchar(40) not null default 'DRAFT',notes text null,created_by uuid null,created_at timestamptz not null default now(),approved_by uuid null,approved_at timestamptz null,rejected_by uuid null,rejected_at timestamptz null,rejection_reason text null,reg_status char(1) not null default 'A');
create table if not exists ged.archive_billing_period(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,competence_month date not null,status varchar(40) not null default 'OPEN',total_entries integer not null default 0,total_quantity numeric(18,4) not null default 0,total_ust numeric(18,4) not null default 0,total_amount numeric(18,4) not null default 0,opened_by uuid null,opened_at timestamptz not null default now(),closed_by uuid null,closed_at timestamptz null,approved_by uuid null,approved_at timestamptz null,notes text null,reg_status char(1) not null default 'A');
create table if not exists ged.archive_productivity_audit(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,entity_type varchar(40) not null,entity_id uuid not null,action varchar(80) not null,performed_by uuid null,performed_at timestamptz not null default now(),before_snapshot jsonb null,after_snapshot jsonb null,notes text null);
create unique index if not exists ux_archive_service_catalog_code on ged.archive_service_catalog(coalesce(tenant_id,'00000000-0000-0000-0000-000000000000'::uuid),code);
create index if not exists ix_archive_productivity_entry_competence on ged.archive_productivity_entry(tenant_id,competence_month,status);
create index if not exists ix_archive_productivity_entry_performed_by on ged.archive_productivity_entry(tenant_id,performed_by,performed_at desc);
create index if not exists ix_archive_productivity_entry_source on ged.archive_productivity_entry(tenant_id,source_type,source_id);
create unique index if not exists ux_archive_productivity_entry_source on ged.archive_productivity_entry(tenant_id,source_type,source_id,service_catalog_id) where reg_status='A' and source_id is not null;
create unique index if not exists ux_archive_billing_period_tenant_month on ged.archive_billing_period(tenant_id,competence_month) where reg_status='A';
insert into ged.archive_service_catalog(code,name,calculation_rule,display_order) values
('GESTAO_DOCUMENTAL','Serviços de Gestão Documental','PER_ITEM',10),('ADMINISTRACAO_BANCO_DADOS','Administração de Banco de Dados','PER_ITEM',20),('IMPLANTACAO','Diagnóstico, migração, adaptação e implantação','PER_ITEM',30),('GUARDA_FISICA_ADMINISTRATIVA','Guarda física de documentos administrativos','PER_BOX',40),('GUARDA_FISICA_MEDICA','Guarda física de documentos médicos','PER_BOX',50),('TRATAMENTO_ARQUIVISTICO','Tratamento arquivístico completo','PER_ITEM',60),('DIGITALIZACAO_OCR','Digitalização com OCR e inserção no GED','PER_PAGE',70),('INDEXACAO_DOCUMENTAL','Indexação documental com metadados estruturados','PER_ITEM',80),('SOLICITACAO_ENTREGA','Solicitação e entrega de documentos físicos','PER_ITEM',90),('ELIMINACAO_TECNICA','Eliminação técnica com certificação','PER_ITEM',100),('GUARDA_DIGITAL','Guarda digital em nuvem','PER_ITEM',110),('DICOM_NUVEM','Visualização DICOM em nuvem','PER_ITEM',120),('IMPRESSAO_ETIQUETA_PADRAO','Impressão de etiqueta','PER_PRINT',130),('IMPRESSAO_ETIQUETA_PERSONALIZADA','Reimpressão de etiqueta','PER_PRINT',140),('INVENTARIO_ETIQUETA','Inventário físico por etiqueta','PER_INVENTORY_ITEM',150),('CONFERENCIA_CAIXA','Conferência física de caixa','PER_BOX',160),('MOVIMENTACAO_FISICA','Movimentação física de caixa/documento','PER_ITEM',170),('SANEAMENTO_RECONCILIACAO','Saneamento e reconciliação de acervo','PER_ITEM',180),('ORDEM_SERVICO_EXECUTADA','Ordem de serviço executada','PER_WORK_ORDER',190) on conflict do nothing;
