create extension if not exists pgcrypto;
create schema if not exists ged;
create table if not exists ged.contract_fiscalization_period(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,competence_month date not null,contract_number text,contractor_name text,contracting_unit text,fiscal_user_id uuid,manager_user_id uuid,status varchar(40) not null default 'DRAFT',total_measured_amount numeric(18,4) not null default 0,total_approved_amount numeric(18,4) not null default 0,total_glossed_amount numeric(18,4) not null default 0,total_ust numeric(18,4) not null default 0,total_items integer not null default 0,opened_by uuid,opened_at timestamptz not null default now(),submitted_by uuid,submitted_at timestamptz,approved_by uuid,approved_at timestamptz,rejected_by uuid,rejected_at timestamptz,rejection_reason text,closed_by uuid,closed_at timestamptz,notes text,reg_status char(1) not null default 'A');
create table if not exists ged.contract_fiscalization_item(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,fiscalization_period_id uuid not null references ged.contract_fiscalization_period(id),productivity_entry_id uuid,service_catalog_id uuid,service_code varchar(80),service_name text not null,unit varchar(40) not null default 'UST',measured_quantity numeric(18,4) not null default 0,measured_ust numeric(18,4) not null default 0,unit_price numeric(18,4) not null default 0,measured_amount numeric(18,4) not null default 0,approved_quantity numeric(18,4) not null default 0,approved_ust numeric(18,4) not null default 0,approved_amount numeric(18,4) not null default 0,glossed_quantity numeric(18,4) not null default 0,glossed_amount numeric(18,4) not null default 0,status varchar(40) not null default 'PENDING_REVIEW',source_type varchar(80),source_id uuid,evidence_count integer not null default 0,fiscal_notes text,contractor_notes text,reviewed_by uuid,reviewed_at timestamptz,reg_status char(1) not null default 'A');
create table if not exists ged.contract_fiscalization_glosa(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,fiscalization_item_id uuid not null references ged.contract_fiscalization_item(id),glosa_type varchar(60) not null,reason text not null,glossed_quantity numeric(18,4) not null default 0,glossed_amount numeric(18,4) not null default 0,status varchar(40) not null default 'OPEN',created_by uuid,created_at timestamptz not null default now(),contractor_response text,responded_by uuid,responded_at timestamptz,resolved_by uuid,resolved_at timestamptz,resolution_notes text,reg_status char(1) not null default 'A');
create table if not exists ged.contract_fiscalization_evidence(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,fiscalization_period_id uuid not null references ged.contract_fiscalization_period(id),fiscalization_item_id uuid references ged.contract_fiscalization_item(id),source_type varchar(80),source_id uuid,evidence_type varchar(60) not null default 'LINK',title text not null,description text,file_path text,external_url text,payload_json jsonb,attached_by uuid,attached_at timestamptz not null default now(),reg_status char(1) not null default 'A');
create table if not exists ged.contract_fiscalization_event(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,fiscalization_period_id uuid not null references ged.contract_fiscalization_period(id),fiscalization_item_id uuid,event_type varchar(80) not null,event_title text not null,event_description text,from_status varchar(40),to_status varchar(40),performed_by uuid,performed_at timestamptz not null default now(),ip_address inet,user_agent text,payload_json jsonb,reg_status char(1) not null default 'A');
create unique index if not exists ux_contract_fiscalization_period_tenant_month on ged.contract_fiscalization_period(tenant_id,competence_month) where reg_status='A';
create index if not exists ix_contract_fiscalization_period_status on ged.contract_fiscalization_period(tenant_id,status,competence_month desc); create index if not exists ix_contract_fiscalization_item_period on ged.contract_fiscalization_item(tenant_id,fiscalization_period_id,status); create index if not exists ix_contract_fiscalization_item_source on ged.contract_fiscalization_item(tenant_id,source_type,source_id); create index if not exists ix_contract_fiscalization_glosa_item on ged.contract_fiscalization_glosa(tenant_id,fiscalization_item_id,status); create index if not exists ix_contract_fiscalization_evidence_period on ged.contract_fiscalization_evidence(tenant_id,fiscalization_period_id); create index if not exists ix_contract_fiscalization_event_period on ged.contract_fiscalization_event(tenant_id,fiscalization_period_id,performed_at desc);
