-- Labels Visual Designer 2.0: estrutura tenant-aware, versões, validações e auditoria.
create schema if not exists ged;
create extension if not exists pgcrypto;
create table if not exists ged.label_template_design(id uuid primary key default gen_random_uuid(),tenant_id uuid null,template_code text not null,template_name text not null,description text null,subject_type varchar(40) not null,print_mode varchar(40) not null default 'CUSTOM',view_name text null,status varchar(40) not null default 'DRAFT',width_mm numeric(8,2) not null default 100,height_mm numeric(8,2) not null default 145,paper_size varchar(40) not null default 'A4',orientation varchar(40) not null default 'PORTRAIT',is_system_template boolean not null default false,base_template_code text null,current_version integer not null default 1,design_json jsonb null,created_by uuid null,created_at timestamptz not null default now(),updated_at timestamptz null,reg_status char(1) not null default 'A',constraint ck_label_design_status check(status in('DRAFT','PUBLISHED','ARCHIVED')),constraint ck_label_design_dimensions check(width_mm>0 and height_mm>0));
create table if not exists ged.label_template_design_field(id uuid primary key default gen_random_uuid(),tenant_id uuid null,template_design_id uuid not null references ged.label_template_design(id),field_key text not null,field_label text not null,field_type varchar(40) not null default 'TEXT',data_source text null,x_mm numeric(8,2) not null default 0,y_mm numeric(8,2) not null default 0,width_mm numeric(8,2) not null default 30,height_mm numeric(8,2) not null default 8,font_size_pt numeric(8,2) not null default 9,font_weight varchar(40) null,text_align varchar(40) not null default 'LEFT',color text null,is_required boolean not null default false,is_printable boolean not null default true,display_order integer not null default 0,created_at timestamptz not null default now(),reg_status char(1) not null default 'A');
create table if not exists ged.label_template_design_version(id uuid primary key default gen_random_uuid(),tenant_id uuid null,template_design_id uuid not null references ged.label_template_design(id),version_number integer not null,status varchar(40) not null default 'PUBLISHED',snapshot_json jsonb not null,published_by uuid null,published_at timestamptz not null default now(),notes text null,reg_status char(1) not null default 'A');
create table if not exists ged.label_template_design_validation(id uuid primary key default gen_random_uuid(),tenant_id uuid null,template_design_id uuid not null references ged.label_template_design(id),validation_type varchar(80) not null,severity varchar(30) not null default 'MEDIUM',title text not null,description text null,recommended_action text null,status varchar(40) not null default 'OPEN',created_at timestamptz not null default now(),reg_status char(1) not null default 'A');
create table if not exists ged.label_template_design_audit(id uuid primary key default gen_random_uuid(),tenant_id uuid null,template_design_id uuid not null references ged.label_template_design(id),event_type varchar(80) not null,template_code text not null,user_id uuid null,created_at timestamptz not null default now());
create unique index if not exists ux_label_template_design_code on ged.label_template_design(coalesce(tenant_id,'00000000-0000-0000-0000-000000000000'::uuid),template_code) where reg_status='A';
create unique index if not exists ux_label_template_design_field on ged.label_template_design_field(template_design_id,field_key) where reg_status='A';
create unique index if not exists ux_label_template_design_version on ged.label_template_design_version(template_design_id,version_number) where reg_status='A';
create index if not exists ix_label_template_design_validation on ged.label_template_design_validation(template_design_id,severity,status) where reg_status='A';
create index if not exists ix_label_template_design_audit on ged.label_template_design_audit(tenant_id,template_design_id,created_at desc);

insert into ged.label_template_design(template_code,template_name,description,subject_type,print_mode,view_name,status,width_mm,height_mm,is_system_template,current_version,design_json)
values
('FACTORY_BOX_V1','Padrão do Sistema - Caixa','Etiqueta oficial para caixas físicas.','BOX','FACTORY','BoxLabel','PUBLISHED',100,70,true,1,'{"border":true}'),
('FACTORY_DOCUMENT_V1','Padrão do Sistema - Documento/Pasta','Etiqueta oficial para documentos e pastas.','DOCUMENT','FACTORY','DocumentLabel','PUBLISHED',100,70,true,1,'{"border":true}'),
('LOCDESK_CAIXA_V1','LocDesk - Caixa','Modelo oficial LocDesk para caixas.','BOX','CUSTOM','LocDeskBoxLabel','PUBLISHED',174,110,true,1,'{"border":true}'),
('LOCDESK_PASTA_V1','LocDesk - Pasta','Modelo oficial LocDesk para pastas.','DOCUMENT','CUSTOM','LocDeskFolderLabel','PUBLISHED',174,110,true,1,'{"border":true}'),
('LOCDESK_PASTA_HOL_V1','LocDesk - Pasta HOL','Modelo oficial fiel do Hospital Ophir Loyola.','DOCUMENT','CUSTOM','LocDeskFolderHolLabel','PUBLISHED',174,110,true,1,'{"border":true}')
on conflict do nothing;

-- Campos oficiais mínimos; o texto histórico do LocDesk permanece deliberadamente inalterado.
with templates as(select id,template_code from ged.label_template_design where tenant_id is null and is_system_template and reg_status='A'), fields(template_code,field_key,field_label,field_type,x,y,w,h,fs,required,ord) as(values
('LOCDESK_PASTA_V1','ARQUIVO','ARQUIVO LOCDESCK ANANINDEUA','TEXT',5,4,164,10,11,true,1),('LOCDESK_PASTA_V1','CONTROLE','N° de Controle','DYNAMIC',5,16,55,10,10,true,2),('LOCDESK_PASTA_V1','VOLUME','Volume','DYNAMIC',65,16,35,10,10,true,3),('LOCDESK_PASTA_V1','LOCALIZACAO','LOCALIZAÇÃO','DYNAMIC',5,88,120,14,11,true,4),('LOCDESK_PASTA_V1','QRCODE','QR Code','QRCODE',145,84,22,22,8,false,5),
('LOCDESK_PASTA_HOL_V1','BORDA','Borda ativa','LINE',1,1,172,108,8,true,1),('LOCDESK_PASTA_HOL_V1','CONTRATO','Contrato: Hospital Ophir Loyola','TEXT',5,5,164,10,10,true,2),('LOCDESK_PASTA_HOL_V1','CONTROLE','N° Controle','DYNAMIC',5,17,55,10,11,true,3),('LOCDESK_PASTA_HOL_V1','ASSUNTO','Assunto','DYNAMIC',5,31,164,14,9,true,4),('LOCDESK_PASTA_HOL_V1','CLASSIFICACAO','Classificação','DYNAMIC',5,48,164,14,9,true,5),('LOCDESK_PASTA_HOL_V1','LOCALIZACAO','LOCALIZAÇÃO','DYNAMIC',5,88,164,14,11,true,6),
('LOCDESK_CAIXA_V1','ARQUIVO','ARQUIVO LOCDESCK ANANINDEUA','TEXT',5,4,164,10,11,true,1),('LOCDESK_CAIXA_V1','CONTROLE','N° de Controle','DYNAMIC',5,16,55,10,10,true,2),('LOCDESK_CAIXA_V1','VOLUME','Volume','DYNAMIC',65,16,35,10,10,true,3),('LOCDESK_CAIXA_V1','LOCALIZACAO','LOCALIZAÇÃO','DYNAMIC',5,88,164,14,11,true,4),
('FACTORY_BOX_V1','CONTROLE','Nº de Controle','DYNAMIC',5,5,90,12,11,true,1),('FACTORY_BOX_V1','LOCALIZACAO','Localização','DYNAMIC',5,50,90,12,10,true,2),('FACTORY_DOCUMENT_V1','CONTROLE','Nº de Controle','DYNAMIC',5,5,90,12,11,true,1),('FACTORY_DOCUMENT_V1','ASSUNTO','Assunto','DYNAMIC',5,22,90,18,9,true,2))
insert into ged.label_template_design_field(template_design_id,field_key,field_label,field_type,x_mm,y_mm,width_mm,height_mm,font_size_pt,is_required,display_order)
select t.id,f.field_key,f.field_label,f.field_type,f.x,f.y,f.w,f.h,f.fs,f.required,f.ord from templates t join fields f using(template_code) on conflict do nothing;
