using System.Data;
using System.Text.RegularExpressions;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.HospitalIntelligence;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;

namespace InovaGed.Infrastructure.HospitalIntelligence;

public sealed class HospitalIntelligenceService : IHospitalIntelligenceService
{
    private static readonly Regex MoneyRegex = new(@"(R\$\s?\d{1,3}(\.\d{3})*,\d{2}|\b\d{1,3}(\.\d{3})*,\d{2}\b)", RegexOptions.Compiled | RegexOptions.IgnoreCase);
    private readonly IDbConnectionFactory _db; private readonly IMemoryCache _cache; private readonly ILogger<HospitalIntelligenceService> _logger;
    public HospitalIntelligenceService(IDbConnectionFactory db, IMemoryCache cache, ILogger<HospitalIntelligenceService> logger) { _db = db; _cache = cache; _logger = logger; }
    public async Task<HospitalIntelligenceDashboardDto> GetDashboardAsync(HospitalIntelligenceFilter f, CancellationToken ct){var key=$"HospitalIntelligence:{f.TenantId}:{f.From:yyyyMMdd}:{f.To:yyyyMMdd}:{f.FolderId}:{f.Sector}:{f.DocumentType}:{f.Search}"; if(!f.BypassCache && _cache.TryGetValue(key,out HospitalIntelligenceDashboardDto? c)&&c is not null) return c; await using var conn=await _db.OpenAsync(ct); var exists=await TableExistsAsync(conn,"ged","document_search",ct); if(!exists) return new HospitalIntelligenceDashboardDto{Warning="Texto OCR ainda não indexado para inteligência."}; var total=await conn.ExecuteScalarAsync<int>(new CommandDefinition("select count(*) from ged.document where tenant_id=@t", new{t=f.TenantId},cancellationToken:ct)); var withOcr=await conn.ExecuteScalarAsync<int>(new CommandDefinition("select count(distinct d.id) from ged.document d join ged.document_search s on s.document_id=d.id and s.tenant_id=d.tenant_id where d.tenant_id=@t and coalesce(s.ocr_text,'')<>''", new{t=f.TenantId},cancellationToken:ct)); var terms=await GetClinicalTermsAsync(f,ct); var fins=await GetFinancialSignalsAsync(f,ct); var ops=await GetOperationalSignalsAsync(f,ct); var alerts=await GetCriticalAlertsAsync(f,ct); var dto=new HospitalIntelligenceDashboardDto{TotalDocuments=total,DocumentsWithOcr=withOcr,DocumentsWithoutOcr=Math.Max(0,total-withOcr),OcrPending=Math.Max(0,total-withOcr),UnclassifiedDocuments=0,CriticalDocuments=alerts.Count,ClinicalTerms=terms,FinancialSignals=fins,OperationalSignals=ops,Alerts=alerts,Cards=[new(){Title="Documentos analisados",Value=total.ToString(),Color="primary",Icon="bi-files"},new(){Title="Documentos com OCR",Value=withOcr.ToString(),Color="success",Icon="bi-file-earmark-check"},new(){Title="OCR pendente",Value=Math.Max(0,total-withOcr).ToString(),Color="warning",Icon="bi-hourglass-split"},new(){Title="Alertas críticos",Value=alerts.Count(a=>a.RiskLevel=="Crítico").ToString(),Color="danger",Icon="bi-exclamation-triangle"},new(){Title="Possíveis documentos financeiros",Value=fins.Sum(x=>x.Count).ToString(),Color="info",Icon="bi-cash"},new(){Title="Termos clínicos encontrados",Value=terms.Sum(x=>x.Count).ToString(),Color="secondary",Icon="bi-heart-pulse"}]}; _cache.Set(key,dto,TimeSpan.FromMinutes(5)); return dto; }
    public async Task<IReadOnlyList<TermOccurrenceDto>> GetClinicalTermsAsync(HospitalIntelligenceFilter f, CancellationToken ct){ var map=new Dictionary<string,string[]>{{"NEOPLASIA",["neoplasia","câncer","tumor","oncologia","quimioterapia","radioterapia","biópsia","metástase"]},{"EMERGÊNCIA",["sepse","uti","intubação","hemorragia","óbito","avc","iam"]}}; var docs=await LoadTextRows(f,ct); return BuildTermList(docs,map,f.Top); }
    public async Task<IReadOnlyList<FinancialSignalDto>> GetFinancialSignalsAsync(HospitalIntelligenceFilter f, CancellationToken ct){ var map=new Dictionary<string,string[]>{{"Financeiro",["nota fiscal","contrato","glosa","faturamento","pagamento","convênio","sus","cobrança","opme"]}}; var docs=await LoadTextRows(f,ct); var terms=BuildTermList(docs,map,20); var list=terms.Select(t=>new FinancialSignalDto{Indicator=t.Term,Count=t.Count,Description="Sinal financeiro detectado via OCR",RiskLevel=t.RiskLevel,Documents=t.Examples}).ToList(); var money=docs.Sum(d=>MoneyRegex.Matches(d.Text).Count); list.Add(new FinancialSignalDto{Indicator="Valores monetários detectados",Count=money,Description="Detecção automática por regex; requer validação.",RiskLevel=money>0?"Médio":"Baixo"}); return list; }
    public async Task<IReadOnlyList<OperationalSignalDto>> GetOperationalSignalsAsync(HospitalIntelligenceFilter f, CancellationToken ct){ var d=await GetDashboardAsync(new HospitalIntelligenceFilter{TenantId=f.TenantId,BypassCache=f.BypassCache},ct); return [new(){Indicator="OCR pendente",Count=d.OcrPending,Description="Documentos sem OCR concluído.",Recommendation="Priorizar processamento OCR.",RiskLevel=d.OcrPending>100?"Alto":"Médio"},new(){Indicator="Sem classificação",Count=d.UnclassifiedDocuments,Description="Documentos sem tipo definido.",Recommendation="Executar rotina de classificação.",RiskLevel="Médio"}]; }
    public async Task<IReadOnlyList<DocumentAlertDto>> GetCriticalAlertsAsync(HospitalIntelligenceFilter f, CancellationToken ct){ var terms=await GetClinicalTermsAsync(f,ct); var high=terms.Where(x=>x.RiskLevel is "Alto" or "Crítico").Take(10).ToList(); return high.SelectMany(h=>h.Examples.Take(1).Select(e=>new DocumentAlertDto{DocumentId=e.DocumentId,VersionId=e.VersionId,Title=e.Title,Folder=e.Folder,AlertType="Recorrência de termo crítico",Description=$"Termo '{h.Term}' recorrente.",RiskLevel=h.RiskLevel,CreatedAt=e.CreatedAt})).ToList(); }

    private async Task<List<(Guid DocumentId,string Title,string Folder,DateTime? CreatedAt,string Text)>> LoadTextRows(HospitalIntelligenceFilter f, CancellationToken ct){ await using var conn=await _db.OpenAsync(ct); if(!await TableExistsAsync(conn,"ged","document_search",ct) || !await ColumnExistsAsync(conn,"ged","document_search","ocr_text",ct)) return []; var sql=@"select d.id as DocumentId, coalesce(d.title,'Sem título') as Title, coalesce(f.name,'Sem pasta') as Folder, d.created_at as CreatedAt, s.ocr_text as Text from ged.document d join ged.document_search s on s.document_id=d.id and s.tenant_id=d.tenant_id left join ged.folder f on f.id=d.folder_id where d.tenant_id=@TenantId and coalesce(s.ocr_text,'')<>'' order by d.created_at desc limit 1000"; var rows=await conn.QueryAsync<(Guid,string,string,DateTime?,string)>(new CommandDefinition(sql,new{f.TenantId},cancellationToken:ct)); return rows.Select(r=>(r.Item1,r.Item2,r.Item3,r.Item4,MaskSensitive(r.Item5))).ToList(); }
    private static List<TermOccurrenceDto> BuildTermList(List<(Guid DocumentId,string Title,string Folder,DateTime? CreatedAt,string Text)> docs, Dictionary<string,string[]> map, int top){ var result=new List<TermOccurrenceDto>(); foreach(var kv in map) foreach(var term in kv.Value){ var matched=docs.Where(d=>d.Text.Contains(term,StringComparison.OrdinalIgnoreCase)).Take(5).ToList(); if(!matched.Any()) continue; var count=docs.Count(d=>d.Text.Contains(term,StringComparison.OrdinalIgnoreCase)); result.Add(new TermOccurrenceDto{Category=kv.Key,Term=term,Count=count,DocumentCount=matched.Count,Percentage=docs.Count==0?0:Math.Round((decimal)count*100/docs.Count,2),RiskLevel=count>20?"Crítico":count>10?"Alto":count>3?"Médio":"Baixo",Examples=matched.Select(m=>new DocumentReferenceDto{DocumentId=m.DocumentId,Title=m.Title,Folder=m.Folder,CreatedAt=m.CreatedAt,Snippet=ExtractSnippet(m.Text,term)}).ToList()}); } return result.OrderByDescending(x=>x.Count).Take(top).ToList(); }
    private static string ExtractSnippet(string text,string term){ var idx=text.IndexOf(term,StringComparison.OrdinalIgnoreCase); if(idx<0) return "Trecho indisponível."; var start=Math.Max(0,idx-40); var len=Math.Min(120,text.Length-start); return text.Substring(start,len); }
    private static string MaskSensitive(string text)=>Regex.Replace(text,@"\b\d{3}\.\d{3}\.\d{3}-\d{2}\b","***.***.***-**");
    private static async Task<bool> TableExistsAsync(IDbConnection conn,string schema,string table,CancellationToken ct)=>await conn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from information_schema.tables where table_schema=@schema and table_name=@table)",new{schema,table},cancellationToken:ct));
    private static async Task<bool> ColumnExistsAsync(IDbConnection conn,string schema,string table,string column,CancellationToken ct)=>await conn.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from information_schema.columns where table_schema=@schema and table_name=@table and column_name=@column)",new{schema,table,column},cancellationToken:ct));
}
