namespace InovaGed.Application.DocumentGuardian.Rules;

public sealed record GuardianRuleDefinition(string Code, int Version, string Severity, string Category, string Description, string Recommendation);

public static class DocumentGuardianRules
{
    public static readonly IReadOnlyList<GuardianRuleDefinition> All = new[]
    {
        R("GED-001","MEDIUM","QUALIDADE","Documento sem classificação","Classificar o documento."), R("GED-002","MEDIUM","QUALIDADE","Documento elegível sem OCR","Executar OCR."), R("GED-003","MEDIUM","QUALIDADE","Documento suportado sem preview","Gerar preview."), R("GED-004","HIGH","QUALIDADE","Possível duplicidade por hash","Revisar duplicidade."), R("GED-005","MEDIUM","QUALIDADE","Mesmo nome com conteúdo diferente","Revisar nomenclatura."), R("GED-006","MEDIUM","QUALIDADE","Documento sem tipo documental","Definir tipo documental."), R("GED-007","HIGH","QUALIDADE","Metadados obrigatórios incompletos","Completar metadados."), R("GED-008","CRITICAL","QUALIDADE","Arquivo físico ausente no storage","Restaurar arquivo."), R("GED-009","CRITICAL","QUALIDADE","Hash divergente","Verificar integridade."), R("GED-010","MEDIUM","QUALIDADE","Preview desatualizado em relação à versão atual","Regenerar preview."),
        R("ARQ-001","HIGH","ARQUIVISTICA","Documento sem temporalidade","Vincular temporalidade."), R("ARQ-002","HIGH","ARQUIVISTICA","Prazo vencido sem destinação","Iniciar destinação."), R("ARQ-003","HIGH","ARQUIVISTICA","Documento elegível para eliminação com impedimento ativo","Revisar impedimentos."), R("ARQ-004","MEDIUM","ARQUIVISTICA","Classe inativa utilizada","Reclassificar."), R("ARQ-005","MEDIUM","ARQUIVISTICA","Alteração de TTD exigindo recálculo","Recalcular temporalidade."), R("ARQ-006","MEDIUM","ARQUIVISTICA","Documento sem evento inicial de contagem","Registrar evento inicial."),
        R("SEC-001","HIGH","SEGURANCA","Tentativas negadas recorrentes","Revisar permissões e tentativas."), R("SEC-002","HIGH","SEGURANCA","Volume incomum de downloads","Investigar downloads."), R("SEC-003","MEDIUM","SEGURANCA","Acesso fora do padrão de horário","Revisar acesso."), R("SEC-004","HIGH","SEGURANCA","Acesso emergencial aguardando revisão","Revisar quebra de vidro."), R("LGPD-001","CRITICAL","LGPD","Documento sensível sem sigilo","Aplicar sigilo."), R("LGPD-002","HIGH","LGPD","Compartilhamento externo expirado ainda ativo","Revogar compartilhamento."), R("LGPD-003","HIGH","LGPD","Documento sensível sem responsável definido","Definir responsável."), R("LGPD-004","HIGH","LGPD","Retenção superior à regra sem justificativa","Justificar retenção."),
        R("OPS-001","MEDIUM","OPERACAO","OCR com falha recorrente","Reprocessar OCR."), R("OPS-002","MEDIUM","OPERACAO","Preview com falha recorrente","Reprocessar preview."), R("OPS-003","MEDIUM","OPERACAO","Upload incompleto ou abandonado","Retomar ou cancelar upload."), R("OPS-004","HIGH","OPERACAO","Integração PACS com item em quarentena","Tratar quarentena."), R("OPS-005","MEDIUM","OPERACAO","Documento sem pasta válida","Mover para pasta válida."), R("OPS-006","HIGH","OPERACAO","Documento aguardando ação acima do SLA","Escalonar SLA."),
        R("PHY-001","MEDIUM","ACERVO_FISICO","Documento físico sem localização","Registrar localização."), R("PHY-002","MEDIUM","ACERVO_FISICO","Caixa sem localização válida","Atualizar caixa."), R("PHY-003","HIGH","ACERVO_FISICO","Documento emprestado em atraso","Cobrar devolução."), R("PHY-004","HIGH","ACERVO_FISICO","Item físico solicitado e não localizado","Abrir ocorrência."), R("PHY-005","HIGH","ACERVO_FISICO","Divergência entre localização cadastrada e movimentação","Conciliar localização.")
    };
    private static GuardianRuleDefinition R(string c,string s,string cat,string d,string rec)=>new(c,1,s,cat,d,rec);
}
