[CmdletBinding()]param([Parameter(Mandatory)][ValidatePattern('^\d{2}\.\d+\.\d+$')][string]$Version,[ValidateSet('Release')][string]$Configuration='Release',[string]$OutputDirectory='artifacts/release',[switch]$Unofficial)
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path;Set-Location $root
$sha=(git rev-parse HEAD).Trim();$short=$sha.Substring(0,7);$dirty=[bool](git status --porcelain);if($dirty-and-not$Unofficial){throw 'Build oficial exige repositório limpo.'}
$work=Join-Path $OutputDirectory "work-$short";$package=Join-Path $work package;Remove-Item $work -Recurse -Force -ErrorAction Ignore;New-Item $package -ItemType Directory -Force|Out-Null
dotnet restore InovaGed.sln --locked-mode;dotnet build InovaGed.sln -c $Configuration --no-restore;dotnet test InovaGed.sln -c $Configuration --no-build
dotnet publish InovaGed.Web/InovaGed.Web.csproj -c $Configuration -r win-x64 --self-contained false -p:PublishProfile=IIS-Release -o "$package/app"
foreach($tool in @(@('InovaGed.Environment.Doctor','doctor'),@('InovaGed.Database.Migrator','migrator'),@('InovaGed.Deployment.Tool','deployment'))){dotnet publish "$($tool[0])/$($tool[0]).csproj" -c $Configuration -r win-x64 --self-contained false -o "$package/tools/$($tool[1])"}
Copy-Item database/migrations.manifest.json "$package/database/";Copy-Item database/migrations "$package/database/migrations" -Recurse;New-Item "$package/database/assertions" -ItemType Directory|Out-Null;Copy-Item database/assert_*.sql "$package/database/assertions/"
New-Item "$package/config","$package/deployment","$package/manifest","$package/evidence","$package/docs" -ItemType Directory|Out-Null;Copy-Item deploy/config/* "$package/config/";Copy-Item deploy/iis/* "$package/deployment/";Copy-Item deploy/templates/* "$package/deployment/";Copy-Item docs/deployment/README-DEPLOYMENT.md "$package/docs/";Copy-Item docs/deployment/iis-rollback.md "$package/docs/ROLLBACK.md"
$migrationHash=(Get-FileHash "$package/database/migrations.manifest.json" -Algorithm SHA256).Hash.ToLower();$now=[DateTime]::UtcNow.ToString('o');$branch=(git branch --show-current).Trim();$sdk=(dotnet --version).Trim()
$manifest=[ordered]@{schemaVersion='1.0';product='InovaGED';applicationVersion=$Version;commitSha=$sha;commitShortSha=$short;branch=$branch;buildNumber=$env:GITHUB_RUN_NUMBER ?? '';builtAtUtc=$now;targetFramework='net8.0';runtimeMode='framework-dependent';runtimeIdentifier='win-x64';hostingModel='inprocess';environmentDoctorVersion=$Version;databaseMigratorVersion=$Version;requiredDotnetRuntime='8.0';requiredAspNetCoreRuntime='8.0';requiredModules=@('AspNetCoreModuleV2');migrationManifestChecksum=$migrationHash;minimumSchemaVersion='4.1.20';maximumCompatibleSchemaVersion='4.1.24';packageChecksum='';files=@();healthEndpoints=@{live='/health/live';ready='/health/ready'}}
$manifest|ConvertTo-Json -Depth 8|Set-Content "$package/manifest/release-manifest.json" -Encoding utf8
$build=[ordered]@{sdk=$sdk;runtime=[Environment]::Version.ToString();msbuild=(dotnet msbuild -version -nologo|Select-Object -Last 1);operatingSystem=[Environment]::OSVersion.Platform.ToString();architecture=[Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString();configuration=$Configuration;builtAtUtc=$now;commitSha=$sha;repositoryState=$(if($dirty){'dirty-unofficial'}else{'clean'});publishedProjects=@('Web','Environment.Doctor','Database.Migrator','Deployment.Tool');fileCount=(Get-ChildItem $package -File -Recurse).Count};$build|ConvertTo-Json -Depth 5|Set-Content "$package/manifest/build-information.json"
$build|ConvertTo-Json -Depth 5|Set-Content "$package/evidence/build-summary.json";$lines=Get-ChildItem $package -File -Recurse|Where-Object Name -ne checksums.sha256|Sort-Object FullName|ForEach-Object{"$((Get-FileHash $_ -Algorithm SHA256).Hash.ToLower())  $($_.FullName.Substring($package.Length+1).Replace('\','/'))"};$lines|Set-Content "$package/checksums.sha256" -Encoding ascii
New-Item $OutputDirectory -ItemType Directory -Force|Out-Null;$zip=Join-Path $OutputDirectory "InovaGED-$Version-$short.zip";Compress-Archive "$package/*" $zip -Force;& dotnet "$package/tools/deployment/InovaGed.Deployment.Tool.dll" verify-package --package $zip;if($LASTEXITCODE){throw 'Validação final do ZIP falhou.'};Write-Output $zip
