using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.Contracts.Fiscalization;
using InovaGed.Application.Contracts.FiscalPortal;

namespace InovaGed.Infrastructure.Contracts.FiscalPortal;

public sealed class FiscalPortalService(IDbConnectionFactory factory,IContractFiscalizationService fiscalization) : IFiscalPortalPublicationService,IFiscalPortalManifestationService,IFiscalAcceptanceSignatureService,IFiscalPortalNotificationService
{
 const string PublicationColumns="id,tenant_id TenantId,Fiscalization_period_id FiscalizationPeriodId,publication_number PublicationNumber,access_mode AccessMode,status,published_at PublishedAt,expires_at ExpiresAt,fiscal_name FiscalName,fiscal_email FiscalEmail,viewed_at ViewedAt,decided_at DecidedAt";
 static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
 public async Task<Guid>CreatePublicationAsync(FiscalPortalPublicationCreateCommand c,CancellationToken ct){if(c.AccessMode=="TOKEN"&&string.IsNullOrWhiteSpace(c.AccessToken))throw new ArgumentException("Token seguro obrigatório.");await using var db=await factory.OpenAsync(ct);var exists=await db.ExecuteScalarAsync<bool>(new CommandDefinition("select exists(select 1 from ged.contract_fiscalization_period where tenant_id=@TenantId and id=@FiscalizationPeriodId and reg_status='A')",c,cancellationToken:ct));if(!exists)throw new KeyNotFoundException("Competência não encontrada.");var id=Guid.NewGuid();var number=$"PF-{DateTime.UtcNow:yyyyMM}-{id.ToString("N")[..8].ToUpperInvariant()}";await db.ExecuteAsync(new CommandDefinition(@"insert into ged.fiscal_portal_publication(id,tenant_id,fiscalization_period_id,publication_number,access_token_hash,access_mode,expires_at,fiscal_name,fiscal_email,notes) values(@id,@TenantId,@FiscalizationPeriodId,@number,@tokenHash,@AccessMode,@ExpiresAt,@FiscalName,@FiscalEmail,@Notes);insert into ged.fiscal_portal_event(tenant_id,publication_id,fiscalization_period_id,event_type,event_title,to_status,performed_by) values(@TenantId,@id,@FiscalizationPeriodId,'FISCAL_PORTAL_PUBLICATION_CREATED','Publicação criada no Portal do Fiscal','DRAFT',@CreatedBy)",new{id,c.TenantId,c.FiscalizationPeriodId,number,tokenHash=c.AccessToken is null?null:Hash(c.AccessToken),c.AccessMode,c.ExpiresAt,c.FiscalName,c.FiscalEmail,c.Notes,c.CreatedBy},cancellationToken:ct));return id;}
 public async Task PublishAsync(Guid t,Guid id,Guid u,CancellationToken ct){await Transition(t,id,u,"PUBLISHED","FISCAL_PORTAL_PUBLISHED","Competência publicada para o fiscal","status='DRAFT'",null,ct);await NotifyPublicationAsync(t,id,ct);}
 public Task RevokeAsync(Guid t,Guid id,Guid u,string reason,CancellationToken ct){if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Informe o motivo da revogação.");return Transition(t,id,u,"REVOKED","FISCAL_PORTAL_REVOKED","Acesso ao portal revogado","status not in('ACCEPTED','REVOKED')",reason,ct,true);}
 async Task Transition(Guid t,Guid id,Guid u,string status,string eventType,string title,string guard,string?description,CancellationToken ct,bool revoke=false){await using var db=await factory.OpenAsync(ct);var n=await db.ExecuteAsync(new CommandDefinition($@"with changed as(update ged.fiscal_portal_publication set status=@status,published_by=case when @status='PUBLISHED' then @u else published_by end,published_at=case when @status='PUBLISHED' then now() else published_at end,revoked_by=case when @revoke then @u end,revoked_at=case when @revoke then now() end,revoke_reason=case when @revoke then @description end where tenant_id=@t and id=@id and reg_status='A' and {guard} returning fiscalization_period_id,status) insert into ged.fiscal_portal_event(tenant_id,publication_id,fiscalization_period_id,event_type,event_title,to_status,performed_by,event_description) select @t,@id,fiscalization_period_id,@eventType,@title,@status,@u,@description from changed",new{t,id,u,status,eventType,title,description,revoke},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Publicação não encontrada ou transição inválida.");}
 public async Task<IReadOnlyList<FiscalPortalPublicationItem>>ListAsync(Guid t,FiscalPortalPublicationFilter f,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return(await db.QueryAsync<FiscalPortalPublicationItem>(new CommandDefinition($"select {PublicationColumns} from ged.fiscal_portal_publication where tenant_id=@t and reg_status='A' and (@p is null or fiscalization_period_id=@p) and (coalesce(@status,'')='' or status=@status) order by id desc",new{t,p=f.FiscalizationPeriodId,f.Status},cancellationToken:ct))).AsList();}
 public async Task<FiscalPortalPublicationDetails?>GetAsync(Guid t,Guid id,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var pub=await db.QuerySingleOrDefaultAsync<FiscalPortalPublicationItem>(new CommandDefinition($"select {PublicationColumns} from ged.fiscal_portal_publication where tenant_id=@t and id=@id and reg_status='A'",new{t,id},cancellationToken:ct));return pub is null?null:await Details(pub,t,ct);}
 public async Task<FiscalPortalPublicationDetails?>GetByTokenAsync(string token,CancellationToken ct){if(string.IsNullOrWhiteSpace(token))return null;await using var db=await factory.OpenAsync(ct);var pub=await db.QuerySingleOrDefaultAsync<(Guid TenantId,Guid Id)>(new CommandDefinition("select tenant_id TenantId,id from ged.fiscal_portal_publication where access_token_hash=@hash and access_mode='TOKEN' and reg_status='A' and status not in('DRAFT','REVOKED','EXPIRED') and (expires_at is null or expires_at>now())",new{hash=Hash(token)},cancellationToken:ct));return pub==default?null:await GetAsync(pub.TenantId,pub.Id,ct);}
 async Task<FiscalPortalPublicationDetails>Details(FiscalPortalPublicationItem pub,Guid t,CancellationToken ct){var fiscal=await fiscalization.GetPeriodAsync(t,pub.FiscalizationPeriodId,ct)??throw new KeyNotFoundException();await using var db=await factory.OpenAsync(ct);var events=(await db.QueryAsync<FiscalPortalEventItem>(new CommandDefinition("select id,event_type EventType,event_title EventTitle,event_description EventDescription,from_status FromStatus,to_status ToStatus,performed_name PerformedName,performed_at PerformedAt,host(ip_address) IpAddress from ged.fiscal_portal_event where tenant_id=@t and publication_id=@id and reg_status='A' order by performed_at desc",new{t,id=pub.Id},cancellationToken:ct))).AsList();var sig=await db.QuerySingleOrDefaultAsync<FiscalAcceptanceSignatureDetails>(new CommandDefinition("select id,signature_type SignatureType,signer_name SignerName,signer_email SignerEmail,signer_document SignerDocument,signed_at SignedAt,host(ip_address) IpAddress,signed_hash_sha256 SignedHashSha256,validation_status ValidationStatus from ged.fiscal_acceptance_signature where tenant_id=@t and publication_id=@id and reg_status='A'",new{t,id=pub.Id},cancellationToken:ct));return new(pub,fiscal,events,sig);}
 public async Task MarkViewedAsync(Guid t,Guid id,string?ip,string?agent,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition(@"with changed as(update ged.fiscal_portal_publication set status='VIEWED',viewed_at=now() where tenant_id=@t and id=@id and status='PUBLISHED' returning fiscalization_period_id) insert into ged.fiscal_portal_event(tenant_id,publication_id,fiscalization_period_id,event_type,event_title,from_status,to_status,ip_address,user_agent) select @t,@id,fiscalization_period_id,'FISCAL_PORTAL_VIEWED','Publicação visualizada','PUBLISHED','VIEWED',cast(@ip as inet),@agent from changed",new{t,id,ip=SafeIp(ip),agent},cancellationToken:ct));}
 public async Task<Guid>SubmitManifestationAsync(FiscalPortalManifestationCommand c,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var id=Guid.NewGuid();var n=await db.ExecuteAsync(new CommandDefinition(@"insert into ged.fiscal_portal_manifestation(id,tenant_id,publication_id,fiscalization_period_id,manifestation_type,decision,comments,submitted_by,submitted_name,submitted_email,ip_address,user_agent,payload_json) select @id,@TenantId,p.id,p.fiscalization_period_id,@ManifestationType,@Decision,@Comments,@SubmittedBy,@SubmittedName,@SubmittedEmail,cast(@ip as inet),@UserAgent,cast(@payload as jsonb) from ged.fiscal_portal_publication p where p.tenant_id=@TenantId and p.id=@PublicationId and p.status in('PUBLISHED','VIEWED') and (p.expires_at is null or p.expires_at>now())",new{id,c.TenantId,c.PublicationId,c.ManifestationType,c.Decision,c.Comments,c.SubmittedBy,c.SubmittedName,c.SubmittedEmail,ip=SafeIp(c.IpAddress),c.UserAgent,payload=JsonSerializer.Serialize(new{c.RelatedItem})},cancellationToken:ct));if(n==0)throw new InvalidOperationException("Publicação indisponível, expirada ou já decidida.");return id;}
 public Task AcceptAsync(FiscalPortalAcceptCommand c,CancellationToken ct)=>SignElectronicallyAsync(new(c.TenantId,c.PublicationId,c.UserId,c.Name,c.Email,null,true,c.Comments,c.IpAddress,c.UserAgent),ct);
 public Task RejectAsync(FiscalPortalRejectCommand c,CancellationToken ct)=>Decide(c.TenantId,c.PublicationId,c.UserId,FiscalPortalDecision.Reject,c.Reason+"\n"+c.Details,c.RelatedItem,c.Name,c.Email,c.IpAddress,c.UserAgent,ct);
 public Task RequestCorrectionAsync(FiscalPortalCorrectionRequestCommand c,CancellationToken ct)=>Decide(c.TenantId,c.PublicationId,c.UserId,FiscalPortalDecision.RequestCorrection,c.Reason+"\n"+c.Details,c.RelatedItem,c.Name,c.Email,c.IpAddress,c.UserAgent,ct);
 async Task Decide(Guid t,Guid id,Guid?u,string decision,string comments,string?item,string?name,string?email,string?ip,string?agent,CancellationToken ct){await SubmitManifestationAsync(new(t,id,"DECISION",decision,comments,u,name,email,ip,agent,item),ct);await using var db=await factory.OpenAsync(ct);var status=decision==FiscalPortalDecision.Reject?"REJECTED":"VIEWED";var eventType=decision==FiscalPortalDecision.Reject?"FISCAL_PORTAL_REJECTED":"FISCAL_PORTAL_CORRECTION_REQUESTED";await db.ExecuteAsync(new CommandDefinition(@"with changed as(update ged.fiscal_portal_publication set status=@status,decided_at=now() where tenant_id=@t and id=@id and status in('PUBLISHED','VIEWED') returning fiscalization_period_id) insert into ged.fiscal_portal_event(tenant_id,publication_id,fiscalization_period_id,event_type,event_title,event_description,to_status,performed_by,performed_name,ip_address,user_agent) select @t,@id,fiscalization_period_id,@eventType,case when @status='REJECTED' then 'Aceite rejeitado' else 'Correção solicitada' end,@comments,@status,@u,@name,cast(@ip as inet),@agent from changed;update ged.contract_fiscalization_period p set status='IN_REVIEW',rejection_reason=@comments,rejected_by=@u,rejected_at=now() from ged.fiscal_portal_publication x where x.id=@id and p.id=x.fiscalization_period_id and p.tenant_id=@t and p.status not in('CLOSED')",new{t,id,u,status,eventType,comments,name,ip=SafeIp(ip),agent},cancellationToken:ct));if(status=="REJECTED")await NotifyRejectionAsync(t,id,ct);else await NotifyCorrectionRequestAsync(t,id,ct);}
 public async Task<Guid>SignElectronicallyAsync(FiscalElectronicSignatureCommand c,CancellationToken ct){if(!c.DeclarationAccepted||string.IsNullOrWhiteSpace(c.SignerName))throw new ArgumentException("A identificação e a declaração de aceite são obrigatórias.");var payload=JsonSerializer.Serialize(new{c.TenantId,c.PublicationId,c.SignerName,c.SignerEmail,c.SignerDocument,c.Notes,Declaration=true,SignedAt=DateTimeOffset.UtcNow});var hash=Hash(payload);await using var db=await factory.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);var period=await db.ExecuteScalarAsync<Guid?>(new CommandDefinition("select fiscalization_period_id from ged.fiscal_portal_publication where tenant_id=@TenantId and id=@PublicationId and status in('PUBLISHED','VIEWED') and (expires_at is null or expires_at>now()) for update",c,tx,cancellationToken:ct))??throw new InvalidOperationException("Publicação indisponível ou já assinada.");var id=Guid.NewGuid();await db.ExecuteAsync(new CommandDefinition(@"insert into ged.fiscal_acceptance_signature(id,tenant_id,publication_id,fiscalization_period_id,signature_type,signer_user_id,signer_name,signer_email,signer_document,ip_address,user_agent,signed_hash_sha256,signed_payload_json,validation_status) values(@id,@TenantId,@PublicationId,@period,'ELECTRONIC',@UserId,@SignerName,@SignerEmail,@SignerDocument,cast(@ip as inet),@UserAgent,@hash,cast(@payload as jsonb),'VALID');insert into ged.fiscal_portal_manifestation(tenant_id,publication_id,fiscalization_period_id,manifestation_type,decision,comments,submitted_by,submitted_name,submitted_email,ip_address,user_agent,payload_json) values(@TenantId,@PublicationId,@period,'ACCEPTANCE','ACCEPT',@Notes,@UserId,@SignerName,@SignerEmail,cast(@ip as inet),@UserAgent,cast(@payload as jsonb));update ged.fiscal_portal_publication set status='ACCEPTED',decided_at=now() where tenant_id=@TenantId and id=@PublicationId;update ged.contract_fiscalization_period set status='APPROVED',approved_by=@UserId,approved_at=now() where tenant_id=@TenantId and id=@period and status not in('CLOSED');insert into ged.fiscal_portal_event(tenant_id,publication_id,fiscalization_period_id,event_type,event_title,to_status,performed_by,performed_name,ip_address,user_agent,payload_json) values(@TenantId,@PublicationId,@period,'FISCAL_PORTAL_ACCEPTED','Aceite eletrônico registrado','ACCEPTED',@UserId,@SignerName,cast(@ip as inet),@UserAgent,cast(@payload as jsonb)),(@TenantId,@PublicationId,@period,'FISCAL_PORTAL_SIGNATURE_REGISTERED','Assinatura eletrônica registrada','ACCEPTED',@UserId,@SignerName,cast(@ip as inet),@UserAgent,cast(@payload as jsonb))",new{id,c.TenantId,c.PublicationId,period,c.UserId,c.SignerName,c.SignerEmail,c.SignerDocument,ip=SafeIp(c.IpAddress),c.UserAgent,hash,payload,c.Notes},tx,cancellationToken:ct));await tx.CommitAsync(ct);await NotifyAcceptanceAsync(c.TenantId,c.PublicationId,ct);return id;}
 public async Task<Guid>RegisterIcpSignatureAsync(FiscalIcpSignatureCommand c,CancellationToken ct){if(c.ValidationStatus!="VALID")throw new InvalidOperationException("A assinatura ICP-Brasil deve ser validada pelo motor criptográfico antes do registro.");throw new NotSupportedException("O registro ICP-Brasil está preparado, mas exige integração com o validador de certificados deste ambiente.");}
 public async Task<FiscalAcceptanceSignatureDetails?>GetSignatureAsync(Guid t,Guid id,CancellationToken ct){await using var db=await factory.OpenAsync(ct);return await db.QuerySingleOrDefaultAsync<FiscalAcceptanceSignatureDetails>(new CommandDefinition("select id,signature_type SignatureType,signer_name SignerName,signer_email SignerEmail,signer_document SignerDocument,signed_at SignedAt,host(ip_address) IpAddress,signed_hash_sha256 SignedHashSha256,validation_status ValidationStatus from ged.fiscal_acceptance_signature where tenant_id=@t and id=@id and reg_status='A'",new{t,id},cancellationToken:ct));}
 public async Task<string>GenerateAcceptanceHashAsync(Guid t,Guid p,CancellationToken ct){var d=await fiscalization.GetPeriodAsync(t,p,ct)??throw new KeyNotFoundException();return Hash(JsonSerializer.Serialize(d));}
 public Task NotifyPublicationAsync(Guid t,Guid id,CancellationToken ct)=>Notification(t,id,"PUBLICATION_NOTIFICATION","Publicação comunicada ao fiscal",ct);public Task NotifyAcceptanceAsync(Guid t,Guid id,CancellationToken ct)=>Notification(t,id,"ACCEPTANCE_NOTIFICATION","Equipe notificada sobre o aceite",ct);public Task NotifyRejectionAsync(Guid t,Guid id,CancellationToken ct)=>Notification(t,id,"REJECTION_NOTIFICATION","Equipe notificada sobre a rejeição",ct);public Task NotifyCorrectionRequestAsync(Guid t,Guid id,CancellationToken ct)=>Notification(t,id,"CORRECTION_NOTIFICATION","Equipe notificada sobre o pedido de correção",ct);
 async Task Notification(Guid t,Guid id,string type,string title,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition("insert into ged.fiscal_portal_event(tenant_id,publication_id,fiscalization_period_id,event_type,event_title,event_description) select @t,id,fiscalization_period_id,@type,@title,'Notificação interna registrada. Envio de e-mail não configurado neste ambiente.' from ged.fiscal_portal_publication where tenant_id=@t and id=@id",new{t,id,type,title},cancellationToken:ct));}
 static string? SafeIp(string? ip)=>System.Net.IPAddress.TryParse(ip,out var parsed)?parsed.ToString():null;
}
