using System.ComponentModel.DataAnnotations;

namespace InovaGed.Application.Contracts.Fiscalization;

public static class ContractFiscalizationStatus { public const string Draft="DRAFT", Imported="IMPORTED", InReview="IN_REVIEW", WithGlosa="WITH_GLOSA", AwaitingContractorResponse="AWAITING_CONTRACTOR_RESPONSE", Approved="APPROVED", Rejected="REJECTED", Closed="CLOSED"; }
public static class ContractFiscalizationItemStatus { public const string PendingReview="PENDING_REVIEW", Approved="APPROVED", PartiallyGlossed="PARTIALLY_GLOSSED", FullyGlossed="FULLY_GLOSSED", AwaitingCorrection="AWAITING_CORRECTION", Rejected="REJECTED"; }
public static class ContractGlosaStatus { public const string Open="OPEN", Answered="ANSWERED", Accepted="ACCEPTED", Reverted="REVERTED", Maintained="MAINTAINED"; }

public sealed record ContractFiscalizationCreateCommand(Guid TenantId, DateOnly CompetenceMonth, string? ContractNumber, string? ContractorName, string? ContractingUnit, Guid? FiscalUserId, Guid? ManagerUserId, Guid OpenedBy, string? Notes);
public sealed record ContractFiscalizationFilter(DateOnly? CompetenceMonth=null, string? Status=null);
public sealed record ContractFiscalizationPeriodItem(Guid Id, DateOnly CompetenceMonth, string? ContractNumber, string? ContractorName, string? ContractingUnit, Guid? FiscalUserId, string Status, decimal TotalMeasuredAmount, decimal TotalApprovedAmount, decimal TotalGlossedAmount, decimal TotalUst, int TotalItems, DateTimeOffset OpenedAt);
public sealed record ContractFiscalizationItemDto(Guid Id, Guid FiscalizationPeriodId, Guid? ProductivityEntryId, Guid? ServiceCatalogId, string? ServiceCode, string ServiceName, string Unit, decimal MeasuredQuantity, decimal MeasuredUst, decimal UnitPrice, decimal MeasuredAmount, decimal ApprovedQuantity, decimal ApprovedUst, decimal ApprovedAmount, decimal GlossedQuantity, decimal GlossedAmount, string Status, string? SourceType, Guid? SourceId, int EvidenceCount, string? FiscalNotes, string? ContractorNotes, DateTimeOffset? PerformedAt=null, Guid? PerformedBy=null);
public sealed record ContractGlosaDto(Guid Id, Guid FiscalizationItemId, string GlosaType, string Reason, decimal GlossedQuantity, decimal GlossedAmount, string Status, string? ContractorResponse, DateTimeOffset CreatedAt, string? ResolutionNotes);
public sealed record ContractEvidenceDto(Guid Id, Guid? FiscalizationItemId, string EvidenceType, string Title, string? Description, string? ExternalUrl, string? SourceType, Guid? SourceId, DateTimeOffset AttachedAt);
public sealed record ContractEventDto(string EventType, string EventTitle, string? EventDescription, string? FromStatus, string? ToStatus, DateTimeOffset PerformedAt, Guid? PerformedBy);
public sealed record ContractFiscalizationPeriodDetails(ContractFiscalizationPeriodItem Period, IReadOnlyList<ContractFiscalizationItemDto> Items, IReadOnlyList<ContractGlosaDto> Glosas, IReadOnlyList<ContractEvidenceDto> Evidences, IReadOnlyList<ContractEventDto> Events);
public sealed record ContractGlosaCreateCommand(Guid TenantId, Guid FiscalizationItemId, Guid UserId, [Required] string GlosaType, [Required] string Reason, decimal GlossedQuantity, decimal GlossedAmount);
public sealed record ContractEvidenceCreateCommand(Guid TenantId, Guid FiscalizationPeriodId, Guid? FiscalizationItemId, Guid UserId, [Required] string EvidenceType, [Required] string Title, string? Description, string? ExternalUrl, string? SourceType, Guid? SourceId);
public sealed record ContractFiscalizationReport(ContractFiscalizationPeriodDetails Details, IReadOnlyList<ContractFiscalizationReportLine> Lines, bool Synthetic);
public sealed record ContractFiscalizationReportLine(int Number, string Description, string? Nature, decimal UnitPrice, decimal Quantity, decimal Ust, decimal TotalAmount, decimal GlossedAmount, decimal ApprovedAmount, string? Origin, string Status, string? FiscalNotes, DateTimeOffset? PerformedAt, Guid? OperatorId, int EvidenceCount);

public interface IContractFiscalizationService {
 Task<Guid>CreatePeriodAsync(ContractFiscalizationCreateCommand command,CancellationToken ct); Task ImportProductivityAsync(Guid tenantId,Guid periodId,Guid userId,CancellationToken ct); Task<ContractFiscalizationPeriodDetails?>GetPeriodAsync(Guid tenantId,Guid periodId,CancellationToken ct); Task<IReadOnlyList<ContractFiscalizationPeriodItem>>ListPeriodsAsync(Guid tenantId,ContractFiscalizationFilter filter,CancellationToken ct); Task<IReadOnlyList<ContractFiscalizationItemDto>>ListItemsAsync(Guid tenantId,Guid periodId,CancellationToken ct); Task ApproveItemAsync(Guid tenantId,Guid itemId,Guid userId,string?notes,CancellationToken ct); Task SubmitForApprovalAsync(Guid tenantId,Guid periodId,Guid userId,CancellationToken ct); Task ApprovePeriodAsync(Guid tenantId,Guid periodId,Guid userId,string?notes,CancellationToken ct); Task RejectPeriodAsync(Guid tenantId,Guid periodId,Guid userId,string reason,CancellationToken ct); Task ClosePeriodAsync(Guid tenantId,Guid periodId,Guid userId,CancellationToken ct); Task<Guid>AttachEvidenceAsync(ContractEvidenceCreateCommand command,CancellationToken ct);
}
public interface IContractGlosaService { Task<Guid>CreateGlosaAsync(ContractGlosaCreateCommand command,CancellationToken ct); Task RespondGlosaAsync(Guid tenantId,Guid glosaId,Guid userId,string response,CancellationToken ct); Task MaintainGlosaAsync(Guid tenantId,Guid glosaId,Guid userId,string notes,CancellationToken ct); Task RevertGlosaAsync(Guid tenantId,Guid glosaId,Guid userId,string notes,CancellationToken ct); }
public interface IContractFiscalizationReportService { Task<ContractFiscalizationReport>GenerateSyntheticReportAsync(Guid tenantId,Guid periodId,CancellationToken ct); Task<ContractFiscalizationReport>GenerateAnalyticalReportAsync(Guid tenantId,Guid periodId,CancellationToken ct); Task<string>ExportCsvAsync(Guid tenantId,Guid periodId,string reportType,CancellationToken ct); }
