using Dapper;
using InovaGed.Application.Common.Database;
using InovaGed.Application.PhysicalArchive2;

namespace InovaGed.Infrastructure.PhysicalArchive2;

public sealed class PhysicalArchive2Service(IDbConnectionFactory factory) : IPhysicalArchive2Service
{
    public async Task<PhysicalArchiveDashboard> DashboardAsync(Guid t, CancellationToken ct)
    {
        await using var db=await factory.OpenAsync(ct);
        var tables = new[] { "physical_location", "physical_box", "physical_box_document", "physical_movement", "physical_inventory_session", "physical_inventory_item", "physical_loan", "physical_custody_event" };
        var active = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var table in tables)
            active[table] = await HasColumnAsync(db, "ged", table, "reg_status", ct) ? " and reg_status='A'" : string.Empty;
        var r=await db.QuerySingleAsync<DashboardRow>(new CommandDefinition($"""
select (select count(*) from ged.physical_box where tenant_id=@t{active["physical_box"]}) as "Boxes",
(select count(*) from ged.physical_box where tenant_id=@t{active["physical_box"]} and label_code is not null) as "LabelledBoxes",
(select count(*) from ged.physical_box where tenant_id=@t{active["physical_box"]} and location_id is null) as "UnlocatedBoxes",
(select count(*) from ged.physical_box where tenant_id=@t{active["physical_box"]} and status='LOANED') as "LoanedBoxes",
(select count(*) from ged.physical_inventory_session where tenant_id=@t{active["physical_inventory_session"]} and status='OPEN') as "OpenInventories",
(select count(*) from ged.physical_loan where tenant_id=@t{active["physical_loan"]} and status='OPEN' and due_at<now()) as "OverdueLoans",
(select count(*) from ged.physical_movement where tenant_id=@t{active["physical_movement"]} and performed_at>=date_trunc('month',now())) as "MonthlyMovements",
(select count(*) from ged.physical_inventory_item where tenant_id=@t{active["physical_inventory_item"]} and result in ('PENDING','MISSING','WRONG_LOCATION')) as "PendingChecks"
""",new{t},cancellationToken:ct));
        return new(r.Boxes,r.LabelledBoxes,r.UnlocatedBoxes,r.LoanedBoxes,r.OpenInventories,r.OverdueLoans,r.MonthlyMovements,r.PendingChecks);
    }
    private static async Task<bool> HasColumnAsync(System.Data.IDbConnection connection,string schema,string table,string column,CancellationToken ct)
    {
        const string sql="select exists(select 1 from information_schema.columns where table_schema=@schema and table_name=@table and column_name=@column)";
        return await connection.ExecuteScalarAsync<bool>(new CommandDefinition(sql,new{schema,table,column},cancellationToken:ct));
    }
    public async Task<IReadOnlyList<PhysicalOption>> BoxesAsync(Guid t,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var code=await ResolvePhysicalBoxCodeExpressionAsync(db,ct);var rows=await db.QueryAsync<OptionRow>(new CommandDefinition($"select id as Id,{code} as Code,coalesce(title,{code}) as Name from ged.physical_box where tenant_id=@t and reg_status='A' order by {code}",new{t},cancellationToken:ct));return rows.Select(x=>new PhysicalOption(x.Id,x.Code,x.Name)).ToList();}
    public Task<IReadOnlyList<PhysicalOption>> LocationsAsync(Guid t,CancellationToken ct)=>Options("select id as Id,location_code as Code,name as Name from ged.physical_location where tenant_id=@t and reg_status='A' and is_active order by location_code",t,ct);
    private async Task<IReadOnlyList<PhysicalOption>> Options(string sql,Guid t,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var rows=await db.QueryAsync<OptionRow>(new CommandDefinition(sql,new{t},cancellationToken:ct));return rows.Select(x=>new PhysicalOption(x.Id,x.Code,x.Name)).ToList();}
    public async Task<IReadOnlyList<PhysicalActivity>> MovementsAsync(Guid t,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var code=await ResolvePhysicalBoxCodeExpressionAsync(db,ct,"b");var rows=await db.QueryAsync<ActivityRow>(new CommandDefinition($"select m.id as Id,{code} as Code,m.movement_type as Title,m.movement_type as Status,l.name as Location,m.performed_at as OccurredAt,m.reason as Detail from ged.physical_movement m join ged.physical_box b on b.id=m.box_id left join ged.physical_location l on l.id=m.to_location_id where m.tenant_id=@t and m.reg_status='A' order by m.performed_at desc limit 300",new{t},cancellationToken:ct));return MapActivities(rows);}
    public Task<IReadOnlyList<PhysicalActivity>> InventoriesAsync(Guid t,CancellationToken ct)=>Activities("select s.id as Id,s.session_number as Code,s.title as Title,s.status as Status,l.name as Location,s.started_at as OccurredAt,s.notes as Detail from ged.physical_inventory_session s left join ged.physical_location l on l.id=s.location_id where s.tenant_id=@t and s.reg_status='A' order by s.started_at desc",t,ct);
    public async Task<IReadOnlyList<PhysicalActivity>> LoansAsync(Guid t,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var code=await ResolvePhysicalBoxCodeExpressionAsync(db,ct,"b");var rows=await db.QueryAsync<ActivityRow>(new CommandDefinition($"select p.id as Id,p.loan_number as Code,p.requested_by_name as Title,case when p.status='OPEN' and p.due_at<now() then 'OVERDUE' else p.status end as Status,{code} as Location,p.loaned_at as OccurredAt,p.reason as Detail from ged.physical_loan p left join ged.physical_box b on b.id=p.box_id where p.tenant_id=@t and p.reg_status='A' order by p.loaned_at desc",new{t},cancellationToken:ct));return MapActivities(rows);}
    public Task<IReadOnlyList<PhysicalActivity>> CustodyAsync(Guid t,Guid boxId,CancellationToken ct)=>Activities("select id as Id,event_type as Code,title as Title,event_type as Status,source_type as Location,occurred_at as OccurredAt,concat_ws(' · ',description,correlation_id) as Detail from ged.physical_custody_event where tenant_id=@t and source_type='BOX' and source_id=@boxId and reg_status='A' order by occurred_at desc",t,ct,new{boxId});
    private async Task<IReadOnlyList<PhysicalActivity>> Activities(string sql,Guid t,CancellationToken ct,object? extra=null){await using var db=await factory.OpenAsync(ct);var p=new DynamicParameters(extra);p.Add("t",t);var rows=await db.QueryAsync<ActivityRow>(new CommandDefinition(sql,p,cancellationToken:ct));return rows.Select(x=>new PhysicalActivity(x.Id,x.Code,x.Title,x.Status,x.Location,AsOffset(x.OccurredAt),x.Detail)).ToList();}
    private static IReadOnlyList<PhysicalActivity> MapActivities(IEnumerable<ActivityRow> rows)=>rows.Select(x=>new PhysicalActivity(x.Id,x.Code,x.Title,x.Status,x.Location,AsOffset(x.OccurredAt),x.Detail)).ToList();
    private static async Task<string> ResolvePhysicalBoxCodeExpressionAsync(System.Data.IDbConnection connection,CancellationToken ct,string? alias=null)
    {
        var column=await connection.QueryFirstOrDefaultAsync<string>(new CommandDefinition("select column_name from information_schema.columns where table_schema='ged' and table_name='physical_box' and column_name=any(array['box_code','box_no','code']) order by array_position(array['box_code','box_no','code'],column_name) limit 1",cancellationToken:ct));
        var prefix=string.IsNullOrWhiteSpace(alias)?string.Empty:alias+".";
        return column is "box_code" or "box_no" or "code" ? prefix+column : prefix+"id::text";
    }
    public async Task<PhysicalInventoryDetails?> InventoryAsync(Guid t,Guid id,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var s=await db.QuerySingleOrDefaultAsync<InventoryRow>(new CommandDefinition("select s.id as Id,s.session_number as SessionNumber,s.title as Title,s.status as Status,s.location_id as LocationId,l.name as Location,s.started_at as StartedAt from ged.physical_inventory_session s left join ged.physical_location l on l.id=s.location_id where s.tenant_id=@t and s.id=@id and s.reg_status='A'",new{t,id},cancellationToken:ct));if(s is null)return null;var code=await ResolvePhysicalBoxCodeExpressionAsync(db,ct,"b");var items=await Activities($"select i.id as Id,coalesce({code},i.scanned_code,'—') as Code,coalesce(b.title,'Caixa conferida') as Title,i.result as Status,l.name as Location,coalesce(i.scanned_at,s.started_at) as OccurredAt,i.notes as Detail from ged.physical_inventory_item i join ged.physical_inventory_session s on s.id=i.session_id left join ged.physical_box b on b.id=i.box_id left join ged.physical_location l on l.id=i.found_location_id where i.tenant_id=@t and i.session_id=@id and i.reg_status='A' order by occurred_at desc",t,ct,new{id});return new(s.Id,s.SessionNumber,s.Title,s.Status,s.LocationId,s.Location,AsOffset(s.StartedAt),items);}
    public async Task<Guid> StartInventoryAsync(Guid t,Guid? locationId,string title,Guid? userId,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var id=Guid.NewGuid();await db.ExecuteAsync(new CommandDefinition("insert into ged.physical_inventory_session(id,tenant_id,session_number,title,location_id,started_by) values(@id,@t,'INV-'||to_char(now(),'YYYYMMDD-HH24MISS'),@title,@locationId,@userId)",new{id,t,title=title.Trim(),locationId,userId},cancellationToken:ct));return id;}
    public async Task ScanAsync(Guid t,Guid sessionId,string code,Guid? foundLocationId,Guid? userId,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var boxCode=await ResolvePhysicalBoxCodeExpressionAsync(db,ct);await db.ExecuteAsync(new CommandDefinition($"""
insert into ged.physical_inventory_item(tenant_id,session_id,box_id,scanned_code,expected_location_id,found_location_id,result,scanned_by,scanned_at)
select @t,@sessionId,b.id,@code,b.location_id,@foundLocationId,case when b.id is null then 'UNEXPECTED' when b.location_id is not distinct from @foundLocationId then 'FOUND' else 'WRONG_LOCATION' end,@userId,now()
from (select 1) x left join lateral(select id,location_id from ged.physical_box where tenant_id=@t and reg_status='A' and (upper({boxCode})=upper(@code) or upper(coalesce(label_code,''))=upper(@code)) limit 1)b on true;
""",new{t,sessionId,code=code.Trim(),foundLocationId,userId},cancellationToken:ct));}
    public async Task CloseInventoryAsync(Guid t,Guid sessionId,Guid? userId,string? notes,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition("update ged.physical_inventory_session set status='CLOSED',closed_by=@userId,closed_at=now(),notes=@notes where tenant_id=@t and id=@sessionId and status='OPEN'",new{t,sessionId,userId,notes},cancellationToken:ct));}
    public async Task MoveAsync(Guid t,Guid boxId,Guid toLocationId,string type,string? reason,Guid? userId,string? userName,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await using var tx=await db.BeginTransactionAsync(ct);var from=await db.ExecuteScalarAsync<Guid?>(new CommandDefinition("select location_id from ged.physical_box where tenant_id=@t and id=@boxId and reg_status='A' for update",new{t,boxId},tx,cancellationToken:ct));await db.ExecuteAsync(new CommandDefinition("update ged.physical_box set location_id=@toLocationId,updated_at=now() where tenant_id=@t and id=@boxId;insert into ged.physical_movement(tenant_id,box_id,from_location_id,to_location_id,movement_type,reason,performed_by,performed_by_name) values(@t,@boxId,@from,@toLocationId,@type,@reason,@userId,@userName);insert into ged.physical_custody_event(tenant_id,source_type,source_id,event_type,title,description,performed_by,performed_by_name,correlation_id) values(@t,'BOX',@boxId,'PHYSICAL_BOX_MOVED','Caixa movimentada',@reason,@userId,@userName,gen_random_uuid()::text)",new{t,boxId,from,toLocationId,type,reason,userId,userName},tx,cancellationToken:ct));await tx.CommitAsync(ct);}
    public async Task<Guid> LoanAsync(Guid t,Guid boxId,string requester,string? department,string? reason,DateTimeOffset? dueAt,Guid? userId,CancellationToken ct){await using var db=await factory.OpenAsync(ct);var id=Guid.NewGuid();await db.ExecuteAsync(new CommandDefinition("insert into ged.physical_loan(id,tenant_id,loan_number,box_id,requested_by_name,requested_by_department,reason,loaned_by,due_at) values(@id,@t,'EMP-'||to_char(now(),'YYYYMMDD-HH24MISS'),@boxId,@requester,@department,@reason,@userId,@dueAt);update ged.physical_box set status='LOANED',current_holder=@requester,updated_at=now() where tenant_id=@t and id=@boxId;insert into ged.physical_custody_event(tenant_id,source_type,source_id,event_type,title,description,performed_by) values(@t,'BOX',@boxId,'PHYSICAL_LOAN_CREATED','Empréstimo registrado',@reason,@userId)",new{id,t,boxId,requester=requester.Trim(),department,reason,userId,dueAt},cancellationToken:ct));return id;}
    public async Task ReturnLoanAsync(Guid t,Guid loanId,string? notes,Guid? userId,CancellationToken ct){await using var db=await factory.OpenAsync(ct);await db.ExecuteAsync(new CommandDefinition("update ged.physical_loan set status='RETURNED',returned_by=@userId,returned_at=now(),return_notes=@notes where tenant_id=@t and id=@loanId and status='OPEN';update ged.physical_box b set status='ACTIVE',current_holder=null,updated_at=now() from ged.physical_loan p where p.tenant_id=@t and p.id=@loanId and b.tenant_id=p.tenant_id and b.id=p.box_id;insert into ged.physical_custody_event(tenant_id,source_type,source_id,event_type,title,description,performed_by) select @t,'BOX',box_id,'PHYSICAL_LOAN_RETURNED','Caixa devolvida',@notes,@userId from ged.physical_loan where tenant_id=@t and id=@loanId",new{t,loanId,notes,userId},cancellationToken:ct));}
    private static DateTimeOffset AsOffset(DateTime value)=>new(DateTime.SpecifyKind(value,DateTimeKind.Utc));
    private sealed class DashboardRow{public long Boxes{get;set;}public long LabelledBoxes{get;set;}public long UnlocatedBoxes{get;set;}public long LoanedBoxes{get;set;}public long OpenInventories{get;set;}public long OverdueLoans{get;set;}public long MonthlyMovements{get;set;}public long PendingChecks{get;set;}}
    private sealed class OptionRow{public Guid Id{get;set;}public string Code{get;set;}="";public string Name{get;set;}="";}
    private sealed class ActivityRow{public Guid Id{get;set;}public string Code{get;set;}="";public string Title{get;set;}="";public string Status{get;set;}="";public string? Location{get;set;}public DateTime OccurredAt{get;set;}public string? Detail{get;set;}}
    private sealed class InventoryRow{public Guid Id{get;set;}public string SessionNumber{get;set;}="";public string Title{get;set;}="";public string Status{get;set;}="";public Guid? LocationId{get;set;}public string? Location{get;set;}public DateTime StartedAt{get;set;}}
}
