namespace InovaGed.Application.SmartWorkflow;

public static class SmartWorkflowTaskType { public const string OcrPending="OCR_PENDING", ClassificationPending="CLASSIFICATION_PENDING", ClassificationSuggestionReview="CLASSIFICATION_SUGGESTION_REVIEW", RetentionSuggestionReview="RETENTION_SUGGESTION_REVIEW", SensitiveDataReview="SENSITIVE_DATA_REVIEW", QualityIssueReview="QUALITY_ISSUE_REVIEW", LabelPrintPending="LABEL_PRINT_PENDING", LabelReprintReview="LABEL_REPRINT_REVIEW", BoxLocationPending="BOX_LOCATION_PENDING", AssistantActionReview="ASSISTANT_ACTION_REVIEW", IncidentReview="INCIDENT_REVIEW"; }
public static class SmartWorkflowTaskStatus { public const string Open="OPEN", InProgress="IN_PROGRESS", Waiting="WAITING", Completed="COMPLETED", Cancelled="CANCELLED", Rejected="REJECTED"; }
public static class SmartWorkflowPriority { public const string Critical="CRITICAL", High="HIGH", Medium="MEDIUM", Low="LOW"; }

public sealed record SmartWorkflowDashboard(int OpenTasks,int OverdueTasks,int CriticalTasks,int InProgressTasks,int CompletedToday,int ClassificationPending,int RetentionPending,int AssistantPending);
public sealed record SmartWorkflowTaskFilter(Guid TenantId,string? Status=null,string? Priority=null,string? TaskType=null,string? SourceType=null,bool OverdueOnly=false,Guid? DocumentId=null);
public sealed record SmartWorkflowTaskItem(Guid Id,string TaskNumber,string SourceType,string TaskType,string Title,string Priority,string Status,string? AssignedToName,DateTimeOffset? DueAt,DateTimeOffset OpenedAt)
{ public string SlaLabel => DueAt is null ? "Sem SLA" : DueAt < DateTimeOffset.UtcNow ? "Atrasada" : DueAt.Value.UtcDateTime.Date == DateTime.UtcNow.Date ? "Vence hoje" : "No prazo"; }
public sealed record SmartWorkflowEventItem(string EventType,string Message,string? PerformedByName,DateTimeOffset OccurredAt);
public sealed record SmartWorkflowTaskDetails(SmartWorkflowTaskItem Task,Guid? SourceId,Guid? RelatedDocumentId,Guid? RelatedBoxId,Guid? RelatedIncidentId,Guid? RelatedSuggestionId,string? Description,string? RecommendedAction,string? CompletionNotes,IReadOnlyList<SmartWorkflowEventItem> Events);
public sealed record SmartWorkflowTaskCreateCommand(Guid TenantId,string SourceType,Guid? SourceId,string TaskType,string Title,string? Description,string? RecommendedAction,string Priority,Guid? RelatedDocumentId=null,Guid? RelatedBoxId=null,Guid? RelatedIncidentId=null,Guid? RelatedSuggestionId=null,Guid? OpenedBy=null);
public sealed record SmartWorkflowRuleItem(string Code,string Title,string SourceType,string TaskType,string Priority,int SlaHours,bool Enabled);

public interface ISmartWorkflowTaskService { Task<SmartWorkflowDashboard> GetDashboardAsync(Guid tenantId,CancellationToken ct); Task<IReadOnlyList<SmartWorkflowTaskItem>> ListAsync(SmartWorkflowTaskFilter filter,CancellationToken ct); Task<SmartWorkflowTaskDetails?> GetAsync(Guid tenantId,Guid taskId,CancellationToken ct); Task<Guid> CreateAsync(SmartWorkflowTaskCreateCommand command,CancellationToken ct); Task AssignAsync(Guid tenantId,Guid taskId,Guid assignedTo,Guid performedBy,CancellationToken ct); Task StartAsync(Guid tenantId,Guid taskId,Guid performedBy,CancellationToken ct); Task CompleteAsync(Guid tenantId,Guid taskId,Guid performedBy,string notes,CancellationToken ct); Task CancelAsync(Guid tenantId,Guid taskId,Guid performedBy,string reason,CancellationToken ct); Task<IReadOnlyList<SmartWorkflowRuleItem>> ListRulesAsync(Guid tenantId,CancellationToken ct); }
public interface ISmartWorkflowRuleEngine { Task<IReadOnlyList<SmartWorkflowTaskCreateCommand>> DetectPendingTasksAsync(Guid tenantId,CancellationToken ct); Task<int> GenerateTasksAsync(Guid tenantId,Guid? performedBy,CancellationToken ct); }
public interface ISmartWorkflowNumberGenerator { Task<string> NextAsync(Guid tenantId,CancellationToken ct); }
