<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../InovaGed.Application/InovaGed.Application.csproj" />
    <ProjectReference Include="../InovaGed.Infrastructure/InovaGed.Infrastructure.csproj" />
    <ProjectReference Include="../InovaGed.Environment.Doctor/InovaGed.Environment.Doctor.csproj" />
    <ProjectReference Include="../WebGed.WebApi/WebGed.WebApi.csproj" />
    <ProjectReference Include="../InovaGed.Web/InovaGed.Web.csproj" />
  </ItemGroup>
</Project>
